### ISSUE TITLE
ConnectionClosed: Connection to server.ip.address.and:5672 failed: timeout

### ISSUE THREAD

**Issue by arnaldojvg** [pika/pika#1024]
I'm using the example connection code from the rabbitmq python tutorial from my home PC, just changed the address:

import pika

connection = pika.BlockingConnection(pika.ConnectionParameters(host='server.ip.address.and', port=5672))
channel = connection.channel()

channel.queue_declare(queue='hello')

def callback(ch, method, properties, body):
   print(body)

channel.basic_consume(callback,
                      queue='hello',
                      no_ack=True)

print(' [*] Waiting for messages. To exit press CTRL+C')
channel.start_consuming()

I'm my server /etc/rabbitmq/rabbitmq.config i have:
loopback_users = none
all the other lines are commented (#)
and im getting the error:
Traceback (most recent call last):

  File "<ipython-input-1-d1bd3ce57be2>", line 1, in <module>
    runfile('C:/Users/arnal/Desktop/rabbit/recv.py', wdir='C:/Users/arnal/Desktop/rabbit')

  File "C:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 692, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/arnal/Desktop/rabbit/recv.py", line 11, in <module>
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='167.99.54.148', port=5672))

  File "C:\Anaconda\lib\site-packages\pika\adapters\blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()

  File "C:\Anaconda\lib\site-packages\pika\adapters\blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)

  File "C:\Anaconda\lib\site-packages\pika\adapters\blocking_connection.py", line 468, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)

ConnectionClosed: Connection to  server.ip.address.and:5672 failed: timeout

What can i do to connect to the rabbitmq server remotely?

**Comment by lukebakken** [comment]
> ConnectionClosed: Connection to server.ip.address.and:5672 failed: timeout

You need to diagnose why your connection isn't succeeding: https://www.rabbitmq.com/troubleshooting-networking.html
