### ISSUE TITLE
BlockingConnection heartbeat attribute can be undefined

### ISSUE THREAD

**Issue by michaelklishin** [pika/pika#1036]
I've been testing connection recovery docs and managed to run into the following exceptions several times:

```
Traceback (most recent call last):
  File "./blocking_consumer_recovery2.py", line 31, in <module>
    channel.start_consuming()
  File "/Users/antares/Development/RabbitMQ/pika.git/pika/adapters/blocking_connection.py", line 1878, in start_consuming
    self._process_data_events(time_limit=None)
  File "/Users/antares/Development/RabbitMQ/pika.git/pika/adapters/blocking_connection.py", line 2040, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/Users/antares/Development/RabbitMQ/pika.git/pika/adapters/blocking_connection.py", line 814, in process_data_events
    self._flush_output(common_terminator)
  File "/Users/antares/Development/RabbitMQ/pika.git/pika/adapters/blocking_connection.py", line 525, in _flush_output
    self._impl.ioloop.process_timeouts()
  File "/Users/antares/Development/RabbitMQ/pika.git/pika/adapters/select_connection.py", line 462, in process_timeouts
    self._timer.process_timeouts()
  File "/Users/antares/Development/RabbitMQ/pika.git/pika/adapters/select_connection.py", line 297, in process_timeouts
    timeout.callback()
  File "/Users/antares/Development/RabbitMQ/pika.git/pika/heartbeat.py", line 104, in send_and_check
    self._start_timer()
  File "/Users/antares/Development/RabbitMQ/pika.git/pika/heartbeat.py", line 167, in _start_timer
    if self.active:
  File "/Users/antares/Development/RabbitMQ/pika.git/pika/heartbeat.py", line 53, in active
    return self._connection.heartbeat is self
AttributeError: 'SelectConnection' object has no attribute 'heartbeat'
```

unfortunately I don't have a 100% clear idea of how to reproduce this but all I did was restarting down nodes cleanly. At some point during recovery attempt the above exception would make the process exit. Perhaps the code that checks for `self._connection.heartbeat` should be more defensive.

**Comment by vitaly-krugl** [comment]
@michaelklishin , are you using the code base from current pika master?

**Comment by vitaly-krugl** [comment]
I see now, it's my bug. I renamed that member to `_heartbeat_checker` in Connection, but failed to update the code in HeartbeatChecker class. Would be nice to add a heartbeat checker test method that would detect it before fixing.

**Comment by michaelklishin** [comment]
@vitaly-krugl FTR, I was using the tip of master + a PR by @hairyhum.

**Comment by michaelklishin** [comment]
@vitaly-krugl so should this be addressed in a separate PR or #1034? As our experience with other clients suggests, automatically testing heartbeat implementations beyond a couple of very common scenarios is hard. More often than not we modify the server e.g. to not send heartbeat frames to imitate certain failures. So I'd apply a fix and test with the recovery example we now have in the docs.

**Comment by vitaly-krugl** [comment]
Once a connection is created in the new test in  acceptance,
async_adapters_test.py, simply access the HeartbeatChecker.active property
via connection.heartbeat_checker.active. it should not crash and should
return true. As simple as that :)

**Comment by vitaly-krugl** [comment]
I'll do it separately, since the bug is actually at the async layer (which is also used by BlockingConnection)

**Comment by vitaly-krugl** [comment]
@michaelklishin - see pull request #1041 that fixes this
