### ISSUE TITLE
IncompatibleProtocolError: (-1, 'EOF')

### ISSUE THREAD

**Issue by fl0wx** [pika/pika#1047]
Hey all,

here a short roundup of my issue:

- IncompatibleProtocolError: (-1, 'EOF') if i try to connect to my rabbitmq server.
- erlang 20.3 on ubuntu  16.04 LTS - WSL
- rabbitmq 3.6.15 on ubuntu  16.04 LTS - WSL
- python 3.4.4 on windows
- pika 0.11.2

Testcode to connect:
```
import pika
import logging

logging.basicConfig(level=logging.DEBUG)

parameters = pika.URLParameters('amqp://test:test@xxx.xxx.xxx:5672/queuetest')
connection = pika.BlockingConnection(parameters)
```
- User test has all rights in queuetest.
- web management ui is working well
- nothing special is logged in rabbitmq log

Output of Python:
```
DEBUG:pika.adapters.select_connection:Using SelectPoller
DEBUG:pika.callback:Added: {'arguments': None, 'one_shot': True, 'callback': <bound method SelectConnection._on_connection_start of <SelectConnection CLOSED socket=None params=<URLParameters host=xxx.xxx.xxx port=5672 virtual_host=queuetest ssl=False>>>, 'only': None, 'calls': 1}
DEBUG:pika.callback:Added: {'arguments': None, 'one_shot': True, 'callback': <bound method SelectConnection._on_connection_close of <SelectConnection CLOSED socket=None params=<URLParameters host=xxx.xxx.xxx port=5672 virtual_host=queuetest ssl=False>>>, 'only': None, 'calls': 1}
DEBUG:pika.callback:Added: {'arguments': None, 'one_shot': False, 'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x000000000578BF08>>, 'only': None}
DEBUG:pika.callback:Added: {'arguments': None, 'one_shot': False, 'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x00000000050D0488>>, 'only': None}
DEBUG:pika.callback:Added: {'arguments': None, 'one_shot': False, 'callback': <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x000000000578BA08>>, 'only': None}
DEBUG:pika.adapters.select_connection:add_timeout: added timeout 1257082467739489093; deadline=0 at 1526393614.194047
INFO:pika.adapters.base_connection:Connecting to xx.xx.xx.xx:5672
ERROR:pika.adapters.base_connection:Read empty data, calling disconnect
INFO:pika.connection:Disconnected from RabbitMQ at xxx.xxx.xxx:5672 (-1): EOF
ERROR:pika.connection:Incompatible Protocol Versions
ERROR:pika.connection:Connection setup failed due to The protocol returned by the server is not supported: (-1, 'EOF')
DEBUG:pika.callback:Processing 0:_on_connection_error
DEBUG:pika.callback:Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x000000000578BF08>> for "0:_on_connection_error"
DEBUG:pika.callback:Processing 0:_on_connection_closed
DEBUG:pika.callback:Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x000000000578BA08>> for "0:_on_connection_closed"
DEBUG:pika.callback:Incremented callback reference counter: {'arguments': None, 'one_shot': True, 'callback': <bound method SelectConnection._on_connection_start of <SelectConnection CLOSED socket=None params=<URLParameters host=xxx.xxx.xxx port=5672 virtual_host=queuetest ssl=False>>>, 'only': None, 'calls': 2}
DEBUG:pika.callback:Incremented callback reference counter: {'arguments': None, 'one_shot': True, 'callback': <bound method SelectConnection._on_connection_close of <SelectConnection CLOSED socket=None params=<URLParameters host=xxx.xxx.xxx port=5672 virtual_host=queuetest ssl=False>>>, 'only': None, 'calls': 2}
ERROR:pika.adapters.blocking_connection:Connection open failed - The protocol returned by the server is not supported: (-1, 'EOF')
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\181.4668.75\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Users\xxx\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\181.4668.75\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\xxx\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\181.4668.75\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\xxx\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\181.4668.75\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/xxx/PycharmProjects/queuetest/test.py", line 7, in <module>
    connection = pika.BlockingConnection(parameters)
  File "C:\Users\xxx\PycharmProjects\queuetest\env\lib\site-packages\pika\adapters\blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "C:\Users\xxx\PycharmProjects\queuetest\env\lib\site-packages\pika\adapters\blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "C:\Users\xxx\PycharmProjects\queuetest\env\lib\site-packages\pika\adapters\blocking_connection.py", line 466, in _flush_output
    raise maybe_exception
pika.exceptions.IncompatibleProtocolError: (-1, 'EOF')
```

Also tried to use Credentials instead of URL. But this results in the same way.

Any suggestions?

Thanks and kr 

Flow

**Comment by lukebakken** [comment]
```
ERROR:pika.adapters.base_connection:Read empty data, calling disconnect
```

Something between your Pika program and RabbitMQ is disconnecting the socket (like a firewall), or perhaps RabbitMQ isn't actually listening on port `5672`. Have you checked with `netstat`?

If you need further assistance, please follow up on a mailing list. We prefer to only use GitHub issues for actual bugs or feature requests, not root cause analysis.

https://groups.google.com/forum/#!forum/pika-python

https://groups.google.com/forum/#!forum/rabbitmq-users

**Comment by fl0wx** [comment]
@lukebakken Thanks a lot, i will try my luck at the google groups
