### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Krismix1** [pika/pika#1099]
We are currently using pika to send some data to rabbitmq, but we found out that the data doesn't get published completely (until the script is stopped through a KeyboardInterrupt). Our code is based on the asynchronous example found in the docs (see link below). We also tried running the example for asynchronous connection, but it also throws an error.
The scripts have been executed with:
- python3.5.3
- pika 0.11.2 and pika 0.12.0
- rabbitmq 3.6.6-1
- Ubuntu 16.04 LTS, Ubuntu  17.04 

https://pika.readthedocs.io/en/0.11.2/examples/asynchronous_publisher_example.html

The example gives the following stacktrace:
`Traceback (most recent call last):
  File "pikatest.py", line 330, in <module>
    main()
  File "pikatest.py", line 326, in main
    example.run()
  File "pikatest.py", line 283, in run
    self._connection.ioloop.start()
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/adapters/select_connection.py", line 461, in start
    self._poller.start()
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/adapters/select_connection.py", line 721, in start
    self.poll()
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/adapters/select_connection.py", line 1114, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/adapters/select_connection.py", line 831, in _dispatch_fd_events
    handler(fileno, events)
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/adapters/base_connection.py", line 410, in _handle_events
    self._handle_read()
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/adapters/base_connection.py", line 464, in _handle_read
    self._on_data_available(data)
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/connection.py", line 2021, in _on_data_available
    self._process_frame(frame_value)
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/connection.py", line 2142, in _process_frame
    if self._process_callbacks(frame_value):
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/connection.py", line 2123, in _process_callbacks
    frame_value)  # Args
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/home/cristi/.local/lib/python3.5/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "pikatest.py", line 178, in on_queue_declareok
    callback=lambda x: self.start_publishing())
TypeError: queue_bind() got multiple values for argument 'callback'
`

**Comment by lukebakken** [comment]
You are probably using example code that is written for the upcoming Pika `1.0.0` release, where the argument order has changed for several API calls, like `queue_bind`.

Please select the correct tag from the GitHub dropdown, **then** navigate to the appropriate example code. For instance, for version `0.12.0`, use the code at this link:

https://github.com/pika/pika/tree/0.12.0/examples
