### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by moelius** [pika/pika#1105]
Hi I'm trying to use 0.12 version. Have this traceback after some time working :
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/moelius/Documents/work/projects/gromozeka/gromozeka/brokers/rabbit.py", line 67, in worker_run
    self.broker.connection.ioloop.start()
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 461, in start
    self._poller.start()
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 721, in start
    self.poll()
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 994, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 831, in _dispatch_fd_events
    handler(fileno, events)
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 410, in _handle_events
    self._handle_read()
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 461, in _handle_read
    connection.InternalCloseReasons.SOCKET_ERROR, "EOF")
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/connection.py", line 2057, in _on_terminate
    self._adapter_disconnect()
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 109, in _adapter_disconnect
    self.ioloop.remove_handler(self.socket.fileno())
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 454, in remove_handler
    self._poller.remove_handler(fileno)
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 656, in remove_handler
    self._unregister_fd(fileno, events_to_clear=events_cleared)
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1070, in _unregister_fd
    fileno, events=0, events_to_clear=events_to_clear, events_to_set=0)
  File "/Users/moelius/Documents/work/projects/gromozeka/venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1059, in _modify_fd_events
    self._kqueue.control(kevents, 0)
FileNotFoundError: [Errno 2] No such file or directory
```

Version 0.10.0 works good without this error. After this version I'd tried all versions. and they have this error.  Tried on linux and macOS with `pika.adapters.SelectConnection`.

**Comment by lukebakken** [comment]
Hello!

I don't like to guess, so could you please provide the following information:

* How long is "some time working"?
* Can you please provide your source code in `rabbit.py`? I need this code to be able to reproduce your issue. There is a chance you are not using `SelectConnection` correctly.
* It looks like you're using Python `3.7.0`, is that true?
* What version(s) of Linux and OS X were tried? Did you also use Python `3.7.0`?

Thanks!

**Comment by moelius** [comment]
Hi, thanks for your reply.

Answers to your questions:

> How long is "some time working"

2-3 minutes, then application freezes for 2-4 minutes and then error appears

> Can you please provide your source code in rabbit.py? I need this code to be able to reproduce your issue. There is a chance you are not using SelectConnection correctly.

this is my project https://github.com/moelius/gromozeka (the very beginning of it).
Here some documentation http://gromozeka.readthedocs.io/en/latest/.
See https://github.com/moelius/gromozeka/blob/master/gromozeka/brokers/rabbit.py - here I use pika. 

you can install it with pip:

`pip install gromozeka`

You need to run redis also: You can use docker:

`docker run --name gromozeka_redis -p6379:6379 -d redis` 

But this version without error (pika==0.10.0). If you change this to 0.12.0 ...

> It looks like you're using Python 3.7.0, is that true?

3.6.5 - 3.7.0 tested

> What version(s) of Linux and OS X were tried? Did you also use Python 3.7.0?

macOS - High Siera 10.13.6
linux - Ubuntu 16.04.5 LTS

Code to reproduce error:

```python
import time
from random import random

from gromozeka import Gromozeka, ThreadWorker
from gromozeka import task
from gromozeka.primitives.base import BrokerPoint


@task(bind=True)
def test_func_one(self, sleep_time, word):
    """

    Args:
        self(gromozeka.primitives.Task):
        sleep_time(int): Time to sleep
        word(str): Word to print
     """
    self.logger.info('start working')
    self.logger.info('Job is done. Word is %s', word)
    return random()


if __name__ == '__main__':
    app = Gromozeka().config_from_dict(
        dict(broker_url='amqp://guest:guest@localhost:5672/%2F', backend_url='redis://localhost'))

    broker_point_first = BrokerPoint(exchange='first_exchange', exchange_type='direct', queue='first_queue',
                                     routing_key='first')
    app.register(task=test_func_one(), broker_point=broker_point_first, worker_class=ThreadWorker, max_workers=5)
    # Start application
    app.start()
    # Run tasks
    time.sleep(1)
    for i in range(100000):
        test_func_one().apply_async(sleep_time=1, word="bobo")

```

**Comment by lukebakken** [comment]
Thanks for that information. You need to be certain that when methods are called on instances of objects defined in [`rabbit.py`](https://github.com/moelius/gromozeka/blob/master/gromozeka/brokers/rabbit.py) that the call is being made on the same thread as the `ioloop` is running.

For instance, I suspect that the code running a task is probably executed in a different thread than the one running the Pika ioloop, which means that [this call](https://github.com/moelius/gromozeka/blob/master/gromozeka/brokers/rabbit.py#L110) to ack the message isn't happening on the correct thread.

I don't have time to debug this for you but I suspect that is what is going on.

To resolve it, use the [`add_callback_threadsafe`](https://github.com/pika/pika/blob/0.12.0/pika/adapters/select_connection.py#L374-L402) method to schedule the `basic_ack` call.

**Comment by moelius** [comment]
I'll try to thank you, but here is one instance of the rabbit in one thread for the rabbit queue, and it communicates with other threads using a python queue. Strange thing why 0.10 works fine.

**Comment by moelius** [comment]
@lukebakken That helped. But it's strange. Thank you.

**Comment by lukebakken** [comment]
There were changes to how the `ioloop` works between 0.10 and 0.12 that probably caused this issue. Let me know if you have any other Pika issues, or questions. Thanks!

**Comment by Nizebulous** [comment]
I'm running into this problem using [dramatiq](https://github.com/Bogdanp/dramatiq). And I just want to raise it here in case the problem is here and not how they are invoking things. Here is the stacktrace:

```
FileNotFoundError: [Errno 2] No such file or directory
  File "flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "appoptics_apm/middleware.py", line 142, in __call__
    result = self.wrapped_app(environ, wrapped_start_response)
  File "werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "raven/middleware.py", line 100, in __call__
    iterable = self.application(environ, start_response)
  File "flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 35, in reraise
    raise value
  File "flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 35, in reraise
    raise value
  File "flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "sylo/permissions/access.py", line 96, in wrapped
    return f(*args, **kwargs)
  File "webargs/core.py", line 447, in wrapper
    return func(*new_args, **kwargs)
  File "<my-file>", line 47, in wrapper
    result = func(*args, **kwargs)
  File "<my-file>", line 486, in func
    <my_actor>.send(one_id, two_id)
  File "dramatiq/actor.py", line 179, in send
    return self.send_with_options(args=args, kwargs=kwargs)
  File "dramatiq/actor.py", line 198, in send_with_options
    return self.broker.enqueue(message, delay=delay)
  File "dramatiq/brokers/rabbitmq.py", line 250, in enqueue
    properties=properties,
  File "pika/adapters/blocking_connection.py", line 2206, in publish
    immediate=immediate)
  File "pika/channel.py", line 425, in basic_publish
    (properties, body))
  File "pika/channel.py", line 1328, in _send_method
    self.connection._send_method(self.channel_number, method, content)
  File "pika/connection.py", line 2341, in _send_method
    self._send_message(channel_number, method, content)
  File "pika/connection.py", line 2355, in _send_message
    self._send_frame(frame.Method(channel_number, method_frame))
  File "pika/connection.py", line 2327, in _send_frame
    self._flush_outbound()
  File "pika/adapters/base_connection.py", line 330, in _flush_outbound
    self._manage_event_state()
  File "pika/adapters/base_connection.py", line 536, in _manage_event_state
    self.event_state)
  File "pika/adapters/select_connection.py", line 446, in update_handler
    self._poller.update_handler(fileno, events)
  File "pika/adapters/select_connection.py", line 639, in update_handler
    events_to_set=events_set)
  File "pika/adapters/select_connection.py", line 1152, in _modify_fd_events
    self._poll.modify(fileno, events)
```
