### ISSUE TITLE
IndexError: pop from an empty deque

### ISSUE THREAD

**Issue by yutiansut** [pika/pika#1144]
here is the bug report

```
QUANTAXIS>> _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque',); sock=<socket.socket fd=2044, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 3520, 0, 0), raddr=('::1', 5672, 0, 0)>; Caller's stack:
Traceback (most recent call last):
  File "e:\pika\pika\adapters\utils\io_services_utils.py", line 1092, in _on_socket_writable
    self._produce()
  File "e:\pika\pika\adapters\utils\io_services_utils.py", line 817, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "e:\pika\pika\adapters\utils\io_services_utils.py", line 1092, in _on_socket_writable
    self._produce()
  File "e:\pika\pika\adapters\utils\io_services_utils.py", line 817, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
QUANTAXIS>> _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque',); <socket.socket fd=2044, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 3520, 0, 0), raddr=('::1', 5672, 0, 0)>
QUANTAXIS>> Deactivating transport: state=1; <socket.socket fd=2044, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 3520, 0, 0), raddr=('::1', 5672, 0, 0)>
QUANTAXIS>> connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque',)",)
QUANTAXIS>> AMQP stack terminated, failed to connect, or aborted: error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque',)",); pending-error=None
QUANTAXIS>> Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque',)",)
QUANTAXIS>> Closing transport socket and unlinking: state=2; <socket.socket fd=2044, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 3520, 0, 0), raddr=('::1', 5672, 0, 0)>
QUANTAXIS>> Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque',)",)
Stream connection lost: IndexError('pop from an empty deque',)
QUANTAXIS>> BlockingConnection.close(200, 'Normal shutdown') called on closed connection.
QUANTAXIS>> [QUANTAXIS REALTIME] connecting to ('::1', 5672, 0, 0)


```

**Comment by lukebakken** [comment]
Hello and thanks for using Pika. There isn't enough information for this to be useful.

* What version of Pika are you using?
* What Python version and on what OS?
* What AMQP broker are you using, and what version? If RabbitMQ, what Erlang version?
* Can you please provide steps to reproduce this?

**Comment by yutiansut** [comment]
- pika version : 1.0.0b1
- python 3.6.7X64  OS: win10
- RABBITMQ : 3.7.8

using 'fanout' exchangetype, and the error occur in subscriber( using Blocked Connection)

**Comment by lukebakken** [comment]
Closing due to inactivity.

**Comment by yutiansut** [comment]
sorry for that, to much mesage..

i just use try/except to catch this

**Comment by Rmkek** [comment]
Hello! Ran into this issue as well.

- Pika 1.0.0b1
- Python 3.7.1, Linux 4.19.13-1-MANJARO, x64
- RabbitMQ, Erlang 21.2

The error was because of function call using asyncio where function was not annotated with `@asyncio.coroutine`.

**Comment by lukebakken** [comment]
Thank you for the information!

**Comment by wujsy** [comment]
@yutiansut @lukebakken Hi, how to resolve this problem?please show the details

**Comment by lukebakken** [comment]
@wujsy - we could not reproduce this reliably. If you have code that demonstrates this issue, please share it.

**Comment by wujsy** [comment]
@lukebakken I found the reason, because I created the connection repeatly, sorry for that.

**Comment by splusz** [comment]
@yutiansut @lukebakken Is this issue solved? In my case, the exception occured when the pika connection was shared across threads, which should have be avoided.

**Comment by lukebakken** [comment]
@splusz I could never reproduce it.

**Comment by bulka3** [comment]
> @splusz I could never reproduce it.
Hey. I know how to reproduce it ..but by my way.

`
def kidok():
    while True:
        channel.queue_declare(queue='TG.send.msg.rq')
        data = sql.get_users_list()
        print(data)
        time.sleep(30)

thread1 = threading.Thread(target=kidok)
thread1.start()
q1 = channel.queue_declare(queue='VK.add.new.user.rq')
`

and I **solved it** when I created a new channel and connection:
`def kidok():
    connection2 = pika.BlockingConnection(parameters)
    channel2 = connection2.channel()
    while True:
        channel2.queue_declare(queue='TG.send.msg.rq')
        data = sql.get_users_list()
        print(data)
        time.sleep(30)

thread1 = threading.Thread(target=kidok)
thread1.start()

q1 = channel.queue_declare(queue='VK.add.new.user.rq')
`

hope it helps.

**Comment by Layder** [comment]
> > @splusz I could never reproduce it.
> > Hey. I know how to reproduce it ..but by my way.
> 
> ```
> def kidok():
>     while True:
>         channel.queue_declare(queue='TG.send.msg.rq')
>         data = sql.get_users_list()
>         print(data)
>         time.sleep(30)
> 
> thread1 = threading.Thread(target=kidok)
> thread1.start()
> q1 = channel.queue_declare(queue='VK.add.new.user.rq')
> ```
> 
> and I **solved it** when I created a new channel and connection:
> 
> ```
> def kidok():
>     connection2 = pika.BlockingConnection(parameters)
>     channel2 = connection2.channel()
>     while True:
>         channel2.queue_declare(queue='TG.send.msg.rq')
>         data = sql.get_users_list()
>         print(data)
>         time.sleep(30)
> 
> thread1 = threading.Thread(target=kidok)
> thread1.start()
> 
> q1 = channel.queue_declare(queue='VK.add.new.user.rq')
> ```
> 
> hope it helps.

thanks!

**Comment by flavienbwk** [comment]
I solved my problem following [this pika example](https://github.com/pika/pika/blob/0.12.0/examples/basic_consumer_threaded.py), specifically using `connection.add_callback_threadsafe(cb)`.

**Comment by santoshbalaji** [comment]
> > @splusz I could never reproduce it.
> > Hey. I know how to reproduce it ..but by my way.
> 
> ```
> def kidok():
>     while True:
>         channel.queue_declare(queue='TG.send.msg.rq')
>         data = sql.get_users_list()
>         print(data)
>         time.sleep(30)
> 
> thread1 = threading.Thread(target=kidok)
> thread1.start()
> q1 = channel.queue_declare(queue='VK.add.new.user.rq')
> ```
> 
> and I **solved it** when I created a new channel and connection:
> 
> ```
> def kidok():
>     connection2 = pika.BlockingConnection(parameters)
>     channel2 = connection2.channel()
>     while True:
>         channel2.queue_declare(queue='TG.send.msg.rq')
>         data = sql.get_users_list()
>         print(data)
>         time.sleep(30)
> 
> thread1 = threading.Thread(target=kidok)
> thread1.start()
> 
> q1 = channel.queue_declare(queue='VK.add.new.user.rq')
> ```
> 
> hope it helps.

Hi I am also getting the same using with multiple channel across multiple threads shared on same connection. I can see the single connection per thread works. But it is expensive to create one connection per thread right ? Is there any workaround to support multiple channels across multiple threads on single connection 

```
import pika
import threading
import time


def test_thread(a, channel):
        try:
        	 channel.exchange_declare(exchange='normal_ex', exchange_type='topic')
                channel.basic_publish(exchange='normal_ex', routing_key='test', body=str(a))
        except Exception as e:
                print("thread exception")
                print(e)



try:
        connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
        for i in range(0, 10):
                t = threading.Thread(target=test_thread, args=[i, connection.channel()])
                t.start()
        time.sleep(4)
        connection.close()
except Exception as e:
        print("main exception")
        print(e)

```

**Comment by lukebakken** [comment]
>  But it is expensive to create one connection per thread right

No, not if your thread is long-running.

> Is there any workaround to support multiple channels across multiple threads on single connection

No

**Comment by santoshbalaji** [comment]
For my scenario i may need to use it with web server. So for every request I will be publishing via rabbitmq. The thread life span is less since based on number of requests threads are going to be created and destroyed. So for this I may have to create new connection on each thread. Only way I can think of is getting all requests and store it in memory and later run a scheduled job to publish them one by one to create a single threaded environment.

**Comment by lukebakken** [comment]
Almost every web environment supports long-running threads.

Depending on your expected request rate creating a new connection per request could be adequate. Only benchmarks can prove this.

**Comment by santoshbalaji** [comment]
Thanks for the reply

**Comment by SomeAkk** [comment]
I aimed to pause consuming from mq during (another) problems in app, and for that write code which would pause consuming until (another) problems in app would not be solved. For that I try to not simple "pause" but "stop consume and close". (Maybe is any more good solution for that?)

Anyway, I got the same problem with **pop from an empty deque**.

Prerequisites:
- start 1 connection per 1 (main) thread
- pika 1.1.0
- python 3.7.9

Error got in such case:
1. create connection
2. start consuming
3. no any data receive while consuming
4. one heartbeat for connection is send
4. do channel.stop_consuming()
5. do connection.close()
6. get error (look at debug)

Debug log of pika:

> Cancelling 1 consumers
> Cancelling consumer: ctag1.f4f598b2685c44e3999deab7ef388336 (nowait=False)
> Added: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x109ebf8c0>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 1}
> SelectorIOServicesAdapter.set_writer(12, <bound method _AsyncPlaintextTransport._on_socket_writable of <pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0>>)
> set_writer(12, _) updated handler RdWr
> Turned on writability watcher: <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> Entering blocking state on frame <Basic.Cancel(['consumer_tag=ctag1.f4f598b2685c44e3999deab7ef388336', 'nowait=False'])>; acceptable_replies=[(<class 'pika.spec.Basic.CancelOk'>, {'consumer_tag': 'ctag1.f4f598b2685c44e3999deab7ef388336'})]
> Adding on_synchronous_complete callback
> Added: {'callback': <bound method Channel._on_synchronous_complete of <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>, 'one_shot': True, 'only': None, 'arguments': {'consumer_tag': 'ctag1.f4f598b2685c44e3999deab7ef388336'}, 'calls': 1}
> Adding passed-in RPC response callback
> Added: {'callback': <bound method Channel._on_cancelok of <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>, 'one_shot': True, 'only': None, 'arguments': {'consumer_tag': 'ctag1.f4f598b2685c44e3999deab7ef388336'}, 'calls': 1}
> SelectorIOServicesAdapter.remove_writer(12)
> remove_writer(12) updated handler Rd
> Turned off writability watcher: <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> Wrapped func exited with exception. Caller's stack:
> Traceback (most recent call last):
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
>     return func(*args, **kwargs)
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1093, in _on_socket_writable
>     'but _tx_buffers is empty.', self._state)
> AssertionError: ('_AsyncPlaintextTransport._on_socket_writable() called, but _tx_buffers is empty.', 1)
> Traceback (most recent call last):
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
>     return func(*args, **kwargs)
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1093, in _on_socket_writable
>     'but _tx_buffers is empty.', self._state)
> AssertionError: ('_AsyncPlaintextTransport._on_socket_writable() called, but _tx_buffers is empty.', 1)
> Traceback (most recent call last):
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/click/core.py", line 782, in main
> Processing 1:Basic.CancelOk
> Processing use of oneshot callback
> 0 registered uses left
> Removing callback #0: {'callback': <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x109ebf8c0>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 0}
> Processing use of oneshot callback
> 0 registered uses left
> Comparing {'consumer_tag': 'ctag1.f4f598b2685c44e3999deab7ef388336'} to {'consumer_tag': 'ctag1.f4f598b2685c44e3999deab7ef388336'}
> Removing callback #0: {'callback': <bound method Channel._on_synchronous_complete of <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>, 'one_shot': True, 'only': None, 'arguments': {'consumer_tag': 'ctag1.f4f598b2685c44e3999deab7ef388336'}, 'calls': 0}
> Processing use of oneshot callback
> 0 registered uses left
> Comparing {'consumer_tag': 'ctag1.f4f598b2685c44e3999deab7ef388336'} to {'consumer_tag': 'ctag1.f4f598b2685c44e3999deab7ef388336'}
> Removing callback #0: {'callback': <bound method Channel._on_cancelok of <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>, 'one_shot': True, 'only': None, 'arguments': {'consumer_tag': 'ctag1.f4f598b2685c44e3999deab7ef388336'}, 'calls': 0}
> Calling <bound method _CallbackResult.signal_once of <pika.adapters.blocking_connection._CallbackResult object at 0x109ebf8c0>> for "1:Basic.CancelOk"
> Calling <bound method Channel._on_synchronous_complete of <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>> for "1:Basic.CancelOk"
> 0 blocked frames
> Calling <bound method Channel._on_cancelok of <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>> for "1:Basic.CancelOk"
> Recv would block on <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> Closing connection (200): Normal shutdown
> Channel.close(200, Normal shutdown)
> Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
> SelectorIOServicesAdapter.set_writer(12, <bound method _AsyncPlaintextTransport._on_socket_writable of <pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0>>)
> set_writer(12, _) updated handler RdWr
> Turned on writability watcher: <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> Entering blocking state on frame <Channel.Close(['class_id=0', 'method_id=0', 'reply_code=200', 'reply_text=Normal shutdown'])>; acceptable_replies=[<class 'pika.spec.Channel.CloseOk'>]
> Adding on_synchronous_complete callback
> Added: {'callback': <bound method Channel._on_synchronous_complete of <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 1}
> Adding passed-in RPC response callback
> Added: {'callback': <bound method Channel._on_closeok of <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 1}
>     rv = self.invoke(ctx)
> SelectorIOServicesAdapter.remove_writer(12)
> remove_writer(12) updated handler Rd
> Turned off writability watcher: <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/gudsaf/PycharmProjects/alerter20/app.py", line 21, in main
>     appw.run()
>   File "/Users/gudsaf/PycharmProjects/alerter20/alerter/worker/alerter_daemon.py", line 57, in run
>     self.mq_consumer.consume()
>   File "/Users/gudsaf/PycharmProjects/alerter20/alerter/mq/reconnect_consumer.py", line 62, in consume
>     self.app_broker.start_consuming()
>   File "/Users/gudsaf/PycharmProjects/alerter20/alerter/mq/client.py", line 49, in start_consuming
>     self.channel.start_consuming()
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
> Processing 1:Channel.CloseOk
> Processing use of oneshot callback
> 0 registered uses left
> Removing callback #0: {'callback': <bound method Channel._on_synchronous_complete of <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 0}
> Processing use of oneshot callback
> 0 registered uses left
> Removing callback #0: {'callback': <bound method Channel._on_closeok of <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 0}
> Calling <bound method Channel._on_synchronous_complete of <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>> for "1:Channel.CloseOk"
> 0 blocked frames
> Calling <bound method Channel._on_closeok of <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>> for "1:Channel.CloseOk"
> Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
> Processing 1:_on_channel_close
> Calling <bound method BlockingChannel._on_channel_closed of <BlockingChannel impl=<Channel number=1 CLOSED conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>> for "1:_on_channel_close"
> _on_channel_closed: ChannelClosedByClient: (200) 'Normal shutdown'; <BlockingChannel impl=<Channel number=1 CLOSED conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>>
> Processing 1:_on_channel_cleanup
> Processing use of oneshot callback
> 0 registered uses left
> Removing callback #0: {'callback': <bound method Connection._on_channel_cleanup of <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'one_shot': True, 'only': <Channel number=1 CLOSED conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'arguments': None, 'calls': 0}
> Calling <bound method Connection._on_channel_cleanup of <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>> for "1:_on_channel_cleanup"
> Removed channel 1
> Clearing out '1' from the stack
> Recv would block on <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> New Connection state: CLOSING (prev=OPEN)
> Closing connection (200): 'Normal shutdown'
> Added: {'callback': <bound method Connection._on_connection_close_ok of <SelectConnection CLOSING transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 1}
> SelectorIOServicesAdapter.set_writer(12, <bound method _AsyncPlaintextTransport._on_socket_writable of <pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0>>)
> set_writer(12, _) updated handler RdWr
> Turned on writability watcher: <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> SelectorIOServicesAdapter.remove_writer(12)
> remove_writer(12) updated handler Rd
> Turned off writability watcher: <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> Processing 0:Connection.CloseOk
> Processing use of oneshot callback
> 0 registered uses left
> Removing callback #0: {'callback': <bound method Connection._on_connection_close_ok of <SelectConnection CLOSING transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 0}
> Calling <bound method Connection._on_connection_close_ok of <SelectConnection CLOSING transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>> for "0:Connection.CloseOk"
> _on_connection_close_ok: frame=<METHOD(['channel_number=0', 'frame_type=1', 'method=<Connection.CloseOk>'])>
> Removing timer for next heartbeat send interval
> remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x109d68d90> with deadline=63.050333558 and callback=<bound method HeartbeatChecker._send_heartbeat of <pika.heartbeat.HeartbeatChecker object at 0x109d4ef90>>
> Removing timer for next heartbeat check interval
> remove_timeout: removing timeout <pika.adapters.select_connection._Timeout object at 0x109d4e5d0> with deadline=68.044433549 and callback=<bound method HeartbeatChecker._check_heartbeat of <pika.heartbeat.HeartbeatChecker object at 0x109d4ef90>>
> Aborting transport connection: state=1; <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> Deactivating transport: state=1; <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> SelectorIOServicesAdapter.remove_reader(12)
> remove_reader(12) removed handler
> SelectorIOServicesAdapter.remove_writer(12)
> remove_writer(12) neither was set.
>     add_callback_threadsafe: added callback=functools.partial(<bound method _AsyncTransportBase._connection_lost_notify_async of <pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0>>, None)
> Leaving Plaintext consumer due to inactive state: state=3; <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> process_timeouts: invoking callback=functools.partial(<bound method _AsyncTransportBase._connection_lost_notify_async of <pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x109d483d0>>, None)
> Concluding transport shutdown: state=3; error=None
> connection_lost: None
> AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
> New Connection state: CLOSED (prev=CLOSING)
> Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
> Processing 0:_on_connection_closed
> Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x109d70910>> for "0:_on_connection_closed"
> New Connection state: CLOSED (prev=CLOSED)
> Added: {'callback': <bound method Connection._on_connection_start of <SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 1}
> Incremented callback reference counter: {'callback': <bound method Connection._on_connection_close_from_broker of <SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>, 'one_shot': True, 'only': None, 'arguments': None, 'calls': 2}
> self._process_data_events(time_limit=None)
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
> Closing transport socket and unlinking: state=3; <socket.socket fd=12, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 55067, 0, 0), raddr=('::1', 5672, 0, 0)>
> User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
>     self.connection.process_data_events(time_limit=time_limit)
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
>     self._flush_output(common_terminator)
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 513, in _flush_output
>     self._impl.ioloop.poll()
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 576, in poll
>     self._poller.poll()
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1073, in poll
>     self._dispatch_fd_events(fd_event_map)
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 904, in _dispatch_fd_events
>     handler(fileno, events)
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 391, in _on_reader_writer_fd_events
>     callbacks.writer()
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
>     return func(*args, **kwargs)
>   File "/Users/gudsaf/.local/share/virtualenvs/alerter20-kLBd_3G6/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1093, in _on_socket_writable
>     'but _tx_buffers is empty.', self._state)
> AssertionError: ('_AsyncPlaintextTransport._on_socket_writable() called, but _tx_buffers is empty.', 1)
>
