### ISSUE TITLE
InvalidChannelNumber exception in channels wrongly raised.

### ISSUE THREAD

**Issue by sid22** [pika/pika#1221]
My system:
Ubuntu 18.04
Python 2.7
Pika Version: 1.0.1
RabbitMQ 3.7.15
Erlang 22.0.2

I had tried to connect to RabbitMQ using a SelectConnection.

```
credentials = pika.PlainCredentials('user', 'pwd')
parameters = pika.ConnectionParameters('host', port, '/', credentials=credentials, heartbeat=400)

try:
    connection = pika.SelectConnection(parameters, on_connected)
    connection.ioloop.start()
except KeyboardInterrupt:
    connection.close()
    connection.ioloop.start()
except Exception as e:
    import traceback
    traceback.print_exc()
    print(e)

```
This game me
```

Traceback (most recent call last):
  File "prod_connect.py", line 41, in <module>
    connection.ioloop.start()
  File "/home/in052/Desktop/LogService/venv/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 543, in start
    self._poller.start()
  File "/home/in052/Desktop/LogService/venv/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 804, in start
    self._process_timeouts()
  File "/home/in052/Desktop/LogService/venv/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 492, in process_timeouts
    callback()
  File "/home/in052/Desktop/LogService/venv/local/lib/python2.7/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home/in052/Desktop/LogService/venv/local/lib/python2.7/site-packages/pika/adapters/utils/io_services_utils.py", line 972, in _connection_lost_notify_async
    self._protocol.connection_lost(error)
  File "/home/in052/Desktop/LogService/venv/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 426, in _proto_connection_lost
    'Stream connection lost: {!r}'.format(error))
  File "/home/in052/Desktop/LogService/venv/local/lib/python2.7/site-packages/pika/exceptions.py", line 271, in __repr__
    self.__class__.__name__, self.args[0])
IndexError: tuple index out of range
tuple index out of range
```

Looking in the exceptions.py file in the package
Line 271, is in exception class InvalidChannelNumber which takes AMQPError class.
So, I tried calling the exception manually:
```
from pika.exceptions import *
b = AMQPError()
import sys
try:
     raise InvalidChannelNumber(b)
except Exception as e:
     print(e)
     print(sys.exc_info())
(<class 'pika.exceptions.InvalidChannelNumber'>, InvalidChannelNumber: An invalid channel number has been specified: , <traceback object at 0x7f42d506ea28>)
```
This works, so checking in the package I found that InvalidChannelNumber is being called only once in channel.py line 60.
But here the exception class is called as is without passing any AMQPError class object.

I think this is a bug in the way exception is being raised.

**Comment by lukebakken** [comment]
Hello, this will be fixed by #1216

**Comment by lfmunoz** [comment]
Code on the website doesn't work because of this issue:
https://pika.readthedocs.io/en/1.0.1/intro.html#io-and-event-looping

What's the actual fix to get the website example working?

**Comment by lukebakken** [comment]
@lfmunoz - this has been fixed and will be in the next release, please see these docs -

https://pika.readthedocs.io/en/latest/intro.html
