### ISSUE TITLE
Raise a exception when connection rabbit server IncompatibleProtocolError 104 

### ISSUE THREAD

**Issue by LeoDemoniac** [pika/pika#1306]
### The base information:
- python version 2.7/3.6.5
+ pika version: 1.1
* rabbit-server 3.7.16 and 3.8.9

### The code for test is 
```python
import pika
import logging

logging.basicConfig(level=logging.DEBUG)
credentials = pika.PlainCredentials("guest, 'guest')
conn_params = pika.ConnectionParameters("192.168.56.3",credentials=credentials)
con_broker = pika.BlockingConnection(conn_params)
channel = con_broker.channel()
print "connect succeed" # for python3 print("connect succeed")
```
Nothing error occurred by rabbit-server(3.7.1). And we used it for rabbit(3.8.9).
It raised thoes exceptions:
```bash
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
IncompatibleProtocolError: StreamLostError: ("Stream connection lost: error(104, 'Connection reset by peer')",)
Traceback (most recent call last):
  File "mq.py", line 7, in <module>
    con_broker = pika.BlockingConnection(conn_params)
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ("Stream connection lost: error(104, 'Connection reset by peer')",)
```
> This exceptions are some between py2 and py3.

Then we captured the TCP packet by `tcpdump`, we found the server `RST` the connection after handshaked。
This is the brief data we analysis of `tcp.cap`。
```bash
py        ->  rabbit  SYN
rabbit  ->  py        SYN ACK
py        ->  rabbit  ACK
py        ->  rabbit  AMQP(unknown version)
rabbit  ->  py        ACK
rabbit  ->  py        RST ACK
```
What can I do for fixing this in my code, or there is some other solutions?

**Comment by LeoDemoniac** [comment]
So sorry, I got a message from our group member, it has a security rule on this VM。This only allow the packet from the security  machine.They rejuect all other packets。
