### ISSUE TITLE
1.2.0 version is breaking for python2.7

### ISSUE THREAD

**Issue by linesight** [pika/pika#1311]
```
>>> import pika
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "z:\test_venv27\venv\lib\site-packages\pika\__init__.py", line 10, in <module>
    from pika.connection import ConnectionParameters
  File "z:\test_venv27\venv\lib\site-packages\pika\connection.py", line 15, in <module>
    import pika.callback
  File "z:\test_venv27\venv\lib\site-packages\pika\callback.py", line 8, in <module>
    from pika import frame
  File "z:\test_venv27\venv\lib\site-packages\pika\frame.py", line 7, in <module>
    from pika import spec
  File "z:\test_venv27\venv\lib\site-packages\pika\spec.py", line 18, in <module>
    from pika.exchange_type import ExchangeType
  File "z:\test_venv27\venv\lib\site-packages\pika\exchange_type.py", line 1, in <module>
    from enum import Enum
ImportError: No module named enum
```

looks like the commit https://github.com/pika/pika/commit/d79ce1c1d576f1d39c72ef7f8aaeb48c3802302a is breaking python2.7 compatibility

**Comment by michaelklishin** [comment]
Python 2.7 has reached EOL [over one year ago](https://www.python.org/doc/sunset-python-2/#:~:text=As%20of%20January%201st%2C%202020,when%20we%20released%20Python%202.7.). Those who have to use it can use Pika 1.1. It supports the same range of RabbitMQ versions and very much the same feature set.

I have updated the README to not list Python 2.7 as supported by Pika 1.2.

**Comment by dabbler0606** [comment]
I use Python 2.7 and can't upgrade to py3 for a short time. But I want to use GeventConnection. However, 1.2.0 does not support py2.7. Looking at the code, it seems that only Enum is used. Can I replace Enum with Enum3.4 to use 1.2.0 in py2.7?

**Comment by michaelklishin** [comment]
At this point 2.7 users might as well fork Pika and swap `Enum` for whatever they need. The mainline does not list 2.7 as supported. Hasn't for over a year.
