### ISSUE TITLE
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately

### ISSUE THREAD

**Issue by MykhailoKhil** [pika/pika#1314]
Hello there!
I also faced with this problem when I wanted to do performance testing with Locust and Pika.
On my macOS it working perfect but on Win10 1909 i have a error!
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately
My code you could find on  https://pastebin.com/ir0ACqKG I only publish a message in RabbitMQ  3.8.2 Erlang 22.2.2
Python version Python 3.9.2
pip list
Package                  Version
------------------------ ---------
cachetools               4.2.1
certifi                  2020.12.5
cffi                     1.14.5
chardet                  4.0.0
click                    7.1.2
ConfigArgParse           1.3
Faker                    6.4.1
Flask                    1.1.2
Flask-BasicAuth          0.2.0
gevent                   21.1.2
geventhttpclient         1.4.5
google-api-core          1.26.0
google-auth              1.27.0
googleapis-common-protos 1.52.0
greenlet                 1.0.0
idna                     2.10
influxdb                 5.3.1
itsdangerous             1.1.0
Jinja2                   2.11.3
locust                   1.4.3
locust-influxdb-listener 0.0.3
lxml                     4.6.2
MarkupSafe               1.1.1
msgpack                  1.0.2
opencensus               0.7.12
opencensus-context       0.1.2
opencensus-ext-azure     1.0.7
packaging                20.9
pika                     1.2.0
pip                      21.0.1
protobuf                 3.15.1
psutil                   5.8.0
psycogreen               1.0.2
psycopg2-binary          2.8.6
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.20
pymongo                  3.11.3
pyparsing                2.4.7
python-dateutil          2.8.1
pytz                     2021.1
pywin32                  300
pyzmq                    22.0.3
requests                 2.25.1
rsa                      4.7.1
selenium                 3.141.0
setuptools               53.0.0
six                      1.15.0
text-unidecode           1.3
urllib3                  1.26.3
websocket-client         0.57.0
Werkzeug                 1.0.1

**Comment by lukebakken** [comment]
Sorry, I was unsubscribed from this repository and have missed new issues from the past year. I will investigate this before the next release, thank you!

**Comment by lukebakken** [comment]
I have added your code here - https://github.com/lukebakken/pika-1314

However, there are two problems:
* There is no code for the `utils` package.
* I have no idea how to run the locust test the same way you did.

@MykhailoKhil I will keep this issue open until I release version 1.3.0. If you have the time, I would like to investigate this, and I even have a Windows environment to do so. Thanks.

**Comment by aeg12345** [comment]
greetings, I run into a similar issue when using pika with locust are there any resolutions to implement?

**Comment by danielgran** [comment]
same here, seems to be a bug. I dont really have an idea on how i'd reproduce this.
Here is my call which fails.
```python
def _publishing_thread_target(self):
    """
    This method runs on a separate thread for publishing messages
    """
    try:

      self._publishing_connection = self.get_threadsafe_connection()

      while self.running:
        # time limit is set to 1 second to allow for graceful shutdown
        self._publishing_connection.process_data_events(time_limit=1)

    except Exception as e:
      print(traceback.format_exc())
      print(f"Error in publishing thread: {e}")
      self.running = False
      raise e
```


With my stacktrace
```
Traceback (most recent call last):
  File "D:\Projects\*-*\.venv\Lib\site-packages\*\Network\Message\RabbitMQMessageExchange.py", line 194, in _publishing_thread_target
    self._publishing_connection.process_data_events(time_limit=1)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "D:\Projects\***-***\.venv\Lib\site-packages\pika\adapters\blocking_connection.py", line 845, in process_data_events
    self._flush_output(timer.is_ready, common_terminator)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\***-***\.venv\Lib\site-packages\pika\adapters\blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Projects\***-***\.venv\Lib\site-packages\pika\adapters\select_connection.py", line 579, in poll
    self._poller.poll()
    ~~~~~~~~~~~~~~~~~^^
  File "D:\Projects\***-***\.venv\Lib\site-packages\pika\adapters\select_connection.py", line 978, in poll
    self._dispatch_fd_events(fd_event_map)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "D:\Projects\***-***\.venv\Lib\site-packages\pika\adapters\select_connection.py", line 907, in _dispatch_fd_events
    handler(fileno, events)
    ~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\Projects\***-***\.venv\Lib\site-packages\pika\adapters\select_connection.py", line 927, in _read_interrupt
    self._r_interrupt.recv(512)  # pylint: disable=E1101
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^
BlockingIOError: [WinError 10035] Ein nicht blockierender Socketvorgang konnte nicht sofort ausgeführt werden
```

Where this is the pika code which seems to bug on windows

```python
    def _read_interrupt(self, _interrupt_fd, _events):
        """ Read the interrupt byte(s). We ignore the event mask as we can ony
        get here if there's data to be read on our fd.

        :param int _interrupt_fd: (unused) The file descriptor to read from
        :param int _events: (unused) The events generated for this fd
        """
        try:
            # NOTE Use recv instead of os.read for windows compatibility
            self._r_interrupt.recv(512)  # pylint: disable=E1101
        except pika.compat.SOCKET_ERROR as err:
            if err.errno != errno.EAGAIN:
                raise
```

Currently on version `1.3.2`

**Comment by danielgran** [comment]
Opus'ed Root cause analysis, this may really help

Root Cause Analysis
This is a Windows-specific bug in the pika library (RabbitMQ Python client). Here's what's happening:

The Problem
Platform Difference: The error [WinError 10035] is WSAEWOULDBLOCK - Windows' way of saying "this non-blocking socket operation can't complete right now because there's no data available"

Pika's Internal Mechanism: Pika uses an internal interrupt socket for thread-safe operations (like [add_callback_threadsafe](vscode-file://vscode-app/c:/Users/*/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)). This socket is non-blocking.

Exception Handling Gap: In [select_connection.py](vscode-file://vscode-app/c:/Users/*/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) line 927, pika catches [SOCKET_ERROR](vscode-file://vscode-app/c:/Users/*/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) and checks if [err.errno != errno.EAGAIN](vscode-file://vscode-app/c:/Users/*/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html). However:

On Unix: [EAGAIN](vscode-file://vscode-app/c:/Users/*/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) (error 11) is raised when no data is available
On Windows: BlockingIOError with errno 10035 (WSAEWOULDBLOCK) is raised instead
Pika's exception handler doesn't catch BlockingIOError properly on Windows

**Comment by danielgran** [comment]
Ah, sorry for spamming. Another update on the cause on this.
The same line errors when the underliying stream was lost, at least the error is indicating this.
Pretty sure that im in a state with pika which is not intended. Haha. Threading. haha...

```
  File "D:\Projects\***-***\.venv\Lib\site-packages\***\Network\Message\RabbitMQMessageExchange.py", line 195, in _publishing_thread_target
    self._publishing_connection.process_data_events(time_limit=1)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "D:\Projects\***-***\.venv\Lib\site-packages\pika\adapters\blocking_connection.py", line 845, in process_data_events
    self._flush_output(timer.is_ready, common_terminator)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\***-***\.venv\Lib\site-packages\pika\adapters\blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
  File "D:\Projects\***-***\.venv\Lib\site-packages\pika\adapters\blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.StreamLostError: Stream connection lost: IndexError('pop from an empty deque')
```

**Comment by danielgran** [comment]
Did some more research on this. Pika retrieves a **non-blocking** socket pair:
https://github.com/pika/pika/blob/10ec0abd23dbd55766a684d7a129451f276adc1e/pika/compat.py#L114

@lukebakken - May i ask you now how to mitigate this error? :-)

**Comment by lukebakken** [comment]
Hello! I'm still waiting for a user to provide code to reproduce this issue. Obviously, this issue is very rare, even on Windows, or I would be getting reports all of the time.

@danielgran - I need information from you:
* RabbitMQ & Erlang version
* Python version
* Pika version
* Windows version on which your Pika application runs

@danielgran if you see this issue regularly, _YOU_ could patch your local Pika installation to follow the genie's suggestion. If it's easier for you to install Pika from pypi for you, I could probably get an alpha version out with the following suggested change:

```
Exception Handling Gap: In select_connection.py line 927, pika catches SOCKET_ERROR and checks if err.errno != errno.EAGAIN. However:

On Unix: EAGAIN (error 11) is raised when no data is available
On Windows: BlockingIOError with errno 10035 (WSAEWOULDBLOCK) is raised instead
```
