### ISSUE TITLE
Pika fails to quit when you press Ctrl-C

### ISSUE THREAD

**Issue by JaapJoris** [pika/pika#1327]
Hi there,

Using Pika 1.2.0, the example code from https://pika.readthedocs.io/en/1.2.0/intro.html fails to quit when you press Ctrl-C.

## Steps to reproduce

First, copy-paste the example code into a file called `test.py`:

```
import pika

def on_open(connection):
    # Invoked when the connection is open
    pass

# Create our connection object, passing in the on_open method
connection = pika.SelectConnection(on_open_callback=on_open)

try:
    # Loop so we can communicate with RabbitMQ
    connection.ioloop.start()
except KeyboardInterrupt:
    # Gracefully close the connection
    connection.close()
    # Loop until we're fully closed, will stop on its own
    connection.ioloop.start()
```

Then, run the following command and press Ctrl-C. Nothing happens.

```
$ python test.py 
^C
```

Finally, press Ctrl-C again. The following traceback is produced.

```
Traceback (most recent call last):
  File "/home/jj/test.py", line 12, in <module>
    connection.ioloop.start()
  File "/home/jj/.virtualenvs/pika/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 546, in start
    self._poller.start()
  File "/home/jj/.virtualenvs/pika/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 806, in start
    self.poll()
  File "/home/jj/.virtualenvs/pika/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jj/test.py", line 17, in <module>
    connection.ioloop.start()
  File "/home/jj/.virtualenvs/pika/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 546, in start
    self._poller.start()
  File "/home/jj/.virtualenvs/pika/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 806, in start
    self.poll()
  File "/home/jj/.virtualenvs/pika/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 1184, in poll
    events = self._poll.poll(self._get_max_wait())
KeyboardInterrupt
```

**Expected results**: The example program exits when you press Ctrl-C.
**Actual results**: Nothing happens.

Thank you for allowing me to report this issue!

Greetings,
Jaap Joris

**Comment by JaapJoris** [comment]
If it's any help, I used `git bisect` to identify the commit that broke the example: https://github.com/pika/pika/commit/bd2580ea9e7d24e6d5199ebf6a77003ddde9f279

It seems that since then, the IO loop doesn't stop automatically anymore when the connection closes, and has to be stopped explicitly by calling `connection.ioloop.stop()`.

The fix is either to restore the behavior described in the documentation, or to update the example to include an `on_close_callback` that calls `connection.ioloop.stop()`.

**Comment by lukebakken** [comment]
Sorry, I was unsubscribed from this repository and have missed new issues from the past few months. I'll check this out before the next release. Thank you!
