### ISSUE TITLE
ERROR - _AsyncBaseTransport._produce() failed, aborting connection: error=ConnectionResetError(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by zhongqingbin** [pika/pika#1331]
2021-09-16 17:52:11,335 - ERROR - _AsyncBaseTransport._produce() failed, aborting connection: error=ConnectionResetError(104, 'Connection reset by peer'); sock=<socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.203', 51524)>; Caller's stack:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/utils/io_services_utils.py", line 819, in _produce
    num_bytes_sent = self._sigint_safe_send(self._sock,
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/utils/io_services_utils.py", line 819, in _produce
    num_bytes_sent = self._sigint_safe_send(self._sock,
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
2021-09-16 17:52:11,336 - ERROR - connection_lost: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
2021-09-16 17:52:11,338 - ERROR - Unexpected connection close detected: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')

Environment: python3.9.6 + uwsgi + flask + pika
System: CentOS 7.6
Startup method: threading.Thread(target=self.consuming)

**Comment by lukebakken** [comment]
`Connection reset by peer` means that RabbitMQ closed the connection.

**Comment by revoorunischal** [comment]
But why does it close connection?
