### ISSUE TITLE
pika client connection closes upon rabbitmq server node shut down, does not automatically handle failure and reconnects to a available broker

### ISSUE THREAD

**Issue by kaushiksrinivas** [pika/pika#1339]
We are seeing pika client to terminate with below error upon shutdown of the broker to which pika client is connected to.
 [x] Sent 'Hello World!'
Traceback (most recent call last):
  File "send.py", line 96, in <module>
    channel.basic_publish(exchange='', routing_key=args_dict['queue'], body='Hello World!',properties=pika.BasicProperties(content_type='text/plain',delivery_mode=2))
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1978, in basic_publish
    mandatory, immediate)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2065, in publish
    self._flush_output()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed

We see below from the rabbitmq docs,
In most client libraries there is a way to react to a connection closure, for example:

Pika (Python)
Go

Does this mean, applications using pika client is supposed to prepare the callback and handle the reconnects upon connection failures and automatic reconnects are not supported in pika client ?

**Comment by lukebakken** [comment]
Right now Pika does not automatically reconnect for you. It may be added in a future release.
