### ISSUE TITLE
TypeError: close() takes from 1 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by Rajjix** [pika/pika#1358]
Hey, The error is being on BaseConnection `close` method. it only accepts 2 parameters (3 with self).
https://github.com/pika/pika/blob/0.13.1/pika/adapters/base_connection.py#L114

But it's being called with four arguments as shown here
https://github.com/pika/pika/blob/0.13.1/pika/channel.py#L1076

the process function for base_connection doesn't need to be called with `self` twice. so removing one of the selves will resolve the issue.

Something like this

```python
    def _on_close_meta(self, reply_code, reply_text):
        """Handle meta-close request from Connection's cleanup logic after
        sudden connection loss. We use this opportunity to transition to
        CLOSED state, clean up the channel, and dispatch the on-channel-closed
        callbacks.
        :param int reply_code: The reply code to pass to on-close callback
        :param str reply_text: The reply text to pass to on-close callback
        """
        LOGGER.debug('Handling meta-close on %s', self)

        if not self.is_closed:
            self._closing_code_and_text = reply_code, reply_text

            self._set_state(self.CLOSED)

            try:
                self.callbacks.process(self.channel_number, '_on_channel_close',
                                       self,
                                       reply_code,
                                       reply_text)
            finally:
                self._cleanup()

```

Thank you!

**Comment by Rajjix** [comment]
Full traceback.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/base_connection.py", line 476, in _handle_write
    num_bytes_sent = self.socket.send(frame)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
TypeError: close() takes from 1 to 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/base_connection.py", line 476, in _handle_write
    num_bytes_sent = self.socket.send(frame)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/run_rabbit.py", line 49, in <module>
    run()
  File "/app/run_rabbit.py", line 45, in run
    consumer.run()
  File "/usr/local/lib/python3.9/site-packages/ppl_messaging/consumer/rabbitmq.py", line 40, in run
    self._connection.ioloop.start()
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 461, in start
    self._poller.start()
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 721, in start
    self.poll()
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 1114, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/select_connection.py", line 831, in _dispatch_fd_events
    handler(fileno, events)
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/base_connection.py", line 406, in _handle_events
    self._handle_write()
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/base_connection.py", line 511, in _handle_write
    return self._handle_error(error)
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/base_connection.py", line 382, in _handle_error
    self._on_terminate(connection.InternalCloseReasons.SOCKET_ERROR,
  File "/usr/local/lib/python3.9/site-packages/pika/connection.py", line 2114, in _on_terminate
    self._channels[channel]._on_close_meta(reason_code, reason_text)
  File "/usr/local/lib/python3.9/site-packages/pika/channel.py", line 1076, in _on_close_meta
    self.callbacks.process(self.channel_number, '_on_channel_close',
  File "/usr/local/lib/python3.9/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
TypeError: close() takes from 1 to 3 positional arguments but 4 were given
```

**Comment by lukebakken** [comment]
Thank you for the report but Pika 0.13 has been out of support for a while now. Please upgrade.
