### ISSUE TITLE
socket.gaierror: [Errno -5] No address associated with hostname

### ISSUE THREAD

**Issue by eneesfd** [pika/pika#1397]
Thank you for using Pika.

- IMPORTANT -----------------------------------------------------------
STOP NOW AND READ THIS BEFORE OPENING A NEW ISSUE ON GITHUB
--------------------------------------------------------------------------

Unless you are CERTAIN you have found a reproducible bug in Pika, you must
first ask your question, discuss your suspected issue, or propose your new
feature on the mailing list:

https://groups.google.com/forum/#!forum/pika-python

Pika's maintainers do NOT use GitHub issues for questions, root cause analysis,
conversations, code reviews, etc.

Thank you!

**Comment by eneesfd** [comment]
Traceback (most recent call last):
  File "/app/consumer.py", line 36, in <module>
    main()
  File "/app/consumer.py", line 16, in main
    connection = pika.BlockingConnection(pika.ConnectionParameters(host="rabbitmq"))
  File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/usr/local/lib/python3.10/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
    result = socket.getaddrinfo(self._host, self._port, self._family,
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

Hello when start image i have this error. How can i solve
