### ISSUE TITLE
GeventConnection may now work on Windows

### ISSUE THREAD

**Issue by lukebakken** [pika/pika#1407]
We should check

**Comment by lukebakken** [comment]
I'd call this a big NOPE:

```
======================================================================
FAIL: test_with_gevent (acceptance.async_adapter_tests.TestZ_PublishAndGet)
Publish a message and get it (GeventConnection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\pika\pika\tests\wrappers\threaded_test_wrapper.py", line 59, in run_in_thread_with_timeout_wrapper
    return runner.kick_off()
  File "D:\a\pika\pika\tests\wrappers\threaded_test_wrapper.py", line 129, in kick_off
    raise AssertionError(self._exc_info_to_str(self._exc_info))
AssertionError: Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\gevent\libuv\loop.py", line 669, in io
    io_watcher = io_watchers[fd]
KeyError: 81

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\pika\pika\tests\wrappers\threaded_test_wrapper.py", line 145, in _thread_entry
    self._fun_result = self._fun()
  File "D:\a\pika\pika\tests\base\async_test_base.py", line 364, in test_with_gevent
    self.start(GeventConnection, ioloop_factory)
  File "D:\a\pika\pika\tests\base\async_test_base.py", line 262, in start
    super(BoundQueueTestCase, self).start(adapter, ioloop_factory)
  File "D:\a\pika\pika\tests\base\async_test_base.py", line 158, in start
    custom_ioloop=ioloop_factory())
  File "D:\a\pika\pika\tests\base\async_test_base.py", line 362, in ioloop_factory
    return _GeventSelectorIOLoop(gevent.get_hub())
  File "D:\a\pika\pika\pika\adapters\gevent_connection.py", line 198, in __init__
    self.add_handler(self._callback_queue.fd, run_callback_in_main_thread,
  File "D:\a\pika\pika\pika\adapters\gevent_connection.py", line 281, in add_handler
    io_watcher = self._hub.loop.io(fd, events)
  File "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\gevent\libuv\loop.py", line 675, in io
    io_watcher = self._watchers.io(self, fd, 0)
  File "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\gevent\libuv\watcher.py", line 252, in __init__
    super(io, self).__init__(loop, fd, events, ref=ref, priority=priority, _args=(fd,))
  File "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\gevent\_ffi\watcher.py", line 477, in __init__
    super(IoMixin, self).__init__(loop, ref=ref, priority=priority,
  File "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\gevent\_ffi\watcher.py", line 224, in __init__
    self._watcher_full_init()
  File "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\gevent\_ffi\watcher.py", line 238, in _watcher_full_init
    self._watcher_ffi_init(args)
  File "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\gevent\libuv\watcher.py", line 163, in _watcher_ffi_init
    return self._watcher_init(self.loop.ptr,
  File "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\gevent\libuv\watcher.py", line 82, in wrap
    raise UVFuncallError(
gevent.libuv.watcher.UVFuncallError: ENOTSOCK socket operation on non-socket Args: (<cdata 'struct uv_loop_s *' 0x000002955E58C3F0>, <cdata 'struct uv_poll_s *' owning 416 bytes>, 81) KWARGS: {}
```
