### ISSUE TITLE
pycharm pika connect rabbitmq error in windows10

### ISSUE THREAD

**Issue by honghh2018** [pika/pika#1434]
Hi developer,
    I am confused, if i running below code in pycharm it show me error

producer.py
    import pika

# 1 链接rabbitmq
#                       heartbeat=0   # 设置这个解决-> pika.exceptions.StreamLostError: Stream connection lost: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)
connection = pika.BlockingConnection(pika.ConnectionParameters('127.0.0.1', heartbeat=0))
channel = connection.channel()

# 2 创建队列
channel.queue_declare(queue='hello',durable=True)  # 并指定队列名称queue="name"  持久化durable=T

# 3 向指定队列插入数据
channel.basic_publish(exchange='',  # 简单模式
                      routing_key='hello',  # 指定队列,向那个队列中插入数据
                      body='Hello Yuan!'  # 写入 Hello Yuan字符串
                      )

print(" [x] Sent 'Hello Yuan!'")

error:
D:\project\virtualEnv\rabbitmq_pika\Scripts\python.exe D:\project\rabbitmq_pika\rabbitmq_pika\2_simple_model\1_producer.py 
Traceback (most recent call last):
  File "D:\project\rabbitmq_pika\rabbitmq_pika\2_simple_model\1_producer.py", line 6, in <module>
    channel = connection.channel()
  File "D:\project\virtualEnv\rabbitmq_pika\lib\site-packages\pika\adapters\blocking_connection.py", line 893, in channel
    channel._flush_output(opened_args.is_ready)
  File "D:\project\virtualEnv\rabbitmq_pika\lib\site-packages\pika\adapters\blocking_connection.py", line 1353, in _flush_output
    self._connection._flush_output(lambda: self.is_closed, *waiters)
  File "D:\project\virtualEnv\rabbitmq_pika\lib\site-packages\pika\adapters\blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.StreamLostError: Stream connection lost: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)

Process finished with exit code 1

The rabbitmq had been install successfully  and can be browser in chrome.
this is the rabbitmq status

C:\Users\86138>rabbitmqctl status
Status of node rabbit@honghh ...
Runtime

OS PID: 20088
OS: Windows
Uptime (seconds): 710
Is under maintenance?: false
RabbitMQ version: 3.10.22
RabbitMQ release series support status: supported
Node name: rabbit@honghh
Erlang configuration: Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]
Crypto library: OpenSSL 3.1.0 14 Mar 2023
Erlang processes: 418 used, 1048576 limit
Scheduler run queue: 1
Cluster heartbeat timeout (net_ticktime): 60

Plugins

Enabled plugin file: c:/Users/86138/AppData/Roaming/RabbitMQ/enabled_plugins
Enabled plugins:

 * rabbitmq_management
 * amqp_client
 * rabbitmq_web_dispatch
 * cowboy
 * cowlib
 * rabbitmq_management_agent

Data directory

Node data directory: c:/Users/86138/AppData/Roaming/RabbitMQ/db/rabbit@honghh-mnesia
Raft data directory: c:/Users/86138/AppData/Roaming/RabbitMQ/db/rabbit@honghh-mnesia/quorum/rabbit@honghh

Config files

 * c:/Users/86138/AppData/Roaming/RabbitMQ/advanced.config

Log file(s)

 * <stdout>
 * c:/Users/86138/AppData/Roaming/RabbitMQ/log/rabbit@honghh.log
 * c:/Users/86138/AppData/Roaming/RabbitMQ/log/rabbit@honghh_upgrade.log

Alarms

(none)

Memory

Total memory used: 0.1118 gb
Calculation strategy: rss
Memory high watermark setting: 0.4 of available memory, computed to: 27.3474 gb

code: 0.0368 gb (32.89 %)
other_proc: 0.0315 gb (28.13 %)
other_system: 0.0281 gb (25.08 %)
allocated_unused: 0.0058 gb (5.18 %)
metrics: 0.0021 gb (1.85 %)
other_ets: 0.0018 gb (1.65 %)
binary: 0.0017 gb (1.5 %)
atom: 0.0015 gb (1.31 %)
reserved_unallocated: 0.001 gb (0.94 %)
plugins: 0.001 gb (0.9 %)
mgmt_db: 0.0004 gb (0.4 %)
mnesia: 0.0001 gb (0.08 %)
msg_index: 0.0 gb (0.03 %)
quorum_ets: 0.0 gb (0.03 %)
connection_other: 0.0 gb (0.02 %)
quorum_queue_procs: 0.0 gb (0.0 %)
quorum_queue_dlx_procs: 0.0 gb (0.0 %)
stream_queue_procs: 0.0 gb (0.0 %)
stream_queue_replica_reader_procs: 0.0 gb (0.0 %)
connection_readers: 0.0 gb (0.0 %)
connection_writers: 0.0 gb (0.0 %)
connection_channels: 0.0 gb (0.0 %)
queue_procs: 0.0 gb (0.0 %)
queue_slave_procs: 0.0 gb (0.0 %)
stream_queue_coordinator_procs: 0.0 gb (0.0 %)

File Descriptors

Total: 2, limit: 65439
Sockets: 0, limit: 58893

Free Disk Space

Low free disk space watermark: 0.05 gb
Free disk space: 303.502 gb

Totals

Connection count: 0
Queue count: 0
Virtual host count: 1

Listeners

Interface: [::], port: 15672, protocol: http, purpose: HTTP API
Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: 0.0.0.0, port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0

C:\Users\86138>

Best,
hanhuihong

**Comment by frost-nzcr4** [comment]
It looks like you have an error in the host parameter, because you have RabbitMQ hosted on `Interface: 0.0.0.0, port: 5672, protocol: amqp`, so you need to replace `127.0.0.1` with `0.0.0.0`:

```python
# producer.py
import pika
connection = pika.BlockingConnection(pika.ConnectionParameters('0.0.0.0', heartbeat=0))
channel = connection.channel()
channel.queue_declare(queue='hello',durable=True)
channel.basic_publish(exchange='', routing_key='hello', body='Hello Yuan!')
print(" [x] Sent 'Hello Yuan!'")
```

**Comment by honghh2018** [comment]
您好！已经收到邮件，祝好！                                    洪汉辉
