### ISSUE TITLE
pika.exceptions.AMQPConnectionError: (0, '') in send.py from tut

### ISSUE THREAD

**Issue by hvnsweeting** [pika/pika#226]
I've doing tut from here http://www.rabbitmq.com/tutorials/tutorial-one-python.html , and got an exceptiion when run send.py 
I've search around and have no ideal about this.

(env)hvn@hvnatvcc: ~/xzone/rabbitmq $ python send.py 
No handlers could be found for logger "pika.adapters.base_connection"
Traceback (most recent call last):
  File "send.py", line 6, in <module>
    host='localhost'))
  File "/home/hvn/xzone/rabbitmq/env/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 61, in **init**
    super(BaseConnection, self).**init**(parameters, on_open_callback)
  File "/home/hvn/xzone/rabbitmq/env/local/lib/python2.7/site-packages/pika/connection.py", line 513, in **init**
    self._connect()
  File "/home/hvn/xzone/rabbitmq/env/local/lib/python2.7/site-packages/pika/connection.py", line 804, in _connect
    self._adapter_connect()
  File "/home/hvn/xzone/rabbitmq/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 146, in _adapter_connect
    self.process_data_events()
  File "/home/hvn/xzone/rabbitmq/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 88, in process_data_events
    if self._handle_read():
  File "/home/hvn/xzone/rabbitmq/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 184, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/home/hvn/xzone/rabbitmq/env/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 305, in _handle_read
    return self._handle_disconnect()
  File "/home/hvn/xzone/rabbitmq/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 181, in _handle_disconnect
    self._on_connection_closed(None, True)
  File "/home/hvn/xzone/rabbitmq/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 235, in _on_connection_closed
    raise exceptions.AMQPConnectionError(*self.closing)
pika.exceptions.AMQPConnectionError: (0, '')

(env)hvn@hvnatvcc: ~/xzone/rabbitmq $ pip freeze
argparse==1.2.1
pika==0.9.8
wsgiref==0.1.2

I'm using Ubuntu 12.04 64bit 
Package: rabbitmq-server
Version: 2.7.1-0ubuntu4

run code from receive.py got the same exception. Please help, thanks

**Comment by MartinYue** [comment]
thanks
