### ISSUE TITLE
No handlers could be found for logger "pika.adapters.base_connection"

### ISSUE THREAD

**Issue by alvinkatojr** [pika/pika#362]
I am trying to work out the first phase of the [_rabbitMQ tutorial_](http://www.rabbitmq.com/tutorials/tutorial-one-python.html) using a virtualenv. But I keep getting the "No handlers could be found for logger "pika.adapters.base_connection" " error.

I have tried previous solutions that involved import logging but none of them works. Please provide a solution because this is a common error for pika beginners like me. Thanks.
<code>No handlers could be found for logger "pika.adapters.base_connection" 
Traceback (most recent call last):
  File "receive.py", line 5, in <module>
    connection=pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 61, in **init**
    super(BaseConnection, self).**init**(parameters, on_open_callback)
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/connection.py", line 513, in **init**
    self._connect()
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/connection.py", line 804, in _connect
    self._adapter_connect()
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 146, in _adapter_connect
    self.process_data_events()
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 88, in process_data_events
    if self._handle_read():
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 184, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 300, in _handle_read
    return self._handle_error(error)
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 264, in _handle_error
    self._handle_disconnect()
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 181, in _handle_disconnect
    self._on_connection_closed(None, True)
  File "/home/alvin/.virtualenvs/sparkplug/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 235, in _on_connection_closed
    raise exceptions.AMQPConnectionError(*self.closing)
pika.exceptions.AMQPConnectionError: (0, '')
</code>

**Comment by cuiyz** [comment]
Have you changed the default username and password "guest/guest" for RabbitMQ, that will cause what you have seen.

**Comment by nqphuong** [comment]
It's ok for me @JamiesonWarner. Thanks.
