### ISSUE TITLE
sys.exc_info raises IndexError

### ISSUE THREAD

**Issue by senseysensor** [pika/pika#398]
Hello,

take a look at my traceback. Seems there are no 2 arguments in ConnectionClosed.__repr__ method (1 or 0 instead)

```traceback
Traceback (most recent call last):
  File "/Volumes/Applications/sergeg/Python/Projects/__project__/source/src/crawler/index.py", line 335, in obtain_and_process_task
    self._return_result()
  File "/Volumes/Applications/sergeg/Python/Projects/__project__/source/src/crawler/index.py", line 416, in _return_result
    self._response_q.publish_msg(msg, CONST.RABBIT.Q.notifiers_working['bind']['add_task_for_notifiers'])
  File "/Volumes/Applications/sergeg/Python/Projects/__project__/source/src/core/rabbit_mq.py", line 609, in publish_msg
    raise ExternalServiceError('Failed publish message into the exchange. Exception: %s, args: %s' % (sys.exc_info(), e))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/exceptions.py", line 53, in __repr__
    return 'The AMQP connection was closed (%s) %s' % (self.args[0],
IndexError: tuple index out of range
```

latest pika (0.9.13)

**Comment by vitaly-krugl** [comment]
Thank you for reporting. It's not longer an issue with the latest pika 0.10.0.

```
In [6]: try:
        raise ConnectionClosed()
except:
        print('%s' % (sys.exc_info(),))
   ...:     
(<class 'pika.exceptions.ConnectionClosed'>, The AMQP connection was closed: (), <traceback object at 0x10480b3b0>)
```
