### ISSUE TITLE
SelectConnection: Crash when attempting to reconnect for too long

### ISSUE THREAD

**Issue by eschnou** [pika/pika#399]
When using a SelectConnection, Pika crash after a few hundred reconnection attempts with a 'maximum recursion depth exceeded' error.

The root of the problem is the way timers are handled in the absence of poller:
https://github.com/pika/pika/blob/master/pika/adapters/select_connection.py#L111

If a callback triggers an add_timeout (which is the case here), this leads to a recursion and unfortunately till recursion optimization is not present in Python.

I still need to try to keep the ioloop on stop (and thus the poller) but wonder of the side-effects this could cause.

```
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <type 'exceptions.AttributeError'> ignored
2013/09/23 09:46:51 > ERROR Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/synapse/dispatcher.py", line 89, in start_amqp
    self.amqpsynapse.run()
  File "/usr/lib/python2.6/site-packages/synapse/amqp.py", line 89, in run
    self._connection.ioloop.start()
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 137, in start
    self.poller.start()
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 426, in start
    self.process_timeouts()
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 280, in process_timeouts
    callback()
  File "/usr/lib/python2.6/site-packages/synapse/amqp.py", line 154, in reconnect
    self._connection = self.connect()
  File "/usr/lib/python2.6/site-packages/synapse/amqp.py", line 94, in connect
    stop_ioloop_on_close=False)
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 51, in __init__
    stop_ioloop_on_close)
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 62, in __init__
    on_close_callback)
  File "/usr/lib/python2.6/site-packages/pika/connection.py", line 593, in __init__
    self.connect()
  File "/usr/lib/python2.6/site-packages/pika/connection.py", line 709, in connect
    self.add_timeout(self.params.retry_delay, self.connect)
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 73, in add_timeout
    return self.ioloop.add_timeout(deadline, callback_method)
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 111, in add_timeout
    return callback_method()
  File "/usr/lib/python2.6/site-packages/pika/connection.py", line 709, in connect
    self.add_timeout(self.params.retry_delay, self.connect)
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 73, in add_timeout
    return self.ioloop.add_timeout(deadline, callback_method)
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 111, in add_timeout
    return callback_method()
  File "/usr/lib/python2.6/site-packages/pika/connection.py", line 709, in connect

[...]
```

**Comment by timeemit** [comment]
I had run into the same issue.

Implemented the following workaround:

```python
import pika
import time
import logging

logger = logging.getLogger()

def attempt_connection():
    _connecting = True
    _connection = connect()
    while not _connection.is_open:
        logger.info('Connection still closed')
        try:
            # Succeeds once pika's internal poller has started
            logger.info('Invoking IO Loop')
            _connection.ioloop.start()
        except AttributeError:
            # If the poller has not started, ioloop is None
            logger.info('IO Loop not started.  Reconnection status is: {}'.format(_connecting))
            if not _connecting:
                logger.info('Retry Count: {}'.format(retry_count))
                if retry_count > 0:
                    sleep_time = 2 ** retry_count
                    logger.info('Sleeping {} seconds'.format(sleep_time))
                    time.sleep(2**retry_count) # Expontential backoff
                logger.info('Issuing reconnect attempt')
                _connecting = True
                _connection.connect()
def connect():
    logger.info('Connecting to %s', _url)
    return pika.SelectConnection(
        pika.URLParameters(_url),
        on_connection_open,
        on_connection_error,
        on_connection_close,
        stop_ioloop_on_close=False
    )

def on_connection_open():
    logger.info('Connected to {} successfully!'.format(_url))
    retry_count = 0
    _connecting = False
    logger.info('Creating a new channel')
    _connection.channel(on_channel_open)

def on_connection_error(*args, **kwargs):
    logger.warning('Connection to {} resulted in an error. Initiating new connection.'.format(_url))
    retry_count += 1
    _connecting = False

def on_connection_close(connection, reply_code, reply_text):
    logger.info('Connection closed')
    close_channel()
    _channel = None
    if _closing:
        # Connection close was intended, so stop the ioloop.
        logger.info('Stopping IO loop')
        _connection.ioloop.stop()
        logger.info('IO loop stopped')
    else:
        logger.warning('Unexpected connection close: (%s) %s', reply_code, reply_text)
        check_to_clear_queue()
        reconnect()
```

**Comment by unthingable** [comment]
This works for me, no more growing stack:

```python
class Consumer(object):
...
    def on_connection_closed(self, connection, reply_code, reply_text):
        self._subscription_channel = None
        if self._closing:
            self._connection.ioloop.stop()
        else:
            logger.warning('Connection closed, reopening in %d seconds: (%s) %s',
                           self._reconnect_wait, reply_code, reply_text)
            self._connection.add_timeout(self._reconnect_wait, self.reconnect)

    def reconnect(self):
        raise ReconnectionException()

    def run(self):
        while not self._closing:
            try:
                # Create a new connection
                self._connection = self.connect()

                # There is now a new connection, needs a new ioloop to run
                self._connection.ioloop.start()

            except ReconnectionException:
                self._connection.ioloop.stop()

    def stop(self):
        logger.info('Stopping')
        self._closing = True
        self.stop_consuming()
        self._connection.ioloop.start()
        logger.info('Stopped')
```

**Comment by vitaly-krugl** [comment]
@unthingable: I have always thought of SelectConnection's poller as an internal component of SelectConnection, and not a general-purpose I/O loop for my program.

**Comment by vitaly-krugl** [comment]
Many changes/fixes were made to SelectConnection's ioloop code, communications, and error-handling, and connectivity in general, in the 0.10.0 release and subsequently more in Pika master. Also, see the new SelectConnection example in this PR #710. Please post your results with pika 0.10.0 and latest pika master. Thank you.
