### ISSUE TITLE
Unexpected KeyError: 'Queue.DeclareOk' during BlockingChannel.queue_declare()

### ISSUE THREAD

**Issue by vak** [pika/pika#451]
```python
import pika
import unittest


class Test(unittest.TestCase):

    def test_hello_world_tutorial1(self):
        connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
        channel = connection.channel()
        channel.queue_declare(queue='hello')
        for _ in range(2):
            channel.basic_publish(exchange='',
                                  routing_key='hello',
                                  body='Hello World!')
            print " [x] Sent 'Hello World!'"
        #channel.queue_declare(queue='hello')

        def callback(ch, method, properties, body):
            try:
                print ch
                status = ch.queue_declare(queue='hello', passive=True)
                print " [x] Received %r" % (body,)
                print "status.method.message_count", status.method.message_count
            except Exception, e:
                print 'Exception:', e.__repr__()
                raise

        channel.basic_consume(callback,
                      queue='hello',
                      no_ack=True)
        print ' [*] Waiting for messages. To exit press CTRL+C'
        channel.start_consuming()
```

and the output:

```
 [x] Sent 'Hello World!'
 [x] Sent 'Hello World!'
<pika.adapters.blocking_connection.BlockingChannel object at 0x7fa92b005390>
<pika.adapters.blocking_connection.BlockingChannel object at 0x7fa92b005390>
 [x] Received 'Hello World!'
status.method.message_count 0
Exception: KeyError('Queue.DeclareOk',)
======================================================================
ERROR: test_hello_world_tutorial1 (rabbicop.tests.test_rabbitmq_basic.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vak/tmp/tests/test_rabbitmq_basic.py", line 30, in test_hello_world_tutorial1
    no_ack=True)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 220, in basic_consume
    {'consumer_tag': consumer_tag})])
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1104, in _rpc
    self._wait_on_response(method_frame))
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1124, in _send_method
    self.connection.process_data_events()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 215, in process_data_events
    if self._handle_read():
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 328, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 326, in _handle_read
    self._on_data_available(data)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1271, in _on_data_available
    self._process_frame(frame_value)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1351, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 963, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 791, in _handle_content_frame
    self._on_deliver(*response)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 886, in _on_deliver
    body)
  File "/home/vak/tmp/tests/test_rabbitmq_basic.py", line 21, in callback
    status = ch.queue_declare(queue='hello', passive=True)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 867, in queue_declare
    None, replies)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1107, in _rpc
    return self._process_replies(replies, callback)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1061, in _process_replies
    frame_value = self._frames[reply]
KeyError: 'Queue.DeclareOk'

----------------------------------------------------------------------
Ran 1 test in 0.050s

FAILED (errors=1)
```

reproducible with: 
```
  pika.__version__ '0.9.13'
  rabbitmq-server  3.1.3-1 and   rabbitmq-server 3.2.4-1
```

**Comment by pfreixes** [comment]
Hi guys,

I came across with this issue a few days ago, I'm using BlockingConnection and the Pika version 0.9.14. The code looks like that:

```python:
    connection = pika.BlockingConnection(pika.ConnectionParameters(
        host='localhost'))
    channel = connection.channel()

    # Declare and bind the queue to consume the messages
    result = channel.queue_declare()
    queue = result.method.queue
    channel.queue_bind(exchange='miimetiq', queue=queue,
                       routing_key='sometopic')

    def callback(channel, method, properties, message):
        queue_response = routing_key = properties.correlation_id.replace('-','')
        channel.queue_declare(queue=queue_response, auto_delete=True)
        channel.queue_bind(exchange='results', queue=queue_response, routing_key=routing_key)
        channel.basic_publish(
            exchange='results',
            routing_key=properties.correlation_id.replace('-', ''),
            body=json.dumps(miimetiq_response_payload),
            properties=pika.BasicProperties(content_type='application/json'))

    channel.basic_consume(callback, queue=queue)
    channel.start_consuming()
```

As you can see the design pattern looks like the snippet of code submit by @vak. After a while of time I found out the root of the issue, it is triggered because of the handling of frames belonging to other amqp messages, let me show you.

When a new amqp message get the `callback`  function it runs until the call to the `channel.queue_declare` is executed, this function [1] prepare the rpc to declare a new queue and register a callback to save the response as a frame in a global variable called `self._frames`. To get these frames the blocking channel calls to process_data_events [2] guessing that when it comes back the new frames will be available on the internal `self._frames`.

Meanwhile another amqp messages has arrived and the calling frames are waiting to be dispatched, the connection process all data available in the socket connection, looking first the frames of the new message arrived. Therefore first is called the callback related with this message, putting in hold the frame that responses to the new queue request belonging to the first amqp messages.

This new request also gets the `queue_declare` step and reproducing again the whole steps already mentioned before and also trying to register the properly callback for his `queue_declare` function.

At last the callback of the first connection is triggered and the replies are processed here [3], removing his replies and ALSO the replies that don't belong to its.

When the last request tries to process the replies it raises one exception because of the reply was removed before by the first request. 

I've made a draft patch that hash the replies by the name of the message plus the id or name of the type object, i.e "Queue.DeclareOk+queue_name", and add some needed arguments to retrieve the context of each message. 

What do you think about that ?

[1] https://github.com/pika/pika/blob/master/pika/adapters/blocking_connection.py#L878
[2] https://github.com/pika/pika/blob/master/pika/adapters/blocking_connection.py#L1142
[3] https://github.com/pika/pika/blob/master/pika/adapters/blocking_connection.py#L1102

**Comment by pfreixes** [comment]
There is a workaround to figure it out while the blocking connection adapter is not patched, using the basic_qos [1] set with `prefetch_count` argument as 1 avoids handle new messages until the current one is not `ack`, obviously it doesn't work if `no_ack` was set to True to consume the messages. 

To enable the `prefetch_count` set the qos before the `start_consuming` is called as the next snippet shows

```python
        channel = connection.channel()
        channel.queue_declare(queue="test", auto_delete=True)
        channel.queue_bind(exchange="test", queue="test")
        channel.basic_qos(prefetch_size=0, prefetch_count=1, all_channels=True)
        channel.start_consuming()
```

[1] http://pika.readthedocs.org/en/latest/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingChannel.basic_qos

**Comment by pfreixes** [comment]
There is no a good way to patch the blocking connection adapter, it lacks of stack frame up such as asyncronous adapter. The only way to figure it out for all RPC commands - i.e declare queue, bind queue, create exchange - is modify the core adding a new keyword to stack up other incomming frames until the `_rpc` is full finished. Obviusly this patch could be seen as a bit dumb because with the workarround that I posted before setting the `prefetch_count=1` gets the same behaviour. IMHO it shouldn't be patched but some kind of warning could be displayed if the user tries to run one RPC command in the middle of the callback when prefetch_count is greater than 1.

Another solution for that is implement a threaded adapter for the blocking connection to overcome this issue and allowing prefetch_count value greater than 0.

**Comment by vitaly-krugl** [comment]
@vak and @pfreixes: BlockingConnection has been completely re-implemented recently. Please re-test.

**Comment by vitaly-krugl** [comment]
Closing due to inactivity. Please open a new issue if this is still a problem with the latest pika release (0.10.0 at the time of this writing)
