### ISSUE TITLE
IndexError: pop from an empty deque

### ISSUE THREAD

**Issue by chubakur** [pika/pika#511]
```
Traceback (most recent call last):
  File "./tracer.py", line 223, in <module>
    proc.run()
  File "./tracer.py", line 133, in run
    self._connection.ioloop.start()
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 138, in start
    self.poller.start()
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 433, in start
    self.poll()
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 494, in poll
    self._handler(fileno, event, write_only=write_only)
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 318, in _handle_events
    self._handle_write()
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 358, in _handle_write
    frame = self.outbound_buffer.popleft()
IndexError: pop from an empty deque
```

Sometimes it arises from additional thread
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.6/site-packages/unirest/__init__.py", line 102, in __request
    callback(_unirestResponse)
  File "./tracer.py", line 176, in put_jobs_in_queue
    self.publish(ip)
  File "./tracer.py", line 98, in publish
    self._w_channel.basic_publish(exchange='', routing_key=self.W_QUEUE_NAME, body=message)
  File "/usr/lib/python2.6/site-packages/pika/channel.py", line 300, in basic_publish
    (properties, body))
  File "/usr/lib/python2.6/site-packages/pika/channel.py", line 1057, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/usr/lib/python2.6/site-packages/pika/connection.py", line 1503, in _send_method
    self._send_frame(frame.Method(channel_number, method_frame))
  File "/usr/lib/python2.6/site-packages/pika/connection.py", line 1490, in _send_frame
    self._flush_outbound()
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 77, in _flush_outbound
    self.ioloop.poller.poll(write_only=True)
  File "/usr/lib/python2.6/site-packages/pika/adapters/select_connection.py", line 494, in poll
    self._handler(fileno, event, write_only=write_only)
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 318, in _handle_events
    self._handle_write()
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 358, in _handle_write
    frame = self.outbound_buffer.popleft()
IndexError: pop from an empty deque
```

self._w_channel  it is channel, where 1 client publish, and 100+ clients consuming

Why this error is arises and what i can do with it?

Version of pika 0.9.14

**Comment by gmr** [comment]
Looks like you're doing cross-thread channel/connection use which is not supported.

**Comment by ybaruchel** [comment]
> Looks like you're doing cross-thread channel/connection use which is not supported.

Any plans on supporting cross-thread channel/connection?

**Comment by lukebakken** [comment]
> Any plans on supporting cross-thread channel/connection?

@ybaruchel no, not at this time. Pika is open-source so a motivated individual could contribute this feature, or build a library _on top_ of Pika that implements thread safety and other features.

**Comment by viniciusd** [comment]
Not sure I follow you here, there is an example of a basic threaded consumer that shares the connection object with the thread: https://github.com/pika/pika/blob/0.12.0/examples/basic_consumer_threaded.py

It isn't supported even though there is an official example using it?

**Comment by lukebakken** [comment]
@viniciusd that example is the _only_ way to do cross-thread method calls with Pika.

I believe that @derkinderfietsen implied something more transparent to the end-user, but that was just a guess.

**Comment by viniciusd** [comment]
I found this thread because I am having the same error with an expanded version of the basic consumer threaded example. But it is probably because I am sharing an outbound channel together with the connection itself (I am debugging it literally now)

**Comment by r-chris** [comment]
I am running into the exact same issue and am trying to solve this in an expanded example from the reference implementation as well. In my case I was trying to post a new message from a separate thread. I assume that - as shown in the example, I can also use `conn.add_callback_threadsafe(cb)` here to post on the same channel again.

@viniciusd please provide an update if you have gained more insight as I am also debugging this right now

**Comment by r-chris** [comment]
For me using `conn.add_callback_threadsafe(cb)` did the trick to being able to re-use the the connection / channel.

**Comment by viniciusd** [comment]
Same solution as you @r-chris. I moved the publishing logic into the thread-safe callback and it worked. I will take some time checking what `add_callback_threadsafe` actually does internally.

The issue I am currently facing is the fact that exceptions raised in the working thread make the consumer get stuck as the previous message didn't get its ack.

I am trying a continuous loop with `thread.join()` but it isn't doing the trick of raising the exception in the main thread.

```
    t.start()
    while t.is_alive():
        connection.sleep(1.0)
    t.join()
```

A bare `t.join()` wouldn't work because it blocks the current thread, then heartbeats wouldn't get sent to the server.

If you think this is an issue for you as well, we can open a separate issue to keep track of this so we don't flood this one anymore.

I understand it is more related to Python itself than Pika, but we could update the example if we find a straightforward way of propagating the exception without getting the consumer stuck.
