### ISSUE TITLE
Incompatible Protocol Error using pika 0.9.14

### ISSUE THREAD

**Issue by ayounes** [pika/pika#527]
I researched this before filing it to see if there is a mistake in my configuration but I couldn't fine one.  The only difference between the machine that complains about the protocol error and the one that does not is PIP.  PIP 6.0.8 vs PIP 1.5.6 (works).

Any thoughts?

pip --version
pip 6.0.8 from /usr/lib/python2.6/site-packages/pip-6.0.8-py2.6.egg (python 2.6)

# pip show pika
---
Name: pika
Version: 0.9.14
Location: /usr/lib/python2.6/site-packages
Requires: 

cat /etc/*-release
CentOS release 6.5 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
CentOS release 6.5 (Final)
CentOS release 6.5 (Final)

My RMQ version:   RabbitMQ 3.4.2, Erlang R14B04

# python producer.py 
2015-02-12 16:34:01,099 13248 Added: {'callback': <bound method BlockingConnection._on_connection_error of <pika.adapters.blocking_connection.BlockingConnection object at 0xb6d050>>, 'only': None, 'one_shot': False, 'arguments': None}
2015-02-12 16:34:01,099 13248 Added: {'callback': <bound method BlockingConnection._on_connection_start of <pika.adapters.blocking_connection.BlockingConnection object at 0xb6d050>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
2015-02-12 16:34:01,103 13248 Connecting to 10.1.1.1:5672
2015-02-12 16:34:01,105 13248 Socket Error on fd 3: 104
2015-02-12 16:34:01,105 13248 Incompatible Protocol Versions
Traceback (most recent call last):
  File "producer.py", line 1934, in <module>
    main(logger,options, parser)
  File "producer.py", line 1879, in main
    worker(logger, RMQ_QUEUE, 'finish_date')
  File "producer.py", line 749, in sample_task_worker
    data_connection = pika.BlockingConnection(pika.ConnectionParameters(host=RABBITMQ, credentials = cred))
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 130, in __init__
    super(BlockingConnection, self).__init__(parameters, None, False)
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 72, in __init__
    on_close_callback)
  File "/usr/lib/python2.6/site-packages/pika/connection.py", line 600, in __init__
    self.connect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 230, in connect
    error = self._adapter_connect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 309, in _adapter_connect
    self.process_data_events()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 348, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 343, in _handle_read
    return self._handle_error(error)
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 302, in _handle_error
    self._handle_disconnect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 248, in _handle_disconnect
    self._adapter_disconnect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 318, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 368, in _check_state_on_disconnect
    super(BlockingConnection, self)._check_state_on_disconnect()
  File "/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py", line 149, in _check_state_on_disconnect
    raise exceptions.IncompatibleProtocolError
pika.exceptions.IncompatibleProtocolError

In the RMQ log:

=WARNING REPORT==== 12-Feb-2015::16:42:27 ===
closing AMQP connection <0.16066.148> (10.3.1.3:45946 -> 10.1.1.1:5672):
connection_closed_abruptly

If I run this on another machine, I don't have issues:
pip --version
pip 1.5.6 from /usr/lib/python2.6/site-packages/pip-1.5.6-py2.6.egg (python 2.6)
pip show pika
---
Name: pika
Version: 0.9.14
Location: /usr/lib/python2.6/site-packages
Requires: 

cat /etc/*-release
CentOS release 6.5 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
CentOS release 6.5 (Final)
CentOS release 6.5 (Final)

**Comment by ayounes** [comment]
It turns out there was a connectivity issue between the two.  A firewall in between was blocking the connection which led to PIKA reporting a protocol error.
