### ISSUE TITLE
SelectConnection fails with socket.timeout most of the time when publishing a large number of large messages

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#538]
Both RabbitMQ broker and my test are running on my 2013 MacBookPro i7 with 16GB RAM.

Publishing a large number of large message via SelectConnection fails with socket.timeout most of the time. I implemented an app that reproduces this failure. It's on github at https://github.com/vitaly-krugl/pika-perf

Here is the command that reproduces the failure on my system:
```
python pika_perf.py publish --impl SelectConnection --exg test --size=50000 --msgs=100000
```

If it succeeds, repeat execution of the command in rapid succession. It usually fails for me the first time, though, and often with smaller messages sizes (e.g., 20000)
```
Traceback (most recent call last):
  File "pika_perf.py", line 187, in <module>
    main()
  File "pika_perf.py", line 92, in main
    messageSize=options.messageSize)
  File "pika_perf.py", line 183, in runSelectPublishTest
    connection.ioloop.start()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/select_connection.py", line 138, in start
    self.poller.start()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/select_connection.py", line 373, in start
    self.poll()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/select_connection.py", line 398, in poll
    self._handler(self.fileno, events, write_only=write_only)
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/base_connection.py", line 322, in _handle_events
    self._handle_read()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/base_connection.py", line 351, in _handle_read
    self._on_data_available(data)
  File "/Users/vkruglikov/ossdev/pika/pika/connection.py", line 1288, in _on_data_available
    self._process_frame(frame_value)
  File "/Users/vkruglikov/ossdev/pika/pika/connection.py", line 1355, in _process_frame
    if self._process_callbacks(frame_value):
  File "/Users/vkruglikov/ossdev/pika/pika/connection.py", line 1325, in _process_callbacks
    frame_value)                 # Args
  File "/Users/vkruglikov/ossdev/pika/pika/callback.py", line 61, in wrapper
    return function(*tuple(args), **kwargs)
  File "/Users/vkruglikov/ossdev/pika/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/Users/vkruglikov/ossdev/pika/pika/callback.py", line 232, in process
    callback(*args, **keywords)
  File "/Users/vkruglikov/ossdev/pika/pika/channel.py", line 959, in _on_openok
    self._on_openok_callback(self)
  File "pika_perf.py", line 158, in onChannelOpen
    body=message)
  File "/Users/vkruglikov/ossdev/pika/pika/channel.py", line 300, in basic_publish
    (properties, body))
  File "/Users/vkruglikov/ossdev/pika/pika/channel.py", line 1057, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/Users/vkruglikov/ossdev/pika/pika/connection.py", line 1510, in _send_method
    self._send_message(channel_number, method_frame, content)
  File "/Users/vkruglikov/ossdev/pika/pika/connection.py", line 1540, in _send_message
    self._flush_outbound()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/select_connection.py", line 77, in _flush_outbound
    self.ioloop.poller.poll(write_only=True)
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/select_connection.py", line 398, in poll
    self._handler(self.fileno, events, write_only=write_only)
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/base_connection.py", line 318, in _handle_events
    self._handle_write()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/base_connection.py", line 360, in _handle_write
    self.socket.sendall(frame)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out
```

**Comment by vitaly-krugl** [comment]
PR #545 (at least at commit 635957f8a780814cb6eaa91c886a891b31518662) appears as if it would also fix this issue

**Comment by gmr** [comment]
This is fixed, it should not be using socket.sendall which is the most likely cause of the issue.
