### ISSUE TITLE
Select Connection Close No such file or directory

### ISSUE THREAD

**Issue by rmb938** [pika/pika#548]
So I have a thread that contains this
```
def run(self):
        self.connection = self.connect()
        self.connection.ioloop.start()
        if not self.connection.is_closed and not self.connection.is_closing:
            self.connection.close()
```

ioloop.start() blocks until it is stopped and once it is stopped then the connection is closed

However when connection.close() is called I receive this error
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/pub/cmt/venv/lib/python2.7/site-packages/cmtwarehouse/rabbitmq/routing/subscriber.py", line 28, in run
    self.connection.close()
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 95, in close
    super(BaseConnection, self).close(reply_code, reply_text)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/connection.py", line 690, in close
    self._close_channels(reply_code, reply_text)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/connection.py", line 910, in _close_channels
    self._channels[channel_number].close(reply_code, reply_text)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/channel.py", line 383, in close
    self.basic_cancel(consumer_tag=consumer_tag)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/channel.py", line 180, in basic_cancel
    {'consumer_tag': consumer_tag})] if nowait is False else [])
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/channel.py", line 1046, in _rpc
    self._send_method(method_frame)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/channel.py", line 1057, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/connection.py", line 1503, in _send_method
    self._send_frame(frame.Method(channel_number, method_frame))
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/connection.py", line 1490, in _send_frame
    self._flush_outbound()
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 73, in _flush_outbound
    self.ioloop.poller._manage_event_state()
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 390, in _manage_event_state
    self.event_state)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 183, in update_handler
    self.poller.update_handler(fileno, events)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 427, in update_handler
    self._poll.modify(fileno, self.events)
IOError: [Errno 2] No such file or directory
```

I am using version 0.9.14

**Comment by vitaly-krugl** [comment]
@rmb938, how are you causing `ioloop.start()` to terminate?

**Comment by rmb938** [comment]
Calling ioloop.stop() in another thread.

**Comment by vitaly-krugl** [comment]
Hi @rmb938, I just ran the following simplistic program against pika 0.9.14 and didn't get a crash:

```
In [2]: import pika; import threading

In [3]: def f():
    c = pika.SelectConnection()
    t = threading.Timer(10, c.ioloop.stop)
    t.start()
    c.ioloop.start()
   ...:     

In [4]: f()

In [5]: pika.__version__
Out[5]: '0.9.14'
```

Would you mind putting together a very simple bare-bones script (akin to mine in simplicity) that reproduces the problem and post it as a comment in this issue?

**Comment by rmb938** [comment]
```
import pika
import threading

def main():
        credentials = pika.PlainCredentials(username="root", password="asdasd")
        params = pika.ConnectionParameters(host="database", port=5672, virtual_host="/", credentials=credentials)
        c = pika.SelectConnection(parameters=params, on_open_callback=(lambda c: c.channel(lambda ch: None)))
        t = threading.Timer(5, c.ioloop.stop)
        t.start()
        c.ioloop.start()
        c.close()

main()
```

```
Traceback (most recent call last):
  File "test", line 13, in <module>
    main()
  File "test", line 11, in main
    c.close()
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 95, in close
    super(BaseConnection, self).close(reply_code, reply_text)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/connection.py", line 690, in close
    self._close_channels(reply_code, reply_text)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/connection.py", line 910, in _close_channels
    self._channels[channel_number].close(reply_code, reply_text)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/channel.py", line 386, in close
    self._on_closeok, [spec.Channel.CloseOk])
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/channel.py", line 1046, in _rpc
    self._send_method(method_frame)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/channel.py", line 1057, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/connection.py", line 1503, in _send_method
    self._send_frame(frame.Method(channel_number, method_frame))
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/connection.py", line 1490, in _send_frame
    self._flush_outbound()
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 73, in _flush_outbound
    self.ioloop.poller._manage_event_state()
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 390, in _manage_event_state
    self.event_state)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 183, in update_handler
    self.poller.update_handler(fileno, events)
  File "/pub/cmt/venv/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 427, in update_handler
    self._poll.modify(fileno, self.events)
IOError: [Errno 2] No such file or directory
```

Platform is Redhat 7

**Comment by vitaly-krugl** [comment]
Thanks. I am also able to reproduce it on Amazon's CentOS release 6.3 (Final) using pika 0.9.14

**Comment by rmb938** [comment]
The issue does not seem to happen on OSX 10.10.* so it could just be a rhel or linux issue.

**Comment by wjps** [comment]
I would imagine SelectConnection is picking the KQueuePoller on OSX whereas it'll be picking EPoll on Linux and the code is quite different.

PR #549 contains a fix if you're interested.

**Comment by rmb938** [comment]
That would make sense. Thanks for making a fix.

**Comment by vitaly-krugl** [comment]
CC @wjps

The original problem has to do with with misplaced clean-up logic in `select_connection.PollPoller.start()`. In the existing implementation, there is no clean way to gracefully close the connection after `PollPoller.start()` terminates as the result of the call to `ioloop.stop()`, which sets the `.open` member to `False`. Referring to the code below, after the `while self.open:` loop terminates, the function unregisters `self.fileno`, which explains the subsequent `IOError: [Errno 2] No such file or directory` in the context of `Connection.close()`

```
    def start(self):
        """Start the main poller loop. It will loop here until self.closed"""
        was_open = self.open
        while self.open:
            self.poll()
            self.process_timeouts()
            self._manage_event_state()
        if not was_open:
            return
        try:
            LOGGER.info("Unregistering poller on fd %d" % self.fileno)
            self.update_handler(self.fileno, 0)
            self._poll.unregister(self.fileno)
        except IOError as err:
            LOGGER.debug("Got IOError while shutting down poller: %s", err)

```

**Comment by gmr** [comment]
I believe this was fixed in #555, please reopen if not.

**Comment by radzhome** [comment]
I'm seeing the error when using blocking connection with `multiprocessing` in pika `0.11.2`. After a few mins of running ok I get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/pipeline/python/daemons/split_files.py", line 126, in mp_file
    queue_compare_tickets(broker_data, diag, rows, filename)
  File "/pipeline/python/daemons/../lib/queue_helpers.py", line 51, in queue_compare_tickets
    'tickets': tix,
  File "/usr/local/virtualenvs/pipeline_py3/src/fanx-service-clients/serviceclients/queue/rabbit.py", line 127, in publish
    self._channel.basic_publish(exchange=exchange, routing_key=exchange, body=data, properties=props)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish
    mandatory, immediate)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2164, in publish
    self._flush_output()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 456, in _flush_output
    self._impl.ioloop.process_timeouts()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 224, in process_timeouts
    self._poller.process_timeouts()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/heartbeat.py", line 88, in send_and_check
    return self._close_connection()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/heartbeat.py", line 125, in _close_connection
    text)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/connection.py", line 1974, in _on_terminate
    self._adapter_disconnect()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 110, in _adapter_disconnect
    self.ioloop.remove_handler(self.socket.fileno())
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 202, in remove_handler
    self._poller.remove_handler(fileno)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 418, in remove_handler
    self._unregister_fd(fileno, events_to_clear=events_cleared)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 983, in _unregister_fd
    self._poll.unregister(fileno)
FileNotFoundError: [Errno 2] No such file or directory
```

I'll see if ignoring the error for now is ok.

**Comment by lukebakken** [comment]
@radzhome if you can provide code to reproduce, that would be great. Please note that you *must* start a completely new Pika connection and set of channels per `multiprocessing` process. You can't share anything between processes.
