### ISSUE TITLE
connection fails using newly released jython 2.7.0

### ISSUE THREAD

**Issue by michaelplaing** [pika/pika#584]
using jython installed to mac via homebrew:
```
>>> import pika
>>> connection = pika.SelectConnection()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/pika/adapters/select_connection.py", line 47, in __init__
    super(SelectConnection, self).__init__(parameters,
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/pika/adapters/base_connection.py", line 69, in __init__
    super(BaseConnection, self).__init__(parameters,
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/pika/connection.py", line 600, in __init__
    self.connect()
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/pika/connection.py", line 708, in connect
    error = self._adapter_connect()
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/pika/adapters/select_connection.py", line 61, in _adapter_connect
    error = super(SelectConnection, self)._adapter_connect()
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/pika/adapters/base_connection.py", line 124, in _adapter_connect
    error = self._create_and_connect_to_socket(sock_addr)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/pika/adapters/base_connection.py", line 168, in _create_and_connect_to_socket
    self.socket.setsockopt(SOL_TCP, socket.TCP_NODELAY, 1)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/_socket.py", line 1367, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/_socket.py", line 357, in handle_exception
    return method_or_function(*args, **kwargs)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/_socket.py", line 357, in handle_exception
    return method_or_function(*args, **kwargs)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/_socket.py", line 1204, in setsockopt
    raise error(errno.ENOPROTOOPT, "Protocol not available")
_socket.error: [Errno 42] Protocol not available
```

**Comment by vitaly-krugl** [comment]
It's a bug in the recently-release Jython 2.7: see http://bugs.jython.org/issue2273

**Comment by vitaly-krugl** [comment]
This was a problem in Jython. The Jython issue http://bugs.jython.org/issue2273 appears to have been fixed. There is also a new pika release 0.10.0. Please retest with the fixed Jython and open a new issue if this is still a problem.
