### ISSUE TITLE
Max recursion error when publishing to the Queue

### ISSUE THREAD

**Issue by tamjd1** [pika/pika#642]
I have a long-running process which accepts messages from RabbitMQ, does some processing, then publishes the success or failure message back to a different Queue. Every now and then, randomly it seems, I keep getting the following exception. Once this exception happens, all future jobs raise the same exception, until I bounce the server which resolves the issue.

[08/27/2015 09:28:01 AM][ERROR][PID:3351] [worker.py] in handle_message on line 97 : Caught an exception when attempting to publish to the Queue
Traceback (most recent call last):
  File "worker.py", line 69, in handle_message
    ch, conn = RabbitFactory.createchannel()
  File "/app/munger/scripts/RabbitFactory.py", line 24, in createchannel
    connection = pika.BlockingConnection(pika.ConnectionParameters(host=host))
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 130, in __init__
    super(BlockingConnection, self).__init__(parameters, None, False)
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 72, in __init__
    on_close_callback)
  File "/usr/local/lib/python2.7/site-packages/pika/connection.py", line 600, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 230, in connect
    error = self._adapter_connect()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 309, in _adapter_connect
    self.process_data_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 348, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 351, in _handle_read
    self._on_data_available(data)
  File "/usr/local/lib/python2.7/site-packages/pika/connection.py", line 1285, in _on_data_available
    self._process_frame(frame_value)
  File "/usr/local/lib/python2.7/site-packages/pika/connection.py", line 1352, in _process_frame
    if self._process_callbacks(frame_value):
  File "/usr/local/lib/python2.7/site-packages/pika/connection.py", line 1322, in _process_callbacks
    frame_value)                 # Args
  File "/usr/local/lib/python2.7/site-packages/pika/callback.py", line 61, in wrapper
    return function(*tuple(args), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pika/callback.py", line 227, in process
    self._use_one_shot_callback(prefix, key, callback_dict)
  File "/usr/local/lib/python2.7/site-packages/pika/callback.py", line 400, in _use_one_shot_callback
    callback_dict[self.ARGUMENTS])
  File "/usr/local/lib/python2.7/site-packages/pika/callback.py", line 54, in wrapper
    args[offset] = _name_or_value(args[offset])
  File "/usr/local/lib/python2.7/site-packages/pika/callback.py", line 25, in _name_or_value
    if issubclass(value, amqp_object.AMQPObject):
RuntimeError: maximum recursion depth exceeded while calling a Python object

For weeks at a time, it would run smoothly, and then all of a sudden all jobs start failing because of this Exception. 

At first, I thought it was this issue: https://github.com/pika/pika/issues/286. But there is no ACK happening in my application. I have no_ack=True in basic_consume. Is this a known issue? Is there a fix for it? 

Thanks, 
T

**Comment by vitaly-krugl** [comment]
This problem should be addressed in the pre-release version of pika 0.10.0 (`pip install pika --pre`)

**Comment by tamjd1** [comment]
Will give it a go and share results. The only issue is, it happens randomly after weeks of stability and I can't seem to figure out how to recreate it. Nonetheless, I'll give pika 0.10.0 a test drive for some time and report back.

Thanks,
T

**Comment by vitaly-krugl** [comment]
One way that recursion could happen with pika 0.9.14 is if you were consuming and publishing on the same connection. Let's say every time your consumer callback was called, you published something in response from the consumer callback's scope. If you had more messages in the queue then python's recursion limit, you could end up in a sequence like this:

1. Consumer callback is called
2. The app publishes a messages via basic_publish from the scope of the consumer callback
3. The consumer callback is called again before `basic_publish` returns
4. The app publish another message from the second consumer callback
5. The consumer callback is called again before the second `basic_publish` returns; and so on.
6. We're now a couple of levels deep, and the stacked calls will continue to increase until the app fails with recursion error.

NOTE: Be sure to read the release notes for 0.10.0, as there are some API changes (they shouldn't affect most developers, but it's better to be safe than sorry).

You might also find that publishing with BlockingConnection in pika v0.10.0 is a lot faster in many cases than in the preceding versions. In some of my tests, I clocked a 40X - 60X performance improvement. The one case where I saw only a minor performance improvement (3X ?) is when publishing a persistent message to a durable queue using the `mandatory` flag with publisher acks turned on (confirm_delivery mode) - in this case, RabbitMQ itself becomes the bottleneck.

**Comment by tamjd1** [comment]
Just reporting back... The pre-release version of the code has been in our UAT environment for over a month now and no issues so far!

**Comment by vitaly-krugl** [comment]
Thanks for the feedback. Let's go ahead and close this issue.

Best,
Vitaly

**Comment by mustfkeskin** [comment]
> One way that recursion could happen with pika 0.9.14 is if you were consuming and publishing on the same connection. Let's say every time your consumer callback was called, you published something in response from the consumer callback's scope. If you had more messages to consume from a queue than python's recursion limit, you could end up in a sequence like this:
> 
> 1. Consumer callback is called
> 2. The app publishes a messages via basic_publish from the scope of the consumer callback
> 3. The consumer callback is called again before `basic_publish` returns
> 4. The app publish another message from the second consumer callback
> 5. The consumer callback is called again before the second `basic_publish` returns; and so on.
> 6. We're now a couple of levels deep, and the stacked calls will continue to increase until the app fails with recursion error.
> 
> NOTE: Be sure to read the release notes for 0.10.0, as there are some API changes (they shouldn't affect most developers, but it's better to be safe than sorry).
> 
> You might also find that publishing with BlockingConnection in pika v0.10.0 is a lot faster in many cases than in the preceding versions. In some of my tests, I clocked a 40X - 60X performance improvement. The one case where I saw only a minor performance improvement (3X ?) is when publishing a persistent message to a durable queue using the `mandatory` flag with publisher acks turned on (confirm_delivery mode) - in this case, RabbitMQ itself becomes the bottleneck.

İ have same problem
How do you solve it
