### ISSUE TITLE
ProbableAuthenticationError not turned into callback in TornadoConnection

### ISSUE THREAD

**Issue by gmr** [pika/pika#649]
```python
ERROR      2015-09-16 14:45:22 2184   async-1         tornado.application  handle_callback_exception: Exception in callback None
Traceback (most recent call last):
  File "/Users/gavinr/Source/rejected/env/lib/python2.7/site-packages/tornado/ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "/Users/gavinr/Source/rejected/env/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/gavinr/Source/rejected/env/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 364, in _handle_events
    self._handle_read()
  File "/Users/gavinr/Source/rejected/env/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 412, in _handle_read
    return self._handle_disconnect()
  File "/Users/gavinr/Source/rejected/env/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 288, in _handle_disconnect
    self._adapter_disconnect()
  File "/Users/gavinr/Source/rejected/env/lib/python2.7/site-packages/pika/adapters/tornado_connection.py", line 73, in _adapter_disconnect
    super(TornadoConnection, self)._adapter_disconnect()
  File "/Users/gavinr/Source/rejected/env/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 154, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/Users/gavinr/Source/rejected/env/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 173, in _check_state_on_disconnect
    raise exceptions.ProbableAuthenticationError
ProbableAuthenticationError
```

**Comment by sjlongland** [comment]
I've occasionally butted heads with this exception myself.  Is there a workaround?  (Sometimes it isn't an authentication error, just the AMQP broker being slow.)

**Comment by sjlongland** [comment]
@dave-shawley: That indeed does cure this problem.  Thank-you.

**Comment by vitaly-krugl** [comment]
fixed

**Comment by vitaly-krugl** [comment]
Fixed in Pika master, closing
