### ISSUE TITLE
Long Running BlockingConnection to publish

### ISSUE THREAD

**Issue by BradRuderman** [pika/pika#668]
I am trying to run a long process, however i keep getting disconnects from heartbeats. I read this article (http://stackoverflow.com/questions/14572020/handling-long-running-tasks-in-pika-rabbitmq) which makes me think I should disable heartbeats, but I feel like that could lead to a lot of orphaned connections. The repo is below. What other recommendations for just a simple queue processor? Should I use some type of async connection?

```
import pika
import time

class QueueManager:
  def __init__(self, **kwargs):
    parameters = pika.ConnectionParameters(host=kwargs['rabbitmq_uri'], heartbeat_interval=10)
    self._connection = pika.BlockingConnection(parameters)
    self._channel = self._connection.channel()
    self._exchange = 'test-exchange'
    self._channel.exchange_declare(exchange=self._exchange, type='direct', auto_delete=True)
    self._queue = self._channel.queue_declare(auto_delete=False, durable=True, queue='test-queue')
    self._channel.queue_bind(exchange=self._exchange,queue='test-queue', routing_key='test-route')
  
  def __enter__(self):
    return self

  def __exit__(self, exc_type, exc_value, traceback):
    if self._connection.is_open:
      self._connection.close()
  
  def push_to_queue(self, message):
    print("Processing " + message)
    self._channel.basic_publish(exchange=self._exchange,routing_key='test-route',body=message)

with QueueManager(rabbitmq_uri='192.168.99.100') as q:
  items_to_process = [1,2,3]
  while True:
    for i in items_to_process:
      q.push_to_queue(str(i))
    time.sleep(35)
```

Error message.
```
> python queue_repo.py
Processing 1
Processing 2
Processing 3
Processing 1
Traceback (most recent call last):
  File "queue_repo.py", line 31, in <module>
    q.push_to_queue(str(i))
  File "queue_repo.py", line 23, in push_to_queue
    self._channel.basic_publish(exchange=self._exchange,routing_key='test-route',body=message)
  File "python3.4/site-packages/pika-0.10.0-py3.4.egg/pika/adapters/blocking_connection.py", line 1978, in basic_publish
  File "python3.4/site-packages/pika-0.10.0-py3.4.egg/pika/adapters/blocking_connection.py", line 2065, in publish
  File "python3.4/site-packages/pika-0.10.0-py3.4.egg/pika/adapters/blocking_connection.py", line 1174, in _flush_output
  File "python3.4/site-packages/pika-0.10.0-py3.4.egg/pika/adapters/blocking_connection.py", line 395, in _flush_output
pika.exceptions.ConnectionClosed
```

I do see the disconnect on the server from the heartbeat.

**Comment by gmr** [comment]
Don't use time.sleep... that blocks Python from running. Use ``BlockingConnection.sleep``:

http://pika.readthedocs.org/en/0.10.0/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingConnection.sleep

If you're emulating some long running processing per message, you're best to use a background thread for the actual processing and poll for completion before moving on to the next message.
