### ISSUE TITLE
Pika python3 deserialization error

### ISSUE THREAD

**Issue by txomon** [pika/pika#706]
I have found a bug that is not present in python2.

I will try to find the root cause, but if any of you wants to try it meanwhile...

Versions are python 2.7.11, 3.5.1 and pika 0.10.0

Test case script:
```
from __future__ import print_function
import json
import pika

rb = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
ch = rb.channel()
ch.queue_declare(queue='test')
ch.queue_purge(queue='test')

ch.basic_publish(
    exchange='',
    routing_key='test',
    body='{"id": "%s"}' % 'hello',
    properties=pika.BasicProperties(
        delivery_mode=2,
    )
)


def consume_cb(channel, method, properties, body):
    print("Received body '%s' type '%s'" % (body, type(body)))
    task = json.loads(body)


ch.basic_qos(prefetch_count=1)
ch.basic_consume(consume_cb, queue='test', no_ack=False)
ch.start_consuming()
```

Sample output of the script:
```
(ve2)javier@thorin:~/projects/spinoffs/pika$ activate 3
(ve3)javier@thorin:~/projects/spinoffs/pika$ python test_case.py
Received body 'b'{"id": "hello"}'' type '<class 'bytes'>'
Traceback (most recent call last):
  File "test_case.py", line 27, in <module>
    ch.start_consuming()
  File "/home/javier/ve3/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/home/javier/ve3/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/home/javier/ve3/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/home/javier/ve3/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "test_case.py", line 22, in consume_cb
    task = json.loads(body)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
(ve2)javier@thorin:~/projects/spinoffs/pika$ activate 2
(ve2)javier@thorin:~/projects/spinoffs/pika$ python test_case.py
Received body '{"id": "hello"}' type '<type 'str'>'
^CTraceback (most recent call last):
  File "test_case.py", line 27, in <module>
    ch.start_consuming()
  File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 1681, in start_consuming
  File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 647, in process_data_events
  File "build/bdist.linux-x86_64/egg/pika/adapters/blocking_connection.py", line 410, in _flush_output
  File "build/bdist.linux-x86_64/egg/pika/adapters/select_connection.py", line 590, in poll
KeyboardInterrupt

```

**Comment by txomon** [comment]
My mistake, it should be decoded in python3, I will add an if clause for datatype for compatibility
