### ISSUE TITLE
pika SSL connection to RabbitMQ 3.4.2-1 failing

### ISSUE THREAD

**Issue by abakhru** [pika/pika#726]
```
import os
import pika
import sys
import ssl
import logging

from urllib import urlencode

certs_dir = "/tmp/rabbitmq"
host = "my_server"

ssl_opts = urlencode({"ssl_options": {"ca_certs": os.path.join(certs_dir, "ca_cert.pem"),
                                      "keyfile": os.path.join(certs_dir, host + "_key.pem"),
                                      "certfile": os.path.join(certs_dir, host + "_cert.pem"),
                                      "cert_reqs": ssl.CERT_REQUIRED}})
full_url = "amqps://guest:guest@%s%s?%s" % (host, "/rsa/sa", ssl_opts)
parameters = pika.URLParameters(full_url)

logger = logging.getLogger()
logger.addHandler(logging.StreamHandler(sys.stdout))
logging.getLogger("pika").setLevel(logging.DEBUG)
logging.getLogger("pika").propagate = True

connection = pika.BlockingConnection(parameters)
channel = connection.channel()
message="This is not a message, this is a tribute to a message"
my_routing_key=""
exchange_name="esa.events"
channel.exchange_declare(exchange=exchange_name,
                         type="direct",
                         durable=True)
channel.basic_publish(exchange=exchange_name,
                      routing_key=my_routing_key,
                      body=message)

channel.close()
connection.close()
```

Output:
```
Connecting to 10.101.59.231:5671 with SSL
Connection to 10.101.59.231:5671 failed: [Errno 54] Connection reset by peer
Could not connect, 0 attempts left
Processing 0:_on_connection_error
Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x10c593320>> for "0:_on_connection_error"
Traceback (most recent call last):
  File "./pika_trials.py", line 31, in <module>
    connection = pika.BlockingConnection(parameters)
  File "build/bdist.macosx-10.10-x86_64/egg/pika/adapters/blocking_connection.py", line 374, in __init__
  File "build/bdist.macosx-10.10-x86_64/egg/pika/adapters/blocking_connection.py", line 421, in _process_io_for_connection_setup
pika.exceptions.AMQPConnectionError: Connection to 10.101.59.231:5671 failed: [Errno 54] Connection reset by peer
```

rabbitmq.config ssl section:
```
{ssl_cert_login_from, common_name},
        {ssl_listeners, [5671]},
        {ssl_apps, [asn1,crypto,public_key,ssl]},
        {ssl_options, [
            {cacertfile, "/etc/rabbitmq/ssl/truststore.pem"},
            {certfile, "/etc/rabbitmq/ssl/server/cert.pem"},
            {keyfile, "/etc/rabbitmq/ssl/server/key.pem"},
            {verify, verify_peer},
            {fail_if_no_peer_cert, true},
            {ssl_cert_login_from, common_name},
            {ciphers, [
                {rsa, aes_256_cbc, sha}
            ]}
```

erlang version: R16B03-0.2
Can someone please fix this issue?

**Comment by abakhru** [comment]
i'm using latest master from this repo

**Comment by vitaly-krugl** [comment]
@abakhru, I would like to welcome you to the community. Would you be able to investigate and contribute a fix? Thank you.

Vitaly

**Comment by vitaly-krugl** [comment]
@gmr, I investigated and suspect that SSL in pika is now quite broken following #578. When the socket was blocking prior to that PR, all of the special OpenSSL I/O management was taking place inside OpenSSL. Once the socket became non-blocking, I think we have to expect SSLWantReadError, SSLWantWriteError, and friends at any time (not just during initial handshake; e.g., readable socket might read an incomplete SSL record, so subsequent wait for readability is needed before any data can be returned to pika), check for pending data and process it all before waiting for readable socket again, etc.

**Comment by vitaly-krugl** [comment]
I am able to get it to work using pika from current master branch at commit 51fd186f1fabe0da8582609d266df1e28e57e3f4 and RabbitMQ 3.6.0. I suspect that the release pika 0.10.0 would work, too.

Note the use of `ssl_version=ssl.PROTOCOL_TLSv1`.

See https://www.rabbitmq.com/ssl.html for certificate creation and rabbitmq SSL configuration instructions.

```
import ssl

import pika

cp = pika.ConnectionParameters(
    ssl=True,
    ssl_options=dict(
        ssl_version=ssl.PROTOCOL_TLSv1,
        ca_certs="/Users/me/rabbitmqcert/testca/cacert.pem",
        keyfile="/Users/me/rabbitmqcert/client/key.pem",
        certfile="/Users/me/rabbitmqcert/client/cert.pem",
        cert_reqs=ssl.CERT_REQUIRED))

conn = pika.BlockingConnection(cp)
ch = conn.channel()
ch.queue_declare("sslq")
Out[10]: <METHOD(['channel_number=1', 'frame_type=1', "method=<Queue.DeclareOk(['consumer_count=0', 'message_count=0', 'queue=sslq'])>"])>

ch.publish("", "sslq", "abc")
ch.basic_get("sslq")
Out[17]: 
(<Basic.GetOk(['delivery_tag=1', 'exchange=', 'message_count=0', 'redelivered=False', 'routing_key=sslq'])>,
 <BasicProperties>,
 'abc')
```

I followed the setup instructions in https://www.rabbitmq.com/ssl.html, including rabbitmq.config and generation of all the certificates, and was able to get it to work with pika.BlockingConnection, after all.

Both the client and rabbitmq server were running on my MacBookPro. I created rabbitmq.config in its default location for OS X: /usr/local/etc/rabbitmq/rabbitmq.config

Its contents (using certificate directory structure and contents created following instructions in https://www.rabbitmq.com/ssl.html):

Note that in my test, I configured rabbit to accept SSL connection only on the local interface.

```
[
  {rabbit,
    [   
      {ssl_listeners, [{"127.0.0.1", 5671}]},

      %% Configuring SSL.
      %% See http://www.rabbitmq.com/ssl.html for full documentation.
      %%
      {ssl_options, [{cacertfile,           "/Users/me/rabbitmqcert/testca/cacert.pem"},
                     {certfile,             "/Users/me/rabbitmqcert/server/cert.pem"},
                     {keyfile,              "/Users/me/rabbitmqcert/server/key.pem"},
                     {verify,               verify_peer},
                     {fail_if_no_peer_cert, true}]}
    ]   
  }
].
```
