### ISSUE TITLE
keep getting pika.exceptions.ConnectionClosed for no reason

### ISSUE THREAD

**Issue by ziXiong** [pika/pika#729]
Hi all,

Here is my case, I write a log handler in python to publish log to rabbitmq used in django project. 
I'm using `{rabbit,"RabbitMQ","3.6.1"}`  and `pika (0.10.0) ` . But it keeps getting exception `pika.exceptions.ConnectionClosed` and `Fatal Socket Error: BrokenPipeError(32, 'Broken pipe')`. 
 I know pika is not thread safe, so I lock basic_publish in code; 
and I know there is a heartbeat between rabbit server and client, so I disable it. But i still get errors.  
I have no idea now.  Does someone run into the same problem? 

Here is my code:
```python
class MQHandler(logging.Handler):
    """
    Handler that send log to rabbitmq.
    """

    def __init__(self, host, port=None, virtual_host=None, username=None, password=None, exchange='log'):
        logging.Handler.__init__(self)
        self.connection_para = dict(host=host)
        if port:
            self.connection_para['port'] = port
        if virtual_host:
            self.connection_para['virtual_host'] = virtual_host
        if username and password:
            self.connection_para['credentials'] = credentials.PlainCredentials(username, password)
        self.exchange = exchange
        self.connection, self.channel = None, None

        # lock connection and basic_publish because thread safety problem.
        self.emit_lock = threading.Lock()
       
        self.connect()

    def connect(self):
        """connect to rabbitmq"""

        # disable heartbeat.
        self.connection_para['heartbeat_interval'] = 0
        self.connection = pika.BlockingConnection(pika.ConnectionParameters(**self.connection_para))
        self.channel = self.connection.channel()
        self.channel.exchange_declare(exchange=self.exchange, type='topic', durable=True, auto_delete=False)

    def emit(self, record):
        start_time = time()
        self.emit_lock.acquire()
        try:
            if not self.connection or not self.channel:
                self.connect()
            if self.connection and self.channel:
                routing_key = "{name}.{level}".format(name=record.name, level=record.levelname)
                self.channel.basic_publish(exchange=self.exchange,
                                           routing_key=routing_key,
                                           body=self.format(record),
                                           properties=pika.BasicProperties(
                                               delivery_mode=2
                                           ))
        except Exception:
            # assign to None so handler can reconnect next time.
            self.channel, self.connection = None, None
            self.handleError(record)
        finally:
            self.emit_lock.release()
```
And exceptions are like
```python
Traceback (most recent call last):
File "/home/deploy/www/myxx/env/lib/python3.5/site-packages/pika/adapters/base_connection.py", line 427, in _handle_write
bw = self.socket.send(frame)
BrokenPipeError: [Errno 32] Broken pipe
```
or
```python
122284   Traceback (most recent call last):
122285   File "./utils/mq/handlers.py", line 62, in emit
122286     delivery_mode=2
122287   File "/home/deploy/www/myxx/env/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 1978, in basic_publish
122288     mandatory, immediate)
122289   File "/home/deploy/www/myxx/env/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 2065, in publish
122290     self._flush_output()
122291   File "/home/deploy/www/myxx/env/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 1174, in _flush_output
122292     *waiters)
122293   File "/home/deploy/www/myxx/env/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
122294     raise exceptions.ConnectionClosed()
122295 pika.exceptions.ConnectionClosed
122296 Call stack:
122297   File "/home/deploy/www/myxx/env/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
122298     response = self.get_response(request)
122299   File "/home/deploy/www/myxx/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 125, in get_response
122300     response = middleware_method(request, callback, callback_args, callback_kwargs)
122301   File "./utils/middlewares/gatemiddleware.py", line 39, in process_view
122302     device=request.device))
122303   File "/usr/lib/python3.5/logging/__init__.py", line 1279, in info
122304     self._log(INFO, msg, args, **kwargs)
122305   File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
122306     self.handle(record)
122307   File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
122308     self.callHandlers(record)
122309   File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
122310     hdlr.handle(record)
122311   File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
122312     self.emit(record)
122313   File "./utils/mq/handlers.py", line 67, in emit
122314     self.handleError(record)
```
And I'm using `uwsgi 2.0.11.2`.

Thanks!!!

**Comment by ziXiong** [comment]
It turned out be the problem of multi-process mode of uwsgi.  Uwsgi spawns workers that share file descriptors.  That is  worse than multi-threads, because even lock won't help.

Any way, the solution is to set  `lazy-apps = true` in uwsgi ini file, which makes wokers not share file descriptors.
Wish this could help those who have the same problem with me.

**Comment by vitaly-krugl** [comment]
Thanks for the update. I am going to close the issue in this case.

**Comment by Akanoa** [comment]
You've saved my evening! many thanks :) @ziXiong
