### ISSUE TITLE
some questions in DLX  ! 

### ISSUE THREAD

**Issue by Michael754267513** [pika/pika#767]
dear guys!
           i want to test DLX, queue setting x-dead-letter-exchange and x-dead-letter-routing-key,my provider send message is ok,,now i run consume is failed!

consume example:
```
#!/usr/bin/env python
import pika
 
connection = pika.BlockingConnection(pika.ConnectionParameters(
        host='localhost'))
channel = connection.channel()
 
channel.queue_declare(queue='task_queue', durable=True)
print ' [*] Waiting for messages. To exit press CTRL+C'
 
def callback(ch, method, properties, body):
    if body == "task_queue":
        ch.basic_reject(requeue=False)
    else:
        print " [x] Received %r" % (body,)
        ch.basic_ack(delivery_tag = method.delivery_tag)
 
channel.basic_qos(prefetch_count=1)
channel.basic_consume(callback,
                      queue='task_queue')
 
channel.start_consuming()
```
run exception:
```
Traceback (most recent call last):
  File "work1.py", line 9, in <module>
    channel.queue_declare(queue='task_queue', durable=True)
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 2329, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 1181, in _flush_output
    raise exceptions.ChannelClosed(method.reply_code, method.reply_text)
pika.exceptions.ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'task_queue' in vhost '/': received none but current is the value 'dead_letter_exchange' of type 'longstr'")
```

**Comment by vitaly-krugl** [comment]
@Michael754267513, I wrapped your sample and traceback in "```" to make the code easier to read (indentation and all)

**Comment by Michael754267513** [comment]
thanks a lot for your suggestions !  i track this agent!

**Comment by vitaly-krugl** [comment]
Thanks for the update!

**Comment by nicbou** [comment]
When you find the solution to your problem, don't leave everyone else hanging, Michael.

https://xkcd.com/979/
