### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'send'

### ISSUE THREAD

**Issue by ricoxor** [pika/pika#775]
I'm using rabbitMQ with Scrapy (Python) and after 10 minutes I have this error in loop.
I don't know why the socket crash.

There is a piece of my code here : http://stackoverflow.com/questions/39895827/rabbitmq-multiple-senders-for-one-receiver

Thank's

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/crawl.py", line 72, in _parse_response
    cb_res = callback(response, **cb_kwargs) or ()
  File "dirbot/spiders/expired_one.py", line 65, in parse_items
    delivery_mode=2,
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1978, in basic_publish
    mandatory, immediate)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 2064, in publish
    immediate=immediate)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 338, in basic_publish
    (properties, body))
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1571, in _send_method
    self._send_message(channel_number, method_frame, content)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1601, in _send_message
    self._flush_outbound()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 282, in _flush_outbound
    self._handle_write()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 427, in _handle_write
    bw = self.socket.send(frame)
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by michaelklishin** [comment]
Please post server logs. The object that's `None` seems to be connection socket.

**Comment by ricoxor** [comment]
Here is my serveur logs : 

```
=INFO REPORT==== 7-Oct-2016::10:51:28 ===
accepting AMQP connection <0.2965.0> (127.0.0.1:60174 -> 127.0.0.1:5672)

=INFO REPORT==== 7-Oct-2016::10:51:28 ===
accepting AMQP connection <0.2976.0> (127.0.0.1:60175 -> 127.0.0.1:5672)

=INFO REPORT==== 7-Oct-2016::10:51:38 ===
closing AMQP connection <0.251.0> (127.0.0.1:59795 -> 127.0.0.1:5672)

=ERROR REPORT==== 7-Oct-2016::11:03:23 ===
closing AMQP connection <0.2304.0> (127.0.0.1:60088 -> 127.0.0.1:5672):
missed heartbeats from client, timeout: 60s

=ERROR REPORT==== 7-Oct-2016::11:08:28 ===
closing AMQP connection <0.2646.0> (127.0.0.1:60145 -> 127.0.0.1:5672):
missed heartbeats from client, timeout: 60s

```

**Comment by ricoxor** [comment]
Here is the logs before the error messages : 

```
2016-10-09 20:43:49 [pika.adapters.base_connection] ERROR: Socket Error: 104
2016-10-09 20:43:49 [pika.adapters.base_connection] WARNING: Socket closed when connection was open
2016-10-09 20:43:49 [pika.connection] WARNING: Disconnected from RabbitMQ at localhost:5672 (0): Not specified
```

Thank's for your help

**Comment by vitaly-krugl** [comment]
Pika has no auto-reconnect. You can't continue to use the connection after it disconnects. Also, in case there are threads involved, a pika connection is not thread-safe.

**Comment by ricoxor** [comment]
Do you know why the connection disconnects ?
And how fix that ?

**Comment by gmr** [comment]
The reason is detailed in your logs:

```
2016-10-09 20:43:49 [pika.adapters.base_connection] ERROR: Socket Error: 104
2016-10-09 20:43:49 [pika.adapters.base_connection] WARNING: Socket closed when connection was open
```

https://www.google.com/search?client=safari&rls=en&q=google+unix+socket+error+104&ie=UTF-8&oe=UTF-8 yields that 104 is "Connection reset by peer" which would indicate the socket was remotely closed. 

There re too many possibilities to enumerate here, but one thing to take a look at is if you have heartbeats enabled and are not responding to them and RabbitMQ is disconnecting you.  You might want to take a look at your RabbitMQ server logs to see if it says anything about the connection your seeing reset.
