### ISSUE TITLE
pika.exceptions.ConnectionClosed

### ISSUE THREAD

**Issue by NicolasDuran** [pika/pika#779]
Using **RabbitMQ 3.6.5** on **Debian 8**
I create a queue containing the numbers for 1 to 100000.
I have workers running on docker (based on debian latest), containing pika.version = 0.10.0
```
import pika

conn = pika.URLParameters('amqp://xxx:xxx@spotted-monkey.rmq.cloudamqp.com/ctuzjcxs')
connection = pika.BlockingConnection(conn)

channel = connection.channel()
channel.queue_declare(queue='task_queue', durable=True)

def callback(ch, method, properties, body):
    print('GOT:' + str(body))
    ch.basic_ack(delivery_tag = method.delivery_tag)

channel.basic_qos(prefetch_count=1)
channel.basic_consume(callback, queue='task_queue')
channel.start_consuming()
```
Some of the workers works perfectly, some other fails very quickly with errors such as :
 
```
 3> ERROR:pika.adapters.base_connection:Socket Error: 104
 3> WARNING:pika.adapters.base_connection:Socket closed when connection was open
 3> WARNING:pika.connection:Disconnected from RabbitMQ at spotted-monkey.rmq.cloudamqp.com:5672 (0): Not specified
 3> CRITICAL:pika.adapters.blocking_connection:Connection close detected
 3> Traceback (most recent call last):
 3>   File "receiver-class2.py", line 25, in <module>
 3>     channel.start_consuming()
 3>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
 3>     self.connection.process_data_events(time_limit=None)
 3>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 647, in process_data_events
 3>     self._flush_output(common_terminator)
 3>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 426, in _flush_output
 3>     raise exceptions.ConnectionClosed()
 3> pika.exceptions.ConnectionClosed
```
or 
```
 0> Traceback (most recent call last):
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/base_connection.py", line 384, in _handle_read
 0>     data = self.socket.recv(self._buffer_size)
 0> ConnectionResetError: [Errno 104] Connection reset by peer
 0> 
 0> During handling of the above exception, another exception occurred:
 0> 
 0> Traceback (most recent call last):
 0>   File "receiver-class2.py", line 6, in <module>
 0>     connection = pika.BlockingConnection(conn)
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 339, in __init__
 0>     self._process_io_for_connection_setup()
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup
 0>     self._open_error_result.is_ready)
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
 0>     self._impl.ioloop.poll()
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/select_connection.py", line 602, in poll
 0>     self._process_fd_events(fd_event_map, write_only)
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/select_connection.py", line 443, in _process_fd_events
 0>     handler(fileno, events, write_only=write_only)
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/base_connection.py", line 364, in _handle_events
 0>     self._handle_read()
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/base_connection.py", line 407, in _handle_read
 0>     return self._handle_error(error)
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/base_connection.py", line 338, in _handle_error
 0>     self._handle_disconnect()
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/base_connection.py", line 288, in _handle_disconnect
 0>     self._adapter_disconnect()
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/select_connection.py", line 95, in _adapter_disconnect
 0>     super(SelectConnection, self)._adapter_disconnect()
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/base_connection.py", line 154, in _adapter_disconnect
 0>     self._check_state_on_disconnect()
 0>   File "/usr/local/lib/python3.4/site-packages/pika/adapters/base_connection.py", line 169, in _check_state_on_disconnect
 0>     raise exceptions.IncompatibleProtocolError
 0> pika.exceptions.IncompatibleProtocolError
```

on rabbitMQ, the logs shows : 
```
=INFO REPORT==== 26-Oct-2016::20:53:23 ===
accepting AMQP connection <0.4144.1> ([::1]:48194 -> [::1]:5672)

=WARNING REPORT==== 26-Oct-2016::20:53:23 ===
closing AMQP connection <0.4144.1> ([::1]:48194 -> [::1]:5672):
client unexpectedly closed TCP connection

=INFO REPORT==== 26-Oct-2016::20:53:23 ===
accepting AMQP connection <0.4147.1> ([::1]:48195 -> [::1]:5672)
```

I played with the heartbeat_interval, socket_timeout, connection_attempts, retry_delay parameters, without success.

What can I do ?

**Comment by vitaly-krugl** [comment]
Based on the Pika logs, it seems like the client thinks that the server closed the connection: "Socket closed when connection was open". Perhaps there is something wrong with your docker/network configuration?

Also, recent RabbitMQ servers default to 60 seconds heartbeat timeout (it used to be almost 10 minutes in older versions of RabbitMQ). The ability to increase this is broken in the released versions of pika, but is fixed in pika master. If you have control over the RabbitMQ server configuration, you should be able to increase the default heartbeat timeout that way, too.

**Comment by NicolasDuran** [comment]
It was a problem on my side, a bad network configuration on my cloud provider.

**Comment by vitaly-krugl** [comment]
@NicolasDuran, thank you for the update.

**Comment by thasler** [comment]
@NicolasDuran can you provide more details about the network configuration issue? which cloud provider do you use?

**Comment by nicgirault** [comment]
In my case here is the logs I get:

```
[ERROR] Error event 25, None
[CRITICAL] Tried to handle an error where no error existed
[ERROR] Socket Error: 104
[INFO] Disconnected from RabbitMQ at blablabla.com:5672 (-1): ConnectionResetError(104, 'Connection reset by peer')
[ERROR] Connection close detected; result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED socket=None params=<ConnectionParameters host=blablabla.com port=5672 virtual_host=/ ssl=False>>, reason_code=-1, reason_text="ConnectionResetError(104, 'Connection reset by peer')")
Traceback (most recent call last):
  File "/xxx/worker.py", line 91, in <module>
    channel.start_consuming()
  File "/xxx/env/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1780, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/xxx/env/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 707, in process_data_events
    self._flush_output(common_terminator)
  File "/xxx/env/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 474, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
```

I'm using AWS with 2 EC2 instances. The worker is not on the same instance than the RabbitMQ server

**Comment by lukebakken** [comment]
@nicgirault - do you also see a message similar to this in the RabbitMQ logs?

```
=WARNING REPORT==== 26-Oct-2016::20:53:23 ===
closing AMQP connection <0.4144.1> ([::1]:48194 -> [::1]:5672):
client unexpectedly closed TCP connection
```

**Comment by vitaly-krugl** [comment]
@nicgirault, it looks like epoll was being used and event 25 is the combination of EPOLLIN, EPOLLERR, and EPOLLHUP, meaning that the other end (presumably RabbitMQ server) closed the connection.

**Comment by lukebakken** [comment]
@nicgirault is there a load balancer between your application and RabbitMQ? That is what first comes to mind when I see both sides of a connection unexpectedly close like this.

**Comment by nicgirault** [comment]
@lukebakken no, there is no load balancer.

My setup is the following:

- I have a first EC2 instance running RabbitMQ in a docker container (https://hub.docker.com/_/rabbitmq/) without any customisation (other than custom username/password). Port 5672 is open on this instance.

- on the same instance is running a Flask application. A HTTP POST on a route executes this code publishing to rabbitmq:

```python
connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost', credentials=RABBITMQ_CREDENTIALS))
channel = connection.channel()

channel.queue_declare(queue=COMPUTE_THETAS_QUEUE)
channel.basic_publish(exchange='', routing_key=COMPUTE_THETAS_QUEUE, body=str(student_id))
```

I just noticed here that I never close the connexion so a new connexion was created but not closed each time this code was triggered. This might be the cause of my issue (I'm following this lead right now and will let you know if it fix my issue).

- On another EC2 instance, supervisor is handling a python script:

```python
connection = pika.BlockingConnection(
    pika.ConnectionParameters(
        socket_timeout=10,
        host=RABBITMQ_HOST, # this host is a public address to the other EC2 instance
        credentials=RABBITMQ_CREDENTIALS
    )
)
channel = connection.channel()
channel.queue_declare(queue=COMPUTE_THETAS_QUEUE)
channel.basic_consume(compute_thetas_receiver, queue=COMPUTE_THETAS_QUEUE, no_ack=True)
logging.info('[*] compute_thetas waiting for messages.')
channel.start_consuming()
connection.close()
```

**Comment by vitaly-krugl** [comment]
I recall from some time ago that RabbitMQ by default comes configured to support a very small number of file descriptors, and you need to change its configuration to support a much larger number of descriptors to use in a real environment. This comes up a number of times in the rabbitmq-users google group, for example [here](https://groups.google.com/d/msg/rabbitmq-users/uNJAT_nKANI/WVjtU3-oDwAJ)

**Comment by nicgirault** [comment]
I don't get the error since I close the connexion of the publisher :-). Thanks for your reactivity.

**Comment by wood-j** [comment]
maybe you should use self.connection if in a class, so that could prevent connection got cleaned by gc.
