### ISSUE TITLE
pika authentication fails with ExternalCredentials

### ISSUE THREAD

**Issue by vaishalipavashe** [pika/pika#784]
I am getting 'pika.exceptions.ProbableAuthenticationError' when I am trying to create connection with RabbitMQ provided by HP OneView:

http://h17007.www1.hpe.com/docs/enterprise/servers/oneviewhelp/oneviewRESTAPI/content/s_SCMB-python-fusion.html

I have downloaded certs required for authentication using ExternalCredentials. 
Here is debug and error message:

```
DEBUG:pika.callback:Processing 0:Connection.Start
DEBUG:pika.callback:Processing use of oneshot callback
DEBUG:pika.callback:0 registered uses left
DEBUG:pika.callback:Removing callback #0: {'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x102387e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 0}
DEBUG:pika.callback:Calling <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x102387e50>> for "0:Connection.Start"
DEBUG:pika.callback:Added: {'callback': <bound method SelectConnection._on_connection_tune of <pika.adapters.select_connection.SelectConnection object at 0x102387e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
DEBUG:pika.credentials:Not supported by this Credentials type
ERROR:pika.adapters.base_connection:Read empty data, calling disconnect
ERROR:pika.adapters.base_connection:Socket closed while authenticating indicating a probable authentication error
DEBUG:pika.callback:Added: {'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x102387e50>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
Traceback (most recent call last):
  File "scmb.py", line 53, in <module>
    connection = pika.BlockingConnection(parameters)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 339, in __init__
    self._process_io_for_connection_setup()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 528, in poll
    self._process_fd_events(fd_event_map, write_only)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 443, in _process_fd_events
    handler(fileno, events, write_only=write_only)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 364, in _handle_events
    self._handle_read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 412, in _handle_read
    return self._handle_disconnect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 288, in _handle_disconnect
    self._adapter_disconnect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 95, in _adapter_disconnect
    super(SelectConnection, self)._adapter_disconnect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 154, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 173, in _check_state_on_disconnect
    raise exceptions.ProbableAuthenticationError
pika.exceptions.ProbableAuthenticationError
```

**Comment by lukebakken** [comment]
`scmb.py` is not part of Pika, and we don't have the resources to address issues with 3rd-party software.
