### ISSUE TITLE
A new channel is unable to return by BlockingConnection.channel() method

### ISSUE THREAD

**Issue by ThreeWalnuts** [pika/pika#809]
I use BlockingConnection.channel() to get a channel to publish a message to a rabbit MQ queue.
In the beginning, everything is OK. I could get this channel successfully, and push a message to above queue successfully. However, nearly one hour later, when my program tries to get a new channel from channel() method, it throws the following error:
Traceback (most recent call last):
  File "waa_slack_message_receiver.py", line 50, in publish_message_to_MQ
    channel = **MQ_connection.channel()**
  **File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 689, in channel
    channel_number=channel_number)**
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 711, in channel
    return self._channels[channel_number]
**KeyError: 1**

And eventually, this error derives another error which is connection closed.
Traceback (most recent call last):
  File "waa_slack_message_receiver.py", line 50, in publish_message_to_MQ
    channel = MQ_connection.channel()
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 689, in channel
    channel_number=channel_number)
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 710, in channel
    self._channels[channel_number].open()
  File "/usr/lib/python2.7/site-packages/pika/channel.py", line 635, in open
    self._rpc(spec.Channel.Open(), self._on_openok, [spec.Channel.OpenOk])
  File "/usr/lib/python2.7/site-packages/pika/channel.py", line 1139, in _rpc
    self._send_method(method_frame)
  File "/usr/lib/python2.7/site-packages/pika/channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 1569, in _send_method
    self._send_frame(frame.Method(channel_number, method_frame))
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 1548, in _send_frame
    **raise exceptions.ConnectionClosed
ConnectionClosed**

Above MQ_connection is a BlockingConnection object. 
My pika version is 0.10.0. 
What should I do?

**Comment by ThreeWalnuts** [comment]
By the way, my rabbit MQ is not down. So it's very strange to have that error.

**Comment by wligang** [comment]
python ？

**Comment by ThreeWalnuts** [comment]
@wligang ,Yes

**Comment by ThreeWalnuts** [comment]
I found that the connection is closed for any unknown reason.
I need to reconnect to MQ.
RabbitMQ doesn't support long-lived connection?

**Comment by gmr** [comment]
Without seeing your code, it's hard to tell what is wrong other than a lack of exception handling. When the connection is closed, the exception contains the reason. So will your RabbitMQ logs.
