### ISSUE TITLE
Pika Connection Closed when basic_ack with many ack messages

### ISSUE THREAD

**Issue by 1rr0m** [pika/pika#814]
Hey,

I have a problem with pika 0.10.0.

**This is critical. This issue makes rabbitmq unusable.**

My configuration is as follows:
I have two named durable queues binded to the fanout exchange.
I use blocking connections for both producer and consumer. My messages are persistent and they need to be acked.

My problem arises when there are several thousands of messages ready to be delivered. Then I run my consumer (two threads taking from the queues) and messages are becoming unacked. I see the number of unacked messages skyrocketing. After some time, (my message processing takes several minutes) the connection is closed and the unacked messages becomes ready and so on. The bakctrace shows that this line is responsible for that:
channel.basic_ack(delivery_tag = method.delivery_tag) - that is when i ack message.

It works fine if there are a few messages, but when it comes to several thousands it crashes.

I assume when there are many messages unacked or they are becoming at once it crashes.

Here goes my code:

Consumer part:
```
#!/usr/bin/env python

import traceback
import pika
import threading
import time

class ConsumerThread1(threading.Thread):
    def __init__(self, host, *args, **kwargs):
        super(ConsumerThread1, self).__init__(*args, **kwargs)
        connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost', heartbeat_interval=0))
        self.channel = connection.channel()
        self.channel.exchange_declare(exchange='logs',
                                 type='fanout')
        self.channel.queue_declare(queue='q1', durable=True)
        self.channel.queue_bind(exchange='logs',
                           queue='q1')
        print(' [*] Waiting for logs. To exit press CTRL+C')

    # Not necessarily a method.
    def callback_func(self, channel, method, properties, body):
        try:
            print("{} q1 received '{}'".format(self.name, body))
            time.sleep(5)
            self.channel.basic_ack(delivery_tag = method.delivery_tag)
            print "Done"
        except Exception as e:
            print "Blad: " + str(e)

    def run(self):
        self.channel.basic_consume(self.callback_func,
                              queue='q1')
        self.channel.start_consuming()

class ConsumerThread2(threading.Thread):
    def __init__(self, host, *args, **kwargs):
        super(ConsumerThread2, self).__init__(*args, **kwargs)
        connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost', heartbeat_interval=0))
        self.channel = connection.channel()
        self.channel.exchange_declare(exchange='logs',
                                 type='fanout')
        self.channel.queue_declare(queue='q2', durable=True)
        self.channel.queue_bind(exchange='logs',
                           queue='q2')
        print(' [*] Waiting for logs. To exit press CTRL+C')

    # Not necessarily a method.
    def callback_func(self, channel, method, properties, body):
        try:
            print("{} q2 received '{}'".format(self.name, body))
            time.sleep(5)
            self.channel.basic_ack(delivery_tag = method.delivery_tag)
            print "Done"
        except Exception:
            traceback.print_exc()

    def run(self):
        self.channel.basic_consume(self.callback_func,
                              queue='q2')
        self.channel.start_consuming()

if __name__ == "__main__":
    threads = [ConsumerThread1("host1"), ConsumerThread2("host2")]
    for thread in threads:
        thread.start()
```

Producer part(just for generating test data):
```
#!/usr/bin/env python
import pika
import sys
import random
import time


connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
channel = connection.channel()

channel.exchange_declare(exchange='logs',
                         type='fanout')

while True:
    message = "Nr: " + str(random.randint(1,100))
    channel.basic_publish(exchange='logs',
                          routing_key='',
                           properties=pika.BasicProperties(
                         delivery_mode = 2, # make message persistent
                      ),
                          body=message)
    print(" [x] Sent %r" % message)
    print "Sent !"

connection.close()
```
I also get: **Attempted to send frame when closed.**

Backtrace:
Here is the stacktrace:

Traceback (most recent call last):
  File "C:/Users/Tom/PycharmProjects/rabbitmqerror/consumer.py", line 54, in callback_func
    self.channel.basic_ack(delivery_tag = method.delivery_tag)
  File "C:\Python27\lib\site-packages\pika\adapters\blocking_connection.py", line 1888, in basic_ack
    self._impl.basic_ack(delivery_tag=delivery_tag, multiple=multiple)
  File "C:\Python27\lib\site-packages\pika\channel.py", line 159, in basic_ack
    return self._send_method(spec.Basic.Ack(delivery_tag, multiple))
  File "C:\Python27\lib\site-packages\pika\channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "C:\Python27\lib\site-packages\pika\connection.py", line 1569, in _send_method
    self._send_frame(frame.Method(channel_number, method_frame))
  File "C:\Python27\lib\site-packages\pika\connection.py", line 1548, in _send_frame
    raise exceptions.ConnectionClosed
ConnectionClosed

Any help appreciated.

**Comment by 1rr0m** [comment]
Here is the stacktrace:

Traceback (most recent call last):
  File "C:/Users/Tom/PycharmProjects/rabbitmqerror/consumer.py", line 54, in callback_func
    self.channel.basic_ack(delivery_tag = method.delivery_tag)
  File "C:\Python27\lib\site-packages\pika\adapters\blocking_connection.py", line 1888, in basic_ack
    self._impl.basic_ack(delivery_tag=delivery_tag, multiple=multiple)
  File "C:\Python27\lib\site-packages\pika\channel.py", line 159, in basic_ack
    return self._send_method(spec.Basic.Ack(delivery_tag, multiple))
  File "C:\Python27\lib\site-packages\pika\channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "C:\Python27\lib\site-packages\pika\connection.py", line 1569, in _send_method
    self._send_frame(frame.Method(channel_number, method_frame))
  File "C:\Python27\lib\site-packages\pika\connection.py", line 1548, in _send_frame
    raise exceptions.ConnectionClosed
ConnectionClosed
