### ISSUE TITLE
AMQPConnectionError if connection attempted when RabbitMQ is restarting in Docker container

### ISSUE THREAD

**Issue by mlmarius** [pika/pika#830]
Using the asynchronous publisher or consumer examples, if the client attempts reconnection when the RabbitMQ server is beeing restarted, then the client fails with the following exeption, killing the thread. The asynchronous publisher example was used in this case.

```
WARNING:pika.connection:Could not connect, 3590 attempts left
INFO:pika.connection:Retrying in 1 seconds
DEBUG:pika.adapters.select_connection:add_timeout: added timeout 6258371582878442654; deadline=1.0 at 1498719339.78
INFO:pika.adapters.base_connection:Connecting to 127.0.0.1:5672
ERROR:pika.adapters.base_connection:Read empty data, calling disconnect
INFO:pika.connection:Disconnected from RabbitMQ at 127.0.0.1:5672 (-1): EOF
ERROR:pika.connection:Incompatible Protocol Versions
ERROR:pika.connection:Connection setup failed due to The protocol returned by the server is not supported: (-1, 'EOF')
```

Steps to reproduce:

1. start an async consumer or publisher with a small reconnect interval ( 1s )
2. stop the rabbitmq server 
3. start the rabbitmq server

**Comment by lukebakken** [comment]
I can't reproduce this using RabbitMQ 3.6.10, Arch Linux, python 2.7.13 and 3.6.2 using the attached code.
[repro.py.txt](https://github.com/pika/pika/files/1178138/repro.py.txt)

**Comment by mlmarius** [comment]
I have upgraded to python 2.7.13, reinstalled pika from the github repo and then:
- started the docker container running rabbitmq
- manually created the "test" queue on the default exchange
- ran the repo.py.txt script. The script connected and started consuming. Dispatching messages to the queue worked as expected
- shut down the docker container running rabbitmq. this is important. Just closing a port to the server in the firewall will not trigger this problem. The reconnection attempt needs to happen while the server is actually starting.
- the script detected this and started reconnection attempts
- after some seconds i restarted the docker container running the rabbitmq server.
- the blow-up happens every time and the error looks like this:

`
ERROR 2017-07-27 10:20:28,082 pika.adapters.base_connection _handle_read  447 : Read empty data, calling disconnect
INFO 2017-07-27 10:20:28,082 pika.connection _on_terminate  1922: Disconnected from RabbitMQ at 127.0.0.1:5672 (-1): EOF
ERROR 2017-07-27 10:20:28,083 pika.connection _on_terminate  1950: Incompatible Protocol Versions
ERROR 2017-07-27 10:20:28,083 pika.connection _on_terminate  1985: Connection setup failed due to The protocol returned by the server is not supported: (-1, 'EOF')
DEBUG 2017-07-27 10:20:28,083 pika.callback process  220 : Processing 0:_on_connection_error
DEBUG 2017-07-27 10:20:28,083 pika.callback process  234 : Calling <bound method SelectConnection._on_connection_error of <SelectConnection CLOSED socket=None params=<ConnectionParameters host=127.0.0.1 port=5672 virtual_host=/ ssl=False>>> for "0:_on_connection_error"
ERROR 2017-07-27 10:20:28,083 pika.callback process  239 : Calling <bound method SelectConnection._on_connection_error of <SelectConnection CLOSED socket=None params=<ConnectionParameters host=127.0.0.1 port=5672 virtual_host=/ ssl=False>>> for "0:_on_connection_error" failed
Traceback (most recent call last):
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/connection.py", line 1744, in _on_connection_error
    self.params.connection_attempts)
AMQPConnectionError: (-1, 'EOF')
DEBUG 2017-07-27 10:20:28,084 pika.adapters.select_connection start  502 : Cleaning up IOLoop
DEBUG 2017-07-27 10:20:28,084 pika.adapters.select_connection start  502 : Cleaning up IOLoop
DEBUG 2017-07-27 10:20:28,084 pika.adapters.select_connection start  502 : Cleaning up IOLoop
DEBUG 2017-07-27 10:20:28,085 pika.adapters.select_connection start  502 : Cleaning up IOLoop
DEBUG 2017-07-27 10:20:28,085 pika.adapters.select_connection start  502 : Cleaning up IOLoop
DEBUG 2017-07-27 10:20:28,085 pika.adapters.select_connection start  502 : Cleaning up IOLoop
DEBUG 2017-07-27 10:20:28,085 pika.adapters.select_connection start  502 : Cleaning up IOLoop
DEBUG 2017-07-27 10:20:28,085 pika.adapters.select_connection start  502 : Cleaning up IOLoop
DEBUG 2017-07-27 10:20:28,086 pika.adapters.select_connection start  502 : Cleaning up IOLoop
DEBUG 2017-07-27 10:20:28,086 pika.adapters.select_connection start  502 : Cleaning up IOLoop
Traceback (most recent call last):
  File "test3.py", line 305, in <module>
    main()  # (this code was run as script)
  File "test3.py", line 299, in main
    consumer.run()
  File "test3.py", line 265, in run
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "test3.py", line 99, in reconnect
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "test3.py", line 99, in reconnect
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "test3.py", line 99, in reconnect
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "test3.py", line 99, in reconnect
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "test3.py", line 99, in reconnect
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "test3.py", line 99, in reconnect
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "test3.py", line 99, in reconnect
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "test3.py", line 99, in reconnect
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "test3.py", line 99, in reconnect
    self._connection.ioloop.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 495, in start
    self.poll()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 816, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 625, in _dispatch_fd_events
    handler(fileno, events)
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 398, in _handle_events
    self._handle_read()
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 450, in _handle_read
    "EOF")
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/connection.py", line 1989, in _on_terminate
    connection_error)
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/Users/liviu/.virtualenvs/rabbitmq/lib/python2.7/site-packages/pika/connection.py", line 1744, in _on_connection_error
    self.params.connection_attempts)
pika.exceptions.AMQPConnectionError: (-1, 'EOF')`

**Comment by lukebakken** [comment]
Thanks for the additional information. There was no mention of Docker in your original report. I have saved your stack trace in a text file and attached it to your comment to keep from cluttering this page up.

**Comment by lukebakken** [comment]
I tried reproducing this issue using Docker without success. Here is my environment:

```
$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.9.1
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 23:08:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.9.1
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 23:09:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I have attached a transcript showing debug output and successful reconnection, even if I use `docker stop` and `docker start` on the image. I suspect this issue could be related to Docker on OS X.

[transcript.txt](https://github.com/pika/pika/files/1429026/transcript.txt)
