### ISSUE TITLE
Inconsistent acknowledgement behaviour between Mac OS X Yosemite and Ubuntu

### ISSUE THREAD

**Issue by tirkarthi** [pika/pika#836]
I have the following code : 

```
import time
import pika


def on_message(channel, method_frame, header_frame, body):
    print(method_frame.delivery_tag)
    print(body)
    time.sleep(20)
    channel.basic_ack(delivery_tag=method_frame.delivery_tag)

connection = pika.BlockingConnection()
channel = connection.channel()
channel.basic_consume(on_message, 'foo_queue')

try:
    channel.start_consuming()
except KeyboardInterrupt:
    channel.stop_consuming()
connection.close()

```

In Mac OS X Yosemite with local RabbitMQ installed via Homebrew I push a message "1" from the UI to the queue and then during the sleep period I stop RabbitMQ so that acknowledgment cannot be made. I ran `brew services stop rabbitmq` and then ran `ps aux | grep rabbitmq` to make sure there are no instance running. I receive the following : 

```
1
b'1'
Traceback (most recent call last):
  File "pika_foo.py", line 16, in <module>
    channel.start_consuming()
  File "/opt/hf-mail/mailworker/venv/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 1683, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/opt/hf-mail/mailworker/venv/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 649, in process_data_events
    self._flush_output(common_terminator)
  File "/opt/hf-mail/mailworker/venv/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 422, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
```

In Ubuntu when I follow the same steps the acknowledgment fails and throws appropriate error as below : 

```
1
b'1'
Traceback (most recent call last):
  File "pika_foo.py", line 17, in <module>
    channel.start_consuming()
  File "/home/ubuntu/env/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 1683, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/home/ubuntu/env/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 658, in process_data_events
    self._dispatch_channel_events()
  File "/home/ubuntu/env/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 471, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/home/ubuntu/env/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 1312, in _dispatch_events
    evt.body)
  File "pika_foo.py", line 9, in on_message
    channel.basic_ack(delivery_tag=method_frame.delivery_tag)
  File "/home/ubuntu/env/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 1891, in basic_ack
    self._flush_output()
  File "/home/ubuntu/env/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 1176, in _flush_output
    *waiters)
  File "/home/ubuntu/env/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 397, in _flush_output
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed
```

As per the Ubuntu stack trace I inserted a print statement in `blocking_connection.py` where it checks for `self._impl.is_closed` . In Mac OS X it returns False whereas in Ubuntu it returns True when acknowledgment is being made with RabbitMQ down.

Mac OS X details : 

```
(venv) ➜  python python
Python 3.5.2 (default, Oct 11 2016, 05:00:16)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pika
>>> pika.__version__
'0.10.0'
```

Ubuntu details : 

```
(env) ➜  python python
Python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pika
>>> pika.__version__
'0.10.0'
```

**Comment by gmr** [comment]
*do not use time.sleep*

http://pika.readthedocs.io/en/0.10.0/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingConnection.sleep
