### ISSUE TITLE
Restarting of RabbitMQ leads to exception

### ISSUE THREAD

**Issue by oleynikandrey** [pika/pika#856]
In version 0.11.0b1 restarting of RabbitMQ leads to crash.

```
INFO       2017-07-31 21:05:12,888 pika.connection                _on_terminate                        1922: Disconnected from RabbitMQ at localhost:5672 (320): CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
WARNING    2017-07-31 21:05:12,889 __main__                       on_channel_closed                    128 : Channel 1 was closed: (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
WARNING    2017-07-31 21:05:12,889 pika.connection                close                                1139: Suppressing close request on <AsyncioConnection CLOSED socket=None params=<URLParameters host=localhost port=5672 virtual_host=/ ssl=False>>
WARNING    2017-07-31 21:05:12,889 __main__                       on_connection_closed                 82  : Connection closed, reopening in 5 seconds: (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
INFO       2017-07-31 21:05:17,890 __main__                       connect                              50  : Connecting to amqp://guest:guest@localhost:5672/%2F
INFO       2017-07-31 21:05:17,891 pika.adapters.base_connection  _create_and_connect_to_socket        217 : Connecting to ::1:5672
ERROR      2017-07-31 21:05:17,895 pika.adapters.base_connection  _handle_read                         447 : Read empty data, calling disconnect
INFO       2017-07-31 21:05:17,896 pika.connection                _on_terminate                        1922: Disconnected from RabbitMQ at localhost:5672 (-1): EOF
ERROR      2017-07-31 21:05:17,896 pika.connection                _on_terminate                        1950: Incompatible Protocol Versions
ERROR      2017-07-31 21:05:17,896 pika.connection                _on_terminate                        1985: Connection setup failed due to The protocol returned by the server is not supported: (-1, 'EOF')
ERROR      2017-07-31 21:05:17,896 pika.callback                  process                              239 : Calling <bound method Connection._on_connection_error of <AsyncioConnection CLOSED socket=None params=<URLParameters host=localhost port=5672 virtual_host=/ ssl=False>>> for "0:_on_connection_error" failed
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\pika\callback.py", line 236, in process
    callback(*args, **keywords)
  File "C:\Python36\lib\site-packages\pika\connection.py", line 1744, in _on_connection_error
    self.params.connection_attempts)
pika.exceptions.AMQPConnectionError: (-1, 'EOF')
ERROR      2017-07-31 21:05:17,896 asyncio                        default_exception_handler            1259: Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "C:\Python36\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Python36\lib\site-packages\pika\adapters\base_connection.py", line 398, in _handle_events
    self._handle_read()
  File "C:\Python36\lib\site-packages\pika\adapters\base_connection.py", line 450, in _handle_read
    "EOF")
  File "C:\Python36\lib\site-packages\pika\connection.py", line 1989, in _on_terminate
    connection_error)
  File "C:\Python36\lib\site-packages\pika\callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "C:\Python36\lib\site-packages\pika\callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "C:\Python36\lib\site-packages\pika\callback.py", line 236, in process
    callback(*args, **keywords)
  File "C:\Python36\lib\site-packages\pika\connection.py", line 1744, in _on_connection_error
    self.params.connection_attempts)
pika.exceptions.AMQPConnectionError: (-1, 'EOF')
```

**Comment by vitaly-krugl** [comment]
@oleynikandrey: what did you expect to happen and what happens on 0.10.0 in this scenario? Thank you.

**Comment by oleynikandrey** [comment]
I thought that it will keep trying to connect to the brocker every 5 seconds and will continue to handle messages when broker become available. 

I don't know how does it work in 0.10.0.

**Comment by vitaly-krugl** [comment]
There might be some outstanding requests that were interrupted as the result of the restart. Pika lets the app know via exception so that the app can take whatever app-specific measures it needs to recover.

**Comment by oleynikandrey** [comment]
What is the correct way to get pika reconnecting say every 5 seconds while RabbitMQ is down?

**Comment by michaelklishin** [comment]
Pika does not support automatic connection recovery the same way Bunny, Java, .NET clients do. This is nothing new in `0.11`.

**Comment by michaelklishin** [comment]
Filed https://github.com/pika/pika/issues/858. This is not a small undertaking, although with at least 6 clients in 3 different languages using roughly the same recovery algorithm, there's plenty of prior art to learn from.

**Comment by lukebakken** [comment]
@oleynikandrey - use the [`connection_attempts`](https://github.com/pika/pika/blob/master/pika/connection.py#L59) to set the number of reconnection tries. The default value is `1` so set it to a higher value and re-try your test.

**Comment by lukebakken** [comment]
@oleynikandrey - I have a quick question - are you using the [`connection_attempts`](https://github.com/pika/pika/blob/master/pika/connection.py#L279-L286) parameter to set a value greater than `1` (the default)?

**Comment by oleynikandrey** [comment]
@lukebakken, I have tried with default value for `connection_attempts`

**Comment by lukebakken** [comment]
Thanks. If you have time, could you please try setting `connection_attempts` to `10` or so? I don't think it'll make a difference but I'd like to check.
