### ISSUE TITLE
pika 0.11.0 with twisted raises AlreadyCalled when connection lost

### ISSUE THREAD

**Issue by raidoz** [pika/pika#881]
Pika 0.11.0 raises AlreadyCalled when connection with the RabbitMQ server is lost and the connection times out. No other exceptions are raised when subscribe or publish activities are done and it is therefore quite difficult to detect the issue. On 0.10.0 the same situation results in a ```320, Too Many Missed Heartbeats, No reply in 120 seconds``` and can be easily recovered from. When the RabbitMQ server is shut down gracefully, then pika realizes this, but when it is an actual connectivity issue then the following is produced (which can be simulated by killing the RabbitMQ server with SIGKILL):
```
2017-10-02 09:27:42,852|CRITICAL|             _legacy| 154| Unhandled Error
Traceback (most recent call last):
  File "/opt/venv/mist/bin/rabbit-lighting", line 3, in <module>
    main()
  File "/opt/venv/mist/local/lib/python2.7/site-packages/rabbitlighting/main_rabbit_adapter.py", line 131, in main
    reactor.run()
  File "/opt/venv/mist/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/opt/venv/mist/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/opt/venv/mist/local/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/venv/mist/local/lib/python2.7/site-packages/pika/heartbeat.py", line 88, in send_and_check
    return self._close_connection()
  File "/opt/venv/mist/local/lib/python2.7/site-packages/pika/heartbeat.py", line 125, in _close_connection
    text)
  File "/opt/venv/mist/local/lib/python2.7/site-packages/pika/connection.py", line 1929, in _on_terminate
    self._remove_heartbeat()
  File "/opt/venv/mist/local/lib/python2.7/site-packages/pika/connection.py", line 1437, in _remove_heartbeat
    self.heartbeat.stop()
  File "/opt/venv/mist/local/lib/python2.7/site-packages/pika/heartbeat.py", line 109, in stop
    self._connection.remove_timeout(self._timer)
  File "/opt/venv/mist/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 145, in remove_timeout
    self.ioloop.remove_timeout(timeout_id)
  File "/opt/venv/mist/local/lib/python2.7/site-packages/pika/adapters/twisted_connection.py", line 226, in remove_timeout
    call.cancel()
  File "/opt/venv/mist/local/lib/python2.7/site-packages/twisted/internet/base.py", line 99, in cancel
    raise error.AlreadyCalled
twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.
```

**Comment by raidoz** [comment]
Perhaps similar to https://github.com/pika/pika/issues/875 ?

**Comment by lukebakken** [comment]
@raidoz - I am unsure how to reproduce this. I ran [this example code](https://github.com/pika/pika/blob/master/examples/twisted_service.py) using `twistd -ny ./twisted_service.py, published a message to the "task" queue, then killed `beam.smp` via `kill -9`. I have attached the output as a file.

I will close this issue for now but if you can provide a code sample that I can use to reproduce I am happy to fix the underlying problem. Thanks.

[twisted-log.txt](https://github.com/pika/pika/files/1373261/twisted-log.txt)
