### ISSUE TITLE
Bad file description exception when using channel.basic_ack()

### ISSUE THREAD

**Issue by marijngiesen** [pika/pika#884]
Since version 0.11.0 I'm getting the following exception when using channel.basic_ack(delivery_tag=<nr>) in my consumer. The message gets delivered without problems, but when I'm ready to acknowledge it this happens.

Any idea?

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/marijn/Projects/icm-ms-movieimages/movieimages/processor.py", line 35, in run
    messagehandler.complete(message)
  File "/Users/marijn/Projects/icm-ms-queue/queuehandler/handlers.py", line 88, in complete
    self.on_complete(message.number, message.status)
  File "/Users/marijn/Projects/icm-ms-queue/queuehandler/__init__.py", line 150, in on_message_complete
    self.on_message_processed(delivery_tag)
  File "/Users/marijn/Projects/icm-ms-queue/queuehandler/__init__.py", line 154, in on_message_processed
    self._channel.basic_ack(delivery_tag=delivery_tag)
  File "/Users/marijn/.virtualenvs/icm-ms-3.6/lib/python3.6/site-packages/pika/channel.py", line 200, in basic_ack
    return self._send_method(spec.Basic.Ack(delivery_tag, multiple))
  File "/Users/marijn/.virtualenvs/icm-ms-3.6/lib/python3.6/site-packages/pika/channel.py", line 1328, in _send_method
    self.connection._send_method(self.channel_number, method, content)
  File "/Users/marijn/.virtualenvs/icm-ms-3.6/lib/python3.6/site-packages/pika/connection.py", line 2170, in _send_method
    self._send_frame(frame.Method(channel_number, method))
  File "/Users/marijn/.virtualenvs/icm-ms-3.6/lib/python3.6/site-packages/pika/connection.py", line 2154, in _send_frame
    self._flush_outbound()
  File "/Users/marijn/.virtualenvs/icm-ms-3.6/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 318, in _flush_outbound
    self._manage_event_state()
  File "/Users/marijn/.virtualenvs/icm-ms-3.6/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 516, in _manage_event_state
    self.event_state)
  File "/Users/marijn/.virtualenvs/icm-ms-3.6/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 194, in update_handler
    self._poller.update_handler(fileno, events)
  File "/Users/marijn/.virtualenvs/icm-ms-3.6/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 401, in update_handler
    events_to_set=events_set)
  File "/Users/marijn/.virtualenvs/icm-ms-3.6/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 874, in _modify_fd_events
    self._kqueue.control(kevents, 0)
OSError: [Errno 9] Bad file descriptor
```

**Comment by lukebakken** [comment]
@marijngiesen - I can see that you're using Python 3.6.1 on OS X, and your code is using the multiprocessing module. I'm wondering if you're running into [this scenario](https://stackoverflow.com/a/45468294).

If you can provide code that reliably reproduces this issue, feel free to re-open this issue and I'll take a look. Thanks!
