### ISSUE TITLE
ssl_handshake error

### ISSUE THREAD

**Issue by TsioryAntonio** [pika/pika#893]
Hi,
I've rabbitMQ server installed in a Centos Vm. 
I have to connect to this rabbitMQ server on a Windows computer using pika.
Everything works well when ssl is not enabled. 

Using pika-0.11.0, when enabling SSL I got an error saying:

```Traceback (most recent call last):
  File "test_pika.py", line 18, in <module>
    conn = pika.BlockingConnection(cp)
  File "C:\Python_virtual_Env\vait\lib\site-packages\pika\adapters\blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "C:\Python_virtual_Env\vait\lib\site-packages\pika\adapters\blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "C:\Python_virtual_Env\vait\lib\site-packages\pika\adapters\blocking_connection.py", line 468, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
pika.exceptions.ConnectionClosed: Connection to 192.168.105.209:5671 failed: [Errno 10054] An existing connection was forcibly closed by the remote host 
```
In rabbitMQ logs:
```=ERROR REPORT==== 20-Nov-2017::15:51:00 ===
Error on AMQP connection <0.520.0>:
{ssl_upgrade_failure,
    {{function_clause,
         [{tls_v1,enum_to_oid,[28],[{file,"tls_v1.erl"},{line,404}]},
          {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,
              [{file,"ssl_handshake.erl"},{line,1657}]},
          {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,
              [{file,"ssl_handshake.erl"},{line,1657}]},
          {ssl_handshake,dec_hello_extensions,2,
              [{file,"ssl_handshake.erl"},{line,1657}]},
          {tls_handshake,decode_handshake,3,
              [{file,"tls_handshake.erl"},{line,182}]},
          {tls_handshake,get_tls_handshake_aux,3,
              [{file,"tls_handshake.erl"},{line,153}]},
          {tls_connection,next_state,4,
              [{file,"tls_connection.erl"},{line,454}]},
          {gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,505}]}]},
     {gen_fsm,sync_send_all_state_event,[<0.521.0>,{start,5000},infinity]}}}
```

This error happened when I try to connect to rabbitMQ on Windows. On Mac OS or on Centos, it works well.

My rabbitmq.config:
```
[
 {
     rabbit,
     [
      	 {loopback_users, []},
         {ssl_cert_login_from, common_name},
         {ssl_listeners, [{"0.0.0.0", 5671}]},
         {auth_mechanisms, ['PLAIN', 'AMQPLAIN', 'EXTERNAL']},
         {
             ssl_options, [
                 {cacertfile,"/etc/ssl/factory/CA_cert.pem"},
                 {certfile,"/etc/ssl/server/server-cert.pem"},
                 {keyfile,"/etc/ssl/server/server-key.pem"},
                 {verify,verify_none},
                 {fail_if_no_peer_cert,false}
             ]
         }
     ]
 }
].
```

To test the rabbitmq connection, I used this script which run well on Mac OS and Centos but not on Windows:
```python 
import pika
import ssl

cp = pika.ConnectionParameters(
    host='192.168.105.209',
    port=5671,
    ssl=True,
    ssl_options=dict(
        ca_certs="CA_cert.pem",
        cert_reqs=ssl.CERT_REQUIRED
    )
)

conn = pika.BlockingConnection(cp)
ch = conn.channel()
print(ch.queue_declare("sslq"))
ch.publish("", "sslq", "abc")
print(ch.basic_get("sslq"))
```
I use 
- python 2.7.10
- rabbitMQ 3.5.6 (I test it using 3.6.14 too)
- pika 0.11.0
 
Do you know how to resolve this?

**Comment by lukebakken** [comment]
Hello!

Your error contains the string `tls_v1,enum_to_oid,[28]` which is a common error when you use an old Erlang version. You need to use a more recent version, preferably Erlang `19.3` or `20.1`.

If you upgrade and that does not resolve the issue, please re-open this issue. Thanks!
