### ISSUE TITLE
pika.exceptions.ConnectionClosed 

### ISSUE THREAD

**Issue by behconsci** [pika/pika#926]
I am getting this issue, here is the traceback: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/handler.py", line 360, in __call__
    message.reply_channel.send(reply_message, immediately=True)
  File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 44, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python3.6/site-packages/asgi_rabbitmq/core.py", line 812, in send
    return future.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/handler.py", line 360, in __call__
    message.reply_channel.send(reply_message, immediately=True)
  File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 44, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python3.6/site-packages/asgi_rabbitmq/core.py", line 812, in send
    return future.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/build/apps/core/decorators.py", line 74, in inner
    return func(message, user=user, *args, **kwargs)
  File "/build/apps/core/consumers.py", line 110, in ws_message
    handler(action, message, user)
  File "/build/apps/core/consumers.py", line 35, in subscribe_handler
    Group('games').add(message.reply_channel)
  File "/usr/local/lib/python3.6/site-packages/channels/channel.py", line 70, in add
    self.channel_layer.group_add(self.name, channel)
  File "/usr/local/lib/python3.6/site-packages/asgi_rabbitmq/core.py", line 839, in group_add
    return future.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
pika.exceptions.ConnectionClosed
```

and this is log from rabbitmq:

```
=WARNING REPORT==== 19-Jan-2018::09:35:40 ===
closing AMQP connection <0.23091.32> (172.20.0.5:39504 -> 172.20.0.2:5672, vhost: '/', user: 'guest'):
client unexpectedly closed TCP connection
```

I have these versions of: 
```
asgi-rabbitmq==0.5.5
pika==0.11.2
```

I am not sure what is happening. I think, pika is doing something that keeps him busy for longer than needed, as a result he cannot accept further messages ---> rabbitmq thinks pika is dead and closes the connection... but this is just my guess.. 

can you guys please look at it? any hotfix would be also acceptable

**Comment by lukebakken** [comment]
Could you please post this to [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users)? If you are using a proxy, please indicate that, as well as provide the following information:

* RabbitMQ and Erlang version
* Library versions (like you provided here)
* Operating system and version
* Virtual environment, if used (cloud vendor, VirtualBox, etc)

If, after discussion on the mailing list, an actual issue is found, we can open it here. Thanks.
