### ISSUE TITLE
Blocking connection hanging on basic_consume when using a pacemaker

### ISSUE THREAD

**Issue by stuartspotlight** [pika/pika#927]
I've already posted this in a closed thread but I'm not sure if that's the correct way to do these things so I'm asking again here. I've created a little library to bind some processing function to a rabbitMQ queue and then perform that processing once something is placed on the queue. The problem I had is that sometimes the execution of the code is sometimes longer than the heartbeat so I added a pacemaker as described [here](https://github.com/eandersson/python-rabbitmq-examples/blob/master/Flask-examples/pika_async_rpc_example.py).
The code for this pacemaker is below:-

```
class heart_runner():
    
    def __init__(self, connection):
        
        if "blockingconnection" not in str(connection).lower() and "mock" not in str(connection).lower():
            raise Exception("Heartbeat runner requires a connection to rabbitmq as connection, actually has %s, a %s"%(str(connection), type(connection)))
        
        if connection.is_open == False:
            raise Exception("Heart runner's connection to rabbitmq should be open, is actually closed")
        
        self.connection = connection
        self.internal_lock = threading.Lock()
    

    def _process_data_events(self):
            """Check for incoming data events.
            We do this on a thread to allow the flask instance to send
            asynchronous requests.
            It is important that we lock the thread each time we check for events.
            """
    
            while True:
                with self.internal_lock:
                    self.connection.process_data_events()
                    #This is how often to run the pacemaker
                    time.sleep(0.1)
```
and then ran it in a separate thread using 

```
    #setup the pacemaker
    pacemaker = heart_runner(connection)

    #set up this deamon thread in order to avoid everything dying due to a heartbeat timeout
    thread = threading.Thread(target=pacemaker._process_data_events)
    thread.setDaemon(True)
    thread.start()
```

but I found when digesting large number of messages the thread would often hang on basic_consume. When I used ctrl+C to stop it the resulting error read:-

```
Traceback (most recent call last):
  File "./example_binding_main.py", line 121, in <module>
    bind(main, "example-function")
  File "/nanowire_plugin.py", line 287, in bind
    input_channel.start_consuming()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1780, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 707, in process_data_events
    self._flush_output(common_terminator)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 455, in _flush_output
    self._impl.ioloop.poll()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 245, in poll
    self._poller.poll()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 923, in poll
    events = self._poll.poll(self._get_next_deadline())
KeyboardInterrupt

```

Since I figured that the process_data_events() function must be causing the timeout I decided to add in a timeout of ten seconds, connection.process_data_events(10) however this lead to the error:-

```
     bind(main, "example-function")
  File "/binding_function_to_queue.py", line 287, in bind
    input_channel.start_consuming()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1775, in start_consuming
    'start_consuming may not be called from the scope of '
pika.exceptions.RecursionError: start_consuming may not be called from the scope of another BlockingConnection or BlockingChannel callback 

```

Is there a way to either prevent the hanging problem or else to add a timeout that will trigger when this happens? Sorry if this question is in the wrong place

**Comment by lukebakken** [comment]
* What was the closed issue?
* Can you please provide a self-contained program that demonstrates this issue?

**Comment by stuartspotlight** [comment]
Part of the problem is that the problem only rears its head quite rarely, as in when I try to ingest and process a large number of files (e.g. 100,000 tweets) very quickly, up to 30 files a second. The code I'm using can be found at on the spotlightdata github repo [here](https://github.com/SpotlightData/nanowire-plugin-py).

**Comment by stuartspotlight** [comment]
I've simplified the code so that the library that handles pika is here:-
```
#!/usr/bin/env python3
"""
Provides a `bind` function to plugins so they can simply bind a function to a queue.
"""
import logging
import json
from os import environ

import threading


import time
import pika
import datetime



#set up the logger globally
logger = logging.getLogger("nanowire-plugin")



class heart_runner():
    
    def __init__(self, connection):
        
        if "blockingconnection" not in str(connection).lower() and "mock" not in str(connection).lower():
            raise Exception("Heartbeat runner requires a connection to rabbitmq as connection, actually has %s, a %s"%(str(connection), type(connection)))
        
        if connection.is_open == False:
            raise Exception("Heart runner's connection to rabbitmq should be open, is actually closed")
        
        self.connection = connection
        self.internal_lock = threading.Lock()
    

    def _process_data_events(self):
            """Check for incoming data events.
            We do this on a thread to allow the flask instance to send
            asynchronous requests.
            It is important that we lock the thread each time we check for events.
            """
    
            while True:
                with self.internal_lock:
                    #This is a command to run a heartbeat. It has a limit of 10
                    #seconds becuase it kept hanging here due to pika not being fully thread
                    #safe
                    self.connection.process_data_events()
                    #This is how often to run the pacemaker
                    time.sleep(0.1)



#create a class so we can feed things into the on_request function
class on_request_class():
    
    def __init__(self, function, name, output_channel):
        

        
        self.name = name
        self.function = function
        self.output_channel = output_channel
        

    def on_request(self, ch, method, props, body):
        
        #check the channel is open
        if not ch.is_open:
            raise Exception("Input channel is closed")


        #check the body is a byte string
        if not isinstance(body, bytes):
            raise Exception("The body data should be a byte stream, it is actually %s, %s"%(body, type(body)))

        

        #set up logging inside the server functions
        logger.setLevel(logging.DEBUG)

        data = body.decode("utf-8")

        payload = json.loads(data)

        returned = send(self.name, payload, ch, self.output_channel, method, props, self.function)
        

        logger.info("Finished running user code at %s"%str(datetime.datetime.now()))
        logger.info("returned, %s"%returned)
        logger.info("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
                          
                                                     
def failed_to_grab():
    
    raise Exception("REACHED TIMEOUT, ETHER BECAUSE THERE'S NOTHING ON THE QUEUE OR BECAUSE THE CONNECTION WAS HANGING AGAIN")
    
    logger.info("Failed to grab a message")


def bind(function, name, version="1.0.0", pulserate=30):
    """binds a function to the input message queue"""
    
    #set up the logging
    logger.setLevel(logging.DEBUG)
    
    logger.info("Running with pika version %s"%str(pika.__version__))

    #write to screen to ensure logging is working ok
    #print "Initialising nanowire lib, this is a print"
    logger.info("initialising nanowire lib")
    
    logger.info("initialising plugin: %s"%name)

    #set the parameters for pika
    parameters = pika.ConnectionParameters(
        host=environ["AMQP_HOST"],
        port=int(environ["AMQP_PORT"]),
        credentials=pika.PlainCredentials(environ["AMQP_USER"], environ["AMQP_PASS"]),
        heartbeat=pulserate,
        socket_timeout=10,
        blocked_connection_timeout=120)

    #set up pika connection channels between rabbitmq and python
    connection = pika.BlockingConnection(parameters)
    
    #This is an attempt to fix the problem with basic_consume hanging on consume sometimes. THIS
    #IS AN EXPEREMENT AND MAY WELL NOT WORK!!!!!
    connection.add_timeout(900, failed_to_grab)
    
    #add something to stop the connection hanging when it's supposed to be grabbing. This does not work
    connection.add_on_connection_blocked_callback(failed_to_grab)
    input_channel = connection.channel()
    output_channel = connection.channel()
    
    #The confirm delivery on the input channel is an attempt to fix the hanging problem. IT MIGHT NOT WORK!!!
    input_channel.confirm_delivery()
    output_channel.confirm_delivery()

    #setup the pacemaker
    pacemaker = heart_runner(connection)

    #set up this deamon thread in order to avoid everything dying due to a heartbeat timeout
    thread = threading.Thread(target=pacemaker._process_data_events)
    thread.setDaemon(True)
    thread.start()


    logger.info("initialised nanowire lib", extra={
        "rabbit": environ["AMQP_HOST"]
    })
    
    logger.info("rabbit: %s"%environ["AMQP_HOST"])


    logger.info("consuming from %s"%name)

    input_channel.queue_declare(name, durable=True)

    #all the stuff that needs to be passed into the callback function is stored
    #in this object so that it can be easily passed through
    requester = on_request_class(function, name, output_channel)
    
    #set the queue length to one
    input_channel.basic_qos(prefetch_count=1)    
    
    #The inactivity timeout might cause the pod to die and restart every 15 minutes when the queue is empty. This is
    #an attempt to fix the problem with the system hanging on basic_consume THIS IS EXPEREMENTAL AT THE MOMENT, IT MIGHT
    #NOT FIX THE PROBLEM!!!!
    input_channel.basic_consume(requester.on_request, queue=name, no_ack=False)
    
    logger.info("Created basic consumer")

    input_channel.start_consuming()
    
    logger.info("Past start consuming, not sure whats going on...")




def get_this_plugin(this_plugin, workflow):
    """ensures the current plugin is present in the workflow"""
    
    #perform type checking
    if not isinstance(this_plugin, str):
        raise Exception("Plugin name must be a string")
    
    if not isinstance(workflow, list):
        raise Exception("Workflow must be a list")
        
    if len(workflow) == 0:
        raise Exception("Workflow is empty, something is wrong")
    
    
    logger.info("this_plugin: %s"%this_plugin)
    
    for i, workpipe in enumerate(workflow):
        if workpipe["config"]["name"] == this_plugin:
            return i
    return -1


def send(name, payload, next_plugin, input_channel, output_channel, method, properties, function):
    #Sends the result to the next queue in the pipeline
    
    
    #log some info about what the send function has been given
    logger.info("consumed message")
    logger.info("channel %s"%input_channel)
    logger.info("method %s"%method)
    logger.info("properties %s"%properties)
    
    result = function(payload["jsonld"])
    
    
    #send the info from this plugin to the next one in the pipeline
    send_to_next_queue(next_plugin, result, output_channel)
    
    #Let the frontend know that we're done
    input_channel.basic_ack(method.delivery_tag)

    return {}


    
def send_to_next_queue(next_queue, payload, output_channel):

    if next_queue != None:
            
        #declare a queue for outputing the results to the next plugin
        output_channel.queue_declare(
            next_queue,
            durable=True
            )
        
        #send the result from this plugin to the next plugin in the pipeline
        _ = output_channel.basic_publish("", next_queue, json.dumps(payload), pika.BasicProperties(content_type='text/plain', delivery_mode=2))
        
```

This library can then be used like this:-

```
#example main function

from example_rabbit_library import bind


def main(jsonld):
    
    if "text" in jsonld.keys():
        
        jsonld["cat-finder"] = {}
        jsonld["cat-finder"]["@type"] = "PropertyValue"
        jsonld["cat-finder"]["measurementTechnique"] = "basic-cat-finding"
        jsonld["variableMeasured"] = []
        
        if "cat" in jsonld["text"]:
            
            result_dict = {}
            result_dict["@type"] = "PropertyValue"
            result_dict["name"] = "found-cat"
            result_dict["value"] = "1"
            
            
    return jsonld
    
    
bind(main, "example-function")
```

The function detailed is a something simple designed to pass data through quickly to give a better chance of replicating the intermittent bug. It might be worth trying to pass this through repeatedly to try and recreate the problem:-

```
{
    "@type": "SocialMediaPosting",
    "@id": "955640572072652800",
    "author": {
        "@type": "Person",
        "@id": "954949663173567891",
        "name": "Anon"
    },
    "publisher": {
        "@type": "Organization",
        "name": "Twitter"
    },
    "dateCreated": "2018-01-23T07:17:22.253Z",
    "datePublished": "2018-01-23T07:17:21.000Z",
    "text": Here is some example text",
    "keywords": [
        "example tweet"
    ],
    "interactionStatistic": [
        {
            "interactionType": "http://schema.org/CommentAction",
            "@type": "InteractionCounter",
            "userInteractionCount": 0
        },
        {
            "interactionType": "http://schema.org/ReplyAction",
            "@type": "InteractionCounter",
            "userInteractionCount": 0
        },
        {
            "interactionType": "http://schema.org/ShareAction",
            "@type": "InteractionCounter",
            "userInteractionCount": 0
        },
        {
            "interactionType": "http://schema.org/FollowAction",
            "@type": "InteractionCounter",
            "userInteractionCount": 0
        }
    ],
    "sharedContent": [],
    "provider": {
        "@type": "Organization",
        "name": "Twitter for Android"
    },
    "mentions": [],
    "@graph": [
    ]
}

```

Given that the problem arises when using a pacemaker and the exception references the process_data_events function could it be that if heartbeats are sent from separate threads the system hangs? Why does the introduction of a timeout to the process_data_events function produce an error? 
Thanks for the help

**Comment by stuartspotlight** [comment]
I've found that waiting to start the pacemaker allows you to use the time_limit parameter on process_data_events. The code for the pacemaker is now:-
```
class heart_runner():
    
    def __init__(self, connection):
        
        if "blockingconnection" not in str(connection).lower() and "mock" not in str(connection).lower():
            raise Exception("Heartbeat runner requires a connection to rabbitmq as connection, actually has %s, a %s"%(str(connection), type(connection)))
        
        if connection.is_open == False:
            raise Exception("Heart runner's connection to rabbitmq should be open, is actually closed")
        
        self.connection = connection
        self.internal_lock = threading.Lock()
    

    def _process_data_events(self):
            """Check for incoming data events.
            We do this on a thread to allow the flask instance to send
            asynchronous requests.
            It is important that we lock the thread each time we check for events.
            """
            time.sleep(1)
    
            while True:
                with self.internal_lock:
                    #This is a command to run a heartbeat. It has a limit of 10
                    #seconds becuase it kept hanging here due to pika not being fully thread
                    #safe
                    
                    self.connection.process_data_events(time_limit=1)
                    time.sleep(1)
                    #This is how often to run the pacemaker
```

This seems to have made the hanging problem significantly worse

**Comment by stuartspotlight** [comment]
I've made an effort to simplyfy the issue. I tried using the signal library to create a timeout for the pacemaker but that failed since signal cannot be used on a deamon thread so I'm going to post a simplified version of the full issue in case someone has a way of adding a timeout to the pacemaker on a second thread. A simplified version of the code is shown below:-
```
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 25 11:30:46 2017

@author: stuart
"""

#!/usr/bin/env python3
"""
Provides a `bind` function to plugins so they can simply bind a function to a queue.
"""
import logging
import json
from os import environ

import threading
import signal

import time
import pika


#set up the logger globally
logger = logging.getLogger("nanowire-plugin")


class pacemaker_timeout:
    
    def __init__(self, seconds=1, error_message='Timeout'):
        
        self.seconds = seconds
        self.error_message = error_message
        
    def handle_timeout(self, signum, frame):
        
        raise TimeoutError(self.error_message)
        
    def __enter__(self):
        signal.signal(signal.SIGALRM, self.handle_timeout)
        signal.alarm(self.seconds)
        
    def __exit__(self, type, value, traceback):
        signal.alarm(0)


class heart_runner():
    
    def __init__(self, connection):
        
        if "blockingconnection" not in str(connection).lower() and "mock" not in str(connection).lower():
            raise Exception("Heartbeat runner requires a connection to rabbitmq as connection, actually has %s, a %s"%(str(connection), type(connection)))
        
        if connection.is_open == False:
            raise Exception("Heart runner's connection to rabbitmq should be open, is actually closed")
        
        self.connection = connection
        self.internal_lock = threading.Lock()
    

    def _process_data_events(self):
            """Check for incoming data events.
            We do this on a thread to allow the flask instance to send
            asynchronous requests.
            It is important that we lock the thread each time we check for events.
            """
    
            while True:
                with self.internal_lock:
                    #This is a command to run a heartbeat. I have used the signal library
                    #to add a 10 second timeout because it kept hanging.
                    with pacemaker_timeout(seconds=10, error_message="Pacemaker has timed out"):
                        
                        #This is the section causing the trouble. Since it hangs occasionally and I can't add a timeout using
                        #the signal library in python 2
                        self.connection.process_data_events()
                        
                    time.sleep(1)
                    #This is how often to run the pacemaker
                    

#create a class so we can feed things into the on_request function
class on_request_class():
    
    def __init__(self, function, name, output_channel):
        
       
        self.name = name
        self.function = function
        self.output_channel = output_channel
        

    def on_request(self, ch, method, props, body):
        
        #when a piece of data is found on the queue it is picked off and converted into a dictionary
        payload = json.loads(body)

    
        returned = send(self.name, payload, ch, self.output_channel, method, props, self.function)
        
                                                 

def bind(function, name, version="1.0.0", pulserate=30):
    """binds a function to the input message queue"""

    #set the parameters for pika, here we are setting the pika host and details
    parameters = pika.ConnectionParameters(
        host=environ["AMQP_HOST"],
        port=int(environ["AMQP_PORT"]),
        credentials=pika.PlainCredentials(environ["AMQP_USER"], environ["AMQP_PASS"]),
        heartbeat=pulserate)

    #set up pika connection channels between rabbitmq and python
    connection = pika.BlockingConnection(parameters)
    
    
    #add something to stop the connection hanging when it's supposed to be grabbing. This does not work
    #connection.add_on_connection_blocked_callback(failed_to_grab)
    input_channel = connection.channel()
    output_channel = connection.channel()
    
    #The confirm delivery on the input channel is an attempt to fix the hanging problem. IT MIGHT NOT WORK!!!
    input_channel.confirm_delivery()
    output_channel.confirm_delivery()

    #setup the pacemaker
    pacemaker = heart_runner(connection)

    #set up this deamon thread in order to avoid everything dying due to a heartbeat timeout
    thread = threading.Thread(target=pacemaker._process_data_events)
    thread.setDaemon(True)
    thread.start()


    #make sure the queue we want to injest from exists
    input_channel.queue_declare(name, durable=True)

    #all the stuff that needs to be passed into the callback function is stored
    #in this object so that it can be easily passed through
    requester = on_request_class(function, name, output_channel)
    
    #set the queue length to one
    input_channel.basic_qos(prefetch_count=1)    
    
    #create the consumer
    input_channel.basic_consume(requester.on_request, queue=name, no_ack=False)
    
    #here is where the basic consumer is created on the main thread
    input_channel.start_consuming()
    




def send(name, payload, input_channel, output_channel, method, properties, function, next_queue):
    """unwraps a message and calls the user function"""  
    
    sending_payload = function(payload)

    #send the info from this plugin to the next one in the pipeline
    send_result = output_channel.basic_publish("", next_queue, json.dumps(sending_payload), pika.BasicProperties(content_type='text/plain', delivery_mode=2))
        

    #Let the rabbitmq know we're done with this one
    input_channel.basic_ack(method.delivery_tag)


###########################################
### End of rabbitMQ interface functions ###
###########################################


def example_function(payload):
    
    text = payload['text']
    
    last_word = text.split(' ')[-1]
    
    payload["last_word"] = last_word
    
    return payload
    
    

#This is an example of how the bind function is used. What it is doing in this
#example is irrelevant
bind(example_function, 'example-function')

```

The problem is on line 85 where I attempt to perform an artificial heartbeat, using process_data_events(), to rabbitMQ. This has a habbit of causing the system to hang producing no errors randomly and if you use the timeout parameter for process_data_events() this will cause the artificial heartbeat to hang every time it is called. Does anyone know a thread safe way to add a timeout to this separate thread that will kill python allowing the automated recovery system to restart the program thereby clearing the hanging problem. Please note that this method must work in both python 2 and python 3?

Thank you

**Comment by vitaly-krugl** [comment]
Current releases of pika are not thread-safe, so you can't access a connection from multiple threads. However, pull request #956 will enable you to offload the time-consuming step to a thread and then delegate the ACK request for the message via new method `add_callback_threadsafe`, while your pika connection is keeping heartbeats alive via `connection.process_data_events` or `channel.start_consuming`, etc., and without the need for complicated locking.

**Comment by michaelklishin** [comment]
A suggestion from the sidelines if I may: a [traffic dump](https://www.rabbitmq.com/amqp-wireshark.html) would greatly help here. If this is primarily about the lack of a timeout for `basic.consume` operations, it'd still be great to have some evidence of what the client does before an operation blocks.

**Comment by stuartspotlight** [comment]
![screen shot 2018-02-19 at 15 44 02](https://user-images.githubusercontent.com/31960846/36385890-e8bcd87e-158b-11e8-9af3-8ebf68d1694c.png)
![screen shot 2018-02-19 at 15 43 36](https://user-images.githubusercontent.com/31960846/36385896-ec46f88a-158b-11e8-843f-2c6dc5658c0f.png)
Here are two screenshots from wireshark. They show that before the hang there are no heartbeats but as soon as the heartbeats start all other traffic stops

**Comment by vitaly-krugl** [comment]
@michaelklishin, if I was not mistaken, the application in question here is using a single pika connection from multiple threads. This is unsupported per pika implementation and FAQ and has been - not surprisingly - shown time and again to cause hangs and other issues by those who tried.

Further, if you look at popular and efficient python event loops such as Tornado, Twisted, and now Python3 asyncio, none of them are thread-safe, but they do offer a single method to enable threads to interact safely with the event loop. Pull request #956 adds this capability to pika via the `add_callback_threadsafe` method. @stuartspotlight should be able to delegate the lengthy processing of the message to another thread and then have that thread safely ACK the message through the instance of `BlockingConnection` via the new method `add_callback_threadsafe` without relying on the unsafe "pacemaker", assuming the event loop of the `BlockingConnection` is kept running via the likes of `BlockingConnection.process_data_events()`,  `BlockingChannel.start_consuming()`, `BlockingChannel.consume()`, or `BlockingConnection.sleep()`.

**Comment by vitaly-krugl** [comment]
The code included in this issue accesses and modifies the connection's and ioloop's data structures and other resources from two separate threads, which is a classic race condition recipe.

**Comment by vitaly-krugl** [comment]
@lukebakken, I think this one is safe to close. The approved mechanism `add_callback_threadsafe` is now available on all supported I/O loops in master.

**Comment by lukebakken** [comment]
Fixed by #956

**Comment by joao-conde** [comment]
Hello and sorry to re-open this discussion.

Regarding this quote:
> ... Pull request #956 adds this capability to pika via the `add_callback_threadsafe` method. @stuartspotlight should be able to delegate the lengthy processing of the message to another thread and then have that thread safely ACK the message through the instance of `BlockingConnection` via the new method `add_callback_threadsafe` without relying on the unsafe "pacemaker", assuming the ioloop of the `BlockingConnection` instance is kept running via the likes of `BlockingConnection.process_data_events()`, `BlockingChannel.start_consuming()`, `BlockingChannel.consume()`, or `BlockingConnection.sleep()`.

Does this apply to `basic_publish` too? Say I have multiple threads publishing to an exchange, I should make use of `add_callback_threadsafe` to add a publish callback, right?

If the above is correct, then I have the following problem. Currently I am trying to use `basic_publish` with `add_callback_threadsafe` but the publish callback is never called. I ran the debugger and saw it was correctly added to the `callbacks` queue in pika. So I was wondering why it was never consumed.

Given the comment of @vitaly-krugl I just quoted, the connection must be kept alive through the mentioned methods. However, I tried the following setup (and it didnt work):

producer.py
```python
#!/usr/bin/env python
import pika
import functools

parameters = pika.ConnectionParameters(
    host = "172.19.0.2",
    credentials = pika.PlainCredentials("guest", "guest"),
    socket_timeout = 100
)
connection = pika.BlockingConnection(parameters)

channel = connection.channel()
channel.basic_qos(prefetch_count = 1)

channel.exchange_declare(
    exchange = "work-exchange",
    exchange_type = "x-random",
    durable = False
)

# PUBLISH THREADSAFE CALLBACK
connection.add_callback_threadsafe(
    functools.partial(
        channel.basic_publish,
        exchange = "work-exchange",
        routing_key = "",
        body = "hello",
        properties = pika.BasicProperties(
            delivery_mode = 2,
            priority = 0
        )
    )
)
```

and consumer.py

```python
#!/usr/bin/env python
import pika

parameters = pika.ConnectionParameters(
    host = "172.19.0.2",
    credentials = pika.PlainCredentials("guest", "guest"),
    socket_timeout = 100
)
connection = pika.BlockingConnection(parameters)

channel = connection.channel()
channel.basic_qos(prefetch_count = 1)

channel.queue_declare(
    queue = "ripe-work-1",
    durable = False,
    arguments = {
        "x-max-priority" : 255
    }
)

def handler(channel, method, properties, body):
    print("Rcv:", body)

channel.basic_consume(
    queue = "ripe-work-1",
    on_message_callback = handler,
    auto_ack = True
)

channel.start_consuming()
```

What happens is that the callback is never called and thus the message is never published. However, if I do the following in the producer script:

```python
#!/usr/bin/env python
import pika
import functools

parameters = pika.ConnectionParameters(
    host = "172.19.0.2",
    credentials = pika.PlainCredentials("guest", "guest"),
    socket_timeout = 100
)
connection = pika.BlockingConnection(parameters)

....

...

# NOTE: this line was added
connection.process_data_events()

```

The message is now flushed. Is this how I should make sure the callbacks are called? And how should I loop on this `process_data_events()` ?  Should I call it right after adding the callback each time I try to publish?

I am using pika 1.1.0, python 3.8.5, RabbitMQ 3.8.9 and Erlang 23.1.4 on WSL2, Ubuntu distro 20.04.

Thanks in advance!

**Comment by lukebakken** [comment]
@joao-conde please do not follow up in a closed issue. Either open a new issue with your question, or post a question to the mailing list: https://groups.google.com/g/pika-python

You should really be using the `SelectConnection` connection type: https://github.com/pika/pika/blob/master/examples/asynchronous_publisher_example.py

> Does this apply to basic_publish too? Say I have multiple threads publishing to an exchange, I should make use of add_callback_threadsafe to add a publish callback, right?

Yes that is one option. The other is to synchronize access to the Pika connection object.

If you use `add_callback_threadsafe` you will have to call `process_data_events` afterward. Your publish will also happen the next time a heartbeat is sent to RabbitMQ. In the consuming case that is not necessary as it is always processing data events.

**Comment by joao-conde** [comment]
@lukebakken  sorry for the misplaced comment. Thank you for your help, in case of future questions I will make use of the mailing list.
