### ISSUE TITLE
No immediate exception when publishing to non existent exchange

### ISSUE THREAD

**Issue by decaz** [pika/pika#971]
I have no exchange `NON_EXISTENT_EXCHANGE` within my RabbitMQ server and I expect that the following code will raise exception immediately due to publishing to non existent exchange. But it raises just from time to time and never immediately. I thought that the `BlockingConnection` should guarantee immediate exception.

`test_pika.py`:
```python
from pika import BlockingConnection, ConnectionParameters, PlainCredentials

credentials = PlainCredentials(username='guest', password='guest')
parameters = ConnectionParameters(host='rabbitmq', credentials=credentials)
connection = BlockingConnection(parameters)
channel = connection.channel()

for i in range(10):
    rv = channel.basic_publish(
        exchange='NON_EXISTENT_EXCHANGE', routing_key='', body='')
    print(i, rv)
```
Output 1:
```
$ python test_pika.py
0 True
1 True
2 True
3 True
4 True
5 True
6 True
7 True
8 True
9 True
```
Output 2:
```
$ python test_pika.py
0 True
1 True
2 True
3 True
Traceback (most recent call last):
  File "test_pika.py", line 10, in <module>
    exchange='NON_EXISTENT_EXCHANGE', routing_key='', body='')
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish
    mandatory, immediate)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2164, in publish
    self._flush_output()
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 455, in _flush_output
    self._impl.ioloop.poll()
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 245, in poll
    self._poller.poll()
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 935, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 625, in _dispatch_fd_events
    handler(fileno, events)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 395, in _handle_events
    self._handle_read()
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 449, in _handle_read
    self._on_data_available(data)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/connection.py", line 1938, in _on_data_available
    self._process_frame(frame_value)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/connection.py", line 2059, in _process_frame
    if self._process_callbacks(frame_value):
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/connection.py", line 2040, in _process_callbacks
    frame_value)  # Args
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1316, in _on_channel_closed
    method.reply_text)
pika.exceptions.ChannelClosed: (404, "NOT_FOUND - no exchange 'NON_EXISTENT_EXCHANGE' in vhost '/'")
```
Was tested with `pika` versions 0.10.0 and 0.11.2 - results almost the same.

**Comment by decaz** [comment]
Found the solution: `channel.confirm_delivery()` had to be used.
