### ISSUE TITLE
blocking_connection publish with multiprocessing error FileNotFound

### ISSUE THREAD

**Issue by radzhome** [pika/pika#992]
Looks like this cleanup operation is failing as soon as I added multiprocessing.Pool and ran a publish inside the new process where the connection is defined in the master process, after some time (a few mins)I get this error. Looks like its related to clean up. I assume blocking_connection publish is not thread safe at the moment:

```
03-08 21:46:31 root         [31140] ERROR    RabbitQueue.publish unhandled error [Errno 2] No such file or directory [in /usr/local/virtualenvs/pipeline_py3/src/fanx-service-clients/serviceclients/queue/rabbit.py:publish:135] on feed4
Traceback (most recent call last):
  File "/usr/local/virtualenvs/pipeline_py3/src/fanx-service-clients/serviceclients/queue/rabbit.py", line 127, in publish
    self._channel.basic_publish(exchange=exchange, routing_key=exchange, body=data, properties=props)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish
    mandatory, immediate)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2163, in publish
    immediate=immediate)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/channel.py", line 425, in basic_publish
    (properties, body))
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/channel.py", line 1328, in _send_method
    self.connection._send_method(self.channel_number, method, content)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/connection.py", line 2198, in _send_method
    self._send_message(channel_number, method, content)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/connection.py", line 2230, in _send_message
    self._flush_outbound()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 315, in _flush_outbound
    self._manage_event_state()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 511, in _manage_event_state
    self.event_state)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 194, in update_handler
    self._poller.update_handler(fileno, events)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 401, in update_handler
    events_to_set=events_set)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 972, in _modify_fd_events
    self._poll.modify(fileno, events)
FileNotFoundError: [Errno 2] No such file or directory
```

Is it safe to ignore this error and move on? Is this something that can be patched?

**Comment by lukebakken** [comment]
>  ran a publish inside the new process where the connection is defined in the master process

You can't share anything Pika-related between processes. In your new process, open a new connection and channel(s).

**Comment by radzhome** [comment]
That's no good... thought it was thread-safe now. So basically have to open a new connection in each process in the pool which is created and destroyed using multiprocessing hmm

**Comment by radzhome** [comment]
I created the connection within the new process but same issue

```
raceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/pipeline/python/daemons/split_files.py", line 161, in process_local_file
  File "/usr/local/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
  File "/usr/local/virtualenvs/pipeline_py3/src/fanx-service-clients/serviceclients/queue/rabbit.py", line 502, in shutdown
    self.stop_consuming()
  File "/usr/local/virtualenvs/pipeline_py3/src/fanx-service-clients/serviceclients/queue/rabbit.py", line 439, in stop_consuming
    self._channel.basic_cancel(self.on_cancelok, self._consumer_tag)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/channel.py", line 267, in basic_cancel
    nowait is False else [])
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/channel.py", line 1316, in _rpc
    self._send_method(method)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/channel.py", line 1328, in _send_method
    self.connection._send_method(self.channel_number, method, content)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/connection.py", line 2200, in _send_method
    self._send_frame(frame.Method(channel_number, method))
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/connection.py", line 2184, in _send_frame
    self._flush_outbound()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 315, in _flush_outbound
    self._manage_event_state()
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 511, in _manage_event_state
    self.event_state)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 194, in update_handler
    self._poller.update_handler(fileno, events)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 401, in update_handler
    events_to_set=events_set)
  File "/usr/local/virtualenvs/pipeline_py3/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 972, in _modify_fd_events
    self._poll.modify(fileno, events)
FileNotFoundError: [Errno 2] No such file or directory
"""

The above exception was the direct cause of the following exception:
```

**Comment by lukebakken** [comment]
If this can be reliably reproduced, please provide code to do so. Thanks!
