### ISSUE TITLE
Meeting error when connecting REMOTE HOST

### ISSUE THREAD

**Issue by hustshawn** [pika/pika#998]
Hi, 

I faced below errors when connecting remote host
```
Traceback (most recent call last):
  File "email_sender.py", line 79, in <module>
    pika.ConnectionParameters(RABBITMQ_HOST, RABBITMQ_PORT, '/', credentials))
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 466, in _flush_output
    raise maybe_exception
pika.exceptions.ProbableAuthenticationError: (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')

```
The connection related code like below.

```python
...

        credentials = pika.PlainCredentials(RABBITMQ_USER, RABBITMQ_PASS)

        connection = pika.BlockingConnection(
            pika.ConnectionParameters(RABBITMQ_HOST, RABBITMQ_PORT, '/', credentials))
        channel = connection.channel()

...
```
How ever, if the user and password was set to 'guest' `guest` would work, otherwise the error occurs, anyone has some clue?

**Comment by hustshawn** [comment]
```
$ pip freeze | grep -i pika
pika==0.11.2

$ python --version
Python 3.6.1
```

**Comment by lukebakken** [comment]
You need to add a user to RabbitMQ, set the user's password, and ensure they have the correct permissions. Please see the [RabbitMQ documentation](https://www.rabbitmq.com/rabbitmqctl.8.html#User_Management). If you have further problems, please ask on the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) and not via GitHub issues.

**Comment by hustshawn** [comment]
Thank you and it fixed by add user to RabbitMQ
